### ISSUE TITLE
Availabilty via F-Droid?

### ISSUE THREAD

**Issue by natrius** [emansih/FireflyMobile#10]
Hello, 

just asking if you are planning to make this app available via the f-droid store (Store for Open Source Apps)? I'm interested in Firefly and would like to use it with an app.
(I'm aware it's possible to download the .apk via /releases)

Greetings

Edit: This seems to be a relatively fresh app. Nice!

**Comment by natrius** [comment]
I'm looking forward, asking for F-Droid because i don't have any google-applications installed on my device :) (As said, its possible with the apk download but i have to check manually every time)

Thanks for considering.

**Comment by emansih** [comment]
Hey @natrius , I have requested for inclusion in Fdroid. https://gitlab.com/fdroid/fdroiddata/merge_requests/3910 ;)

**Comment by natrius** [comment]
Ouh sweet, that was suprisingly fast. In this case, i'm going to install firefly and give it a try. :)
Thanks.

And i think people who want to install firefly for selfhosting are using f-droid pretty often.

**Comment by emansih** [comment]
Hey. https://gitlab.com/fdroid/fdroiddata/merge_requests/3910#note_119854040

;)
