### ISSUE TITLE
Available money in budget does not decrease after spending money from budget

### ISSUE THREAD

**Issue by pbartyik** [emansih/FireflyMobile#101]
**Firefly III Server Version:**
5.2.8
**Firefly III Mobile Version:**
2.0.7
**Android Version:**  
10 , security patch 1 June 2020

**Device Information:**  

- BRAND: Nokia
- MODEL: 8 Sirocco
--------------------------------------

In app main screen budget summary shows as always 100.0% available even after creating transactions (either via mobile or web) using budgets.

## Expected Behavior
Spent money decreases available amount in budget.

## Current Behavior
Spent money does not decrease available amount in budget.

## Steps to Reproduce
Install App
Set up budgets online
Add transaction from budget

Thank you for developing this app, it is very useful for adding transactions on the go. Would also love to see quick glance on the dashboard how much is left to spend in specific budgets.

#97 fixed budget detail but this is still present

**Comment by emansih** [comment]
I have fixed this issue in 2.0.8, it's available on my self hosted fdroid and github release page.

**Comment by pbartyik** [comment]
thanks, works with 2.0.8 via your fdroid.
