### ISSUE TITLE
Feature request: Budget summary should show how much is left in each budget

### ISSUE THREAD

**Issue by pbartyik** [emansih/FireflyMobile#102]
**Firefly III Server Version:**
5.2.8
**Firefly III Mobile Version:**
2.0.7
**Android Version:**  
10 , security patch 1 June 2020
--------------------------------------

## Expected Behavior
Budget summary should show much much money is left for spending in each budget.

## Current Behavior
Shows percentage of expenses in budgets.

## Steps to Reproduce
Launch app, click on budget summary.

**Comment by pbartyik** [comment]
For example:


Budget         Spent  Left 
Groceries:     |==----------------| 20 Eur 80 Eur
Beer money  |======----------| 50 Eur 50 Eur
etc

**Comment by emansih** [comment]
![piechart](https://user-images.githubusercontent.com/5896415/87610802-b4517a00-c749-11ea-965c-dc5b9dfa6379.png)


This?

**Comment by pbartyik** [comment]
yes, that screen.

**Comment by emansih** [comment]
It's in the app. Click on budget summary in the dashboard

**Comment by pbartyik** [comment]
ah cool, didn't know I can click on individual pies to get the data :)
