### ISSUE TITLE
App Crash when starting app

### ISSUE THREAD

**Issue by bmml1** [emansih/FireflyMobile#104]
**Firefly III Server Version:**
5.3.3
**Firefly III Mobile Version:**
2.0.8
**Android Version:**  
Android 10 (GrapheneOS)
**Device Information:**  

- BRAND: Google
- MODEL: Pixel3a
--------------------------------------

## Expected Behavior
Open App
## Current Behavior
When opening app the app instantly crashes
## Steps to Reproduce

[logcat.txt](https://github.com/emansih/FireflyMobile/files/4970619/logcat.txt)

**Comment by emansih** [comment]
A few questions, do you have a valid currency, transaction or budget in your firefly iii instance?

**Comment by bmml1** [comment]
Hi, 

thanks for the quick response. I have valid transactions and currency but have not created / am not using a budget so far.

**Comment by emansih** [comment]
Hi,

could you try this apk? https://drive.google.com/file/d/189T9q_We_Gi73gTL_qy84gQMZMqoVjKL/view?usp=sharing

**Comment by bmml1** [comment]
Hi,

this works, thank you very much :)
I could not dirty flash over the existing installation though.
What caused the crash?

**Comment by emansih** [comment]
to be honest, I have no idea. I'm serious. I expected the new apk to crash and you will provide me with a deobfuscated stack trace to work with. :^)
