### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by bmml1** [emansih/FireflyMobile#105]
**Firefly III Server Version:**
5.3.3
**Firefly III Mobile Version:**
2.10
**Android Version:**  
10
**Device Information:**  

- BRAND: Google
- MODEL: Pixel 3a
--------------------------------------

## Expected Behavior
Starting App
## Current Behavior
Crash on Startup. The first start after a fresh install from your f-droid repo worked. I think I then played around in creating a new transaction view. 
Also the app logo seems to be broken.
## Steps to Reproduce

[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/4974176/Fireflyiii-mobile.txt)
![applogo](https://user-images.githubusercontent.com/32018487/88434254-1c662700-ce00-11ea-91c9-d8c6c0c34db9.png)

**Comment by emansih** [comment]
Regarding the icon bug, what launcher are you using? I cannot replicate it on my device(nova launcher) and Pixel 3a emulator

**Comment by emansih** [comment]
Regarding the crash, I suspect it is a bug in google's material library. It would crash about 30% of the time.  Currently, I am using `1.3.0-alpha02`, downgrading to `1.3.0-alpha01` has stopped the crash.

**Comment by emansih** [comment]
Try this APK https://drive.google.com/file/d/1pZBkRmMFywOOU5aI7k-_Lb0QPfncLXsj/view?usp=sharing

**Comment by bmml1** [comment]
Hi, 
the launcher is GrapheneOS Launcher.
Can you publicly share the apk. Google wants a log in?

**Comment by emansih** [comment]
sorry about it. https://drive.google.com/file/d/1pZBkRmMFywOOU5aI7k-_Lb0QPfncLXsj/view?usp=sharing

**Comment by bmml1** [comment]
Still crashing but I think a different exception, icon is back again though.
[Fireflyiii-mobile_new.txt](https://github.com/emansih/FireflyMobile/files/4975057/Fireflyiii-mobile_new.txt)

**Comment by emansih** [comment]
a couple of questions, were you in Withdrawal / Deposit / Transfer transaction screen when this error occurred? Did you click on any text fields while in any of those screens?

**Comment by bmml1** [comment]
no this this happenend when just normally starting the app. 
In between I have tested the shortcut to transaction when you longpress the app icon which resulted in the error but I could stay in the transaction screen. 
I may pressed some buttons but can't recall. I closed the app, deleted cache and then started again.

This log is def just opening the app:
[Fireflyiii-mobile_new_new.txt](https://github.com/emansih/FireflyMobile/files/4975121/Fireflyiii-mobile_new_new.txt)

**Comment by emansih** [comment]
ah, i have a feeling it may not be a bug in Google's material library after all. It could be due to race conditions caused by Google's new [desugaring library](https://developer.android.com/studio/releases/gradle-plugin#j8-library-desugaring)

**Comment by emansih** [comment]
Try this APK. I have reverted back to the old ThreeTenBp library. https://drive.google.com/file/d/16WijJGXpLZFJyMyzhFm5xj032gvOYLKK/view?usp=sharing

**Comment by bmml1** [comment]
[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/4975326/Fireflyiii-mobile.txt)
Same behaviour

**Comment by emansih** [comment]
found the bug. it seems that Firefly III API docs was not updated. 

In API 1.2.0, transaction endpoint gives me YYYY-mm-DD(2018-09-17) format. However in API 1.3.0 the endpoint is giving me 2020-07-25T02:00:00+02:00 which includes timezone data.

**Comment by emansih** [comment]
@bmml1 can you try this APK? If all is good I will push an update out https://drive.google.com/file/d/19d0lpJz6qieiWMKYtZbOyX76oVfSMZU6/view?usp=sharing

**Comment by bmml1** [comment]
still crashing 
[Fireflyiii-mobile (2).txt](https://github.com/emansih/FireflyMobile/files/4976306/Fireflyiii-mobile.2.txt)

**Comment by emansih** [comment]
I can assure you this APK works. https://drive.google.com/file/d/14Nl7QfZNXSX3wqoEUuNQPgqPVNxOOsfi/view?usp=sharing

**Comment by bmml1** [comment]
Yes this one works. Great work. What was the final reason? :)

**Comment by emansih** [comment]
Some dates were blank and the code didn't handle it well.
