### ISSUE TITLE
Crash when offline

### ISSUE THREAD

**Issue by bmml1** [emansih/FireflyMobile#106]
**Firefly III Server Version:**
 5.3.3
**Firefly III Mobile Version:**
APK from https://github.com/emansih/FireflyMobile/issues/105
**Android Version:**  
10
**Device Information:**  

- BRAND: Pixel
- MODEL: 3a
--------------------------------------
The app crashes when host can not be reached. I think it did not happen with official release.
This probably belongs into
 another issue: 
It would be nice to have a list of pending transactions when in "offline" modus. In official release I could create an offline transaction but it was never synced and I could not see it in the app.
## Expected Behavior
App starts and works with cached data?! Transactions can be created and synced when host is reachable.
## Current Behavior
App crashes on startup
## Steps to Reproduce

[Fireflyiii-mobile_offline.txt](https://github.com/emansih/FireflyMobile/files/4977259/Fireflyiii-mobile_offline.txt)

**Comment by emansih** [comment]
yea... When I wrote the app, the main goal has always been offline first. Thanks for your report

**Comment by emansih** [comment]
check out the latest release. i have fixed it

**Comment by bmml1** [comment]
The app is not crashing anymore. :+1: 
However offline transactions are not working or I am doing something wrong.

I disconnect from my lan where the firefly instance is running. Then I create a withdrawal transaction, a message toasts appears stating something like "your transaction will be added when you are back online" also at the same time an android notification comes up with something like "server could not be reached".

Now after that I can not see this transaction nor will it be added when I connect again. 
You can close this issue and I can create a seperate one if you want.

**Comment by emansih** [comment]
I would say it is _working as intended_. The app will try at most **ONCE** when attempting to add transactions. There is no exception or fallback mechanism. I would not want to try submitting transaction repeatedly when it fails for the first time since it is a waste of battery and network data. (albeit it consumes very little resources.)

**Comment by emansih** [comment]
The current logic is if user is offline, wait for user to get back online. When WiFi / Mobile data is being detected, attempt to submit transaction.

**Comment by emansih** [comment]
Try this for transaction only. https://drive.google.com/file/d/1ET-D1KT2tBu_JN7EZk7BQoMTHyfWRYPY/view?usp=sharing

The submission will retry every 10 mins. The value is currently hardcoded(will be user configurable later on) unless you have root. 

1. To change the value go to `/data/data/xyz.hisname.fireflyiii/shared_prefs/xyz.hisname.fireflyiii.preferences.xml` 

2. add `<string name="workManagerDelay">YOUR_VALUE_IN_MINS</string>`

**Comment by bmml1** [comment]
Hi it works somewhat now, but I think there is some initialization missing. There are duplicates being submitted.
![transactions-2020-07-27-085512](https://user-images.githubusercontent.com/32018487/88512678-39108380-cfe7-11ea-8ce7-96e34be16e64.png)

**This is just an idea:**
When the user creates an offline transaction it could be displayed in the, for example, withdrawal view with a status "pending/waiting for connection" or so. 
Also if the user then swipes to refresh force the submission and do not wait for the given submission interval.

**Comment by emansih** [comment]
hmmm...... It submits once for me. I will take your suggestions into account

**Comment by bmml1** [comment]
Anything I can provide for analyses?

**Comment by emansih** [comment]
there is nothing you can do. I'm busy with uni. I will work on this during my free time.
