### ISSUE TITLE
App Crash on Startup with older Server version

### ISSUE THREAD

**Issue by blacktemplar** [emansih/FireflyMobile#107]
**Firefly III Server Version:** 5.2.8

**Firefly III Mobile Version:** 2.1.2

**Android Version:**  8.1.0

**Device Information:**  Google Nexus 5X running LineageOS 15.1
--------------------------------------

The App sends an error report on startup

## Expected Behavior

The App starts up normally

## Current Behavior

The App sends an error report and quits.

## Steps to Reproduce

Start the app.

Logs:
[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/4993076/Fireflyiii-mobile.txt)

**Comment by emansih** [comment]
Did you click on anything?

**Comment by blacktemplar** [comment]
No, after reinstalling I can open the app authenticate via OAuth and then it crashes again without doing anything more. After that each start of the app results in a crash.

**Comment by emansih** [comment]
Just to confirm you are facing this issue after an upgrade or fresh install?

**Comment by blacktemplar** [comment]
First time occurred after an upgrade (not sure if it really was directly after an ugprade, but I regularly upgraded the App via FDroid). Now I wanted to check if a newer version helps and reinstalled it (deinstalled the App via FDroid and installed it via the apk for version 2.1.2, since FDroid currently only has version 2.1.0) and got the same error as before.

**Comment by emansih** [comment]
I suspect it's because you are using an old version of Firefly III. v5.2.8 does not contain a bug fix for the currency endpoint API

**Comment by blacktemplar** [comment]
Hmmm... Unfortunately my server does not support php 7.4 at the moment so v5.2.8 is the best I can get. To which version should I downgrade the app so that it works again?

**Comment by emansih** [comment]
2.0.6 of my app should work. I can't guarantee anything since I can't support old versions of firefly iii

**Comment by blacktemplar** [comment]
Thank you for your help, version 2.0.6 works for now.

**Comment by emansih** [comment]
@blacktemplar Hi. I added a hack to support older version of Firefly III. Try this https://drive.google.com/file/d/1wQhtcOPalPBq7-fAPDYT3ZjX2du1A0Mz/view?usp=sharing
