### ISSUE TITLE
Crash after upgrade 

### ISSUE THREAD

**Issue by pbartyik** [emansih/FireflyMobile#108]
[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/5001270/Fireflyiii-mobile.txt)
Crashing after upgrade from 2.0.8

**Comment by emansih** [comment]
What's your firefly iii version? I assume you are not using a updated version

**Comment by emansih** [comment]
Similar to #107.

**Comment by pbartyik** [comment]
Firefly iii is fully upgraded too

**Comment by pbartyik** [comment]
that being 5.3.3

**Comment by emansih** [comment]
Can you try clearing app data?

**Comment by pbartyik** [comment]
clearing app data helps, but then I had to re-create the access token.

**Comment by emansih** [comment]
Ah I know what the problem is.

**Comment by pbartyik** [comment]
neat, can this be fixed? :)

**Comment by emansih** [comment]
sure. will do it soon
