### ISSUE TITLE
App chrashes when trying to pick Currency

### ISSUE THREAD

**Issue by TobiasDev** [emansih/FireflyMobile#11]
**Firefly III Server Version:**
4.7.8

**Firefly III Mobile Version:**
0.13

**Android Version:**  
15

**Device Information:**  

- BRAND: OnePlus
- MODEL:  OnePlus 3
--------------------------------------

## Expected Behavior
Not chrashing but letting me choose currency

## Current Behavior
Chrashing

## Steps to Reproduce
1. Add a new withdrawal
2. Click on currency
3. Chrash

 Where are these saved? I couldn't find them on my phone.

I want to mention that my main currency is EUR if that changes anything.

**Comment by emansih** [comment]
Is there a logcat?

**Comment by TobiasDev** [comment]
Where are the logcats saved? I tried looking for one but didn't find it.

**Comment by emansih** [comment]
```
adb logcat --pid=`adb shell pidof -s xyz.hisname.fireflyiii`
```
It's ok though,I managed to replicate the bug. 

P.S I doubt you have API level 15 on your OnePlus 3. API level 15 = ICS. This software supports KitKat onwards.

**Comment by TobiasDev** [comment]
Sorry! You are right... I was thinking of Lineage numbering... sorry. I have 7.1.2

**Comment by emansih** [comment]
Fix in the latest release
