### ISSUE TITLE
Crash on open

### ISSUE THREAD

**Issue by optimistic5** [emansih/FireflyMobile#112]
**Firefly III Server Version:**
5.2.5

**Firefly III Mobile Version:**
3.0.0

**Android Version:**  
10

**Device Information:**  

- BRAND: Samsung
- MODEL: A41
--------------------------------------
Issue continue after updating to 3.0.0
I open app, it opens my email client with firefly report attachment. 
The same with connection or without. 
## Expected Behavior
App workrs. 

## Current Behavior
App wanted to send email and cant be open. 

## Steps to Reproduce
Run app

[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/5112276/Fireflyiii-mobile.txt)

![Screenshot_20200822-141025_Tutanota](https://user-images.githubusercontent.com/25054050/90954894-5f5bfe80-e481-11ea-9bba-387e9dc8a728.jpg)

**Comment by emansih** [comment]
@optimistic5 Hey, I added a hack to support older version of Firefly III. Try this https://drive.google.com/file/d/1wQhtcOPalPBq7-fAPDYT3ZjX2du1A0Mz/view?usp=sharing
