### ISSUE TITLE
Crash after login with PAT

### ISSUE THREAD

**Issue by ivanboytsov** [emansih/FireflyMobile#113]
**Firefly III Server Version:**
5.3.3
**Firefly III Mobile Version:**
3.0.0
**Android Version:**  
9
**Device Information:**  

- BRAND: samsung
- MODEL: galaxy j7
--------------------------------------

## Expected Behavior
Logged in and open app
## Current Behavior
Crash and email client is opening with log file
## Steps to Reproduce
1. Launch app
2. Select PAT option
3. App crashes

> 
[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/5125790/Fireflyiii-mobile.txt)

>

**Comment by emansih** [comment]
Hi, thanks for your report. I will take a look this weekend.

**Comment by emansih** [comment]
@ivanboytsov Hi, I am unable to replicate your bug. Are you able to sign in using OAUTH?

**Comment by ivanboytsov** [comment]
No. It doesn't work either.14:02, August 27, 2020, Daniel Quah <notifications@github.com>:
@ivanboytsov Hi, I am unable to replicate your bug. Are you able to sign in using OAUTH?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Sincerely yours,Ivan Boytsov

**Comment by ivanboytsov** [comment]
![Screenshot_20200827-141830_Firefly III Mobile](https://user-images.githubusercontent.com/70232503/91436313-885d0480-e870-11ea-97d1-bea95483da41.jpg)
![Screenshot_20200827-141819_Chrome](https://user-images.githubusercontent.com/70232503/91436323-8eeb7c00-e870-11ea-970f-70444f3169b1.jpg)
![Screenshot_20200827-141812_Firefly III Mobile](https://user-images.githubusercontent.com/70232503/91436331-93179980-e870-11ea-9030-8ef9e327a2a1.jpg)

**Comment by emansih** [comment]
You are using http that is why there is an error. I am not sure why it crashes instead of showing the error message though.

**Comment by ivanboytsov** [comment]
Is it possible to use your app without https?

**Comment by emansih** [comment]
No, it is not possible to use without https by design. However, you can rebuild the app.  


1. Insert the following code in [Android Manifest](https://github.com/emansih/FireflyMobile/blob/master/app/src/main/AndroidManifest.xml)

```
android:usesCleartextTraffic="true"
```

2. Remove ` android:networkSecurityConfig="@xml/network_security_config"`

You should be good to go.  Check this [stackoverflow link](https://stackoverflow.com/questions/53984725/networksecurityconfig-no-network-security-config-specified-using-platform-defa/53984915) for more info.

**Comment by ivanboytsov** [comment]
I'll try. Thank you!

**Comment by emansih** [comment]
Feel free to ask me if you need help
