### ISSUE TITLE
Crash on sending intent

### ISSUE THREAD

**Issue by ivanboytsov** [emansih/FireflyMobile#114]
**Firefly III Server Version:**
5.3.3
**Firefly III Mobile Version:**
3.0.0
**Android Version:**  
9
**Device Information:**  

- BRAND:samsung
- MODEL: galaxy j7
--------------------------------------

## Expected Behavior
I send intent via Tasker to create withdrawal transaction as described on [wiki page](https://github.com/emansih/FireflyMobile/wiki/Automation-via-Android-Intents).

## Current Behavior
On the event Firefly opens email client with crash log. Transaction isn't added.
## Steps to Reproduce

1. Configure Tasker for sending intent to the app.
2. Launch Task on any trigger.
3. App crashes, transaction not added.

[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/5140757/Fireflyiii-mobile.txt)

![Screenshot_20200828-102840_IntentTask](https://user-images.githubusercontent.com/70232503/91535578-09bda100-e91c-11ea-8741-b8e8d425b6ce.jpg)
![Screenshot_20200828-102856_IntentTask](https://user-images.githubusercontent.com/70232503/91535585-0b876480-e91c-11ea-9e1f-5ad6c017b993.jpg)
![Screenshot_20200828-102904_IntentTask](https://user-images.githubusercontent.com/70232503/91535594-0e825500-e91c-11ea-89bd-40e4c9b40771.jpg)

**Comment by emansih** [comment]
Hi, I have removed support for broadcast intents. Try using the Tasker plugins for transactions

**Comment by ivanboytsov** [comment]
Works. Thanks. But turns out it's impossible to set different currency but default)

**Comment by ivanboytsov** [comment]
Also i can't find how to use variables. Not realized yet?

**Comment by ivanboytsov** [comment]
@emansih I just downgraded on version 2.1.2 and intents work great with tasker variables. Why did you deprecated this functionality?

**Comment by emansih** [comment]
The reason I removed support is that it feels unintuitive and having a tasker plugin gives users an UI. I could add support for broadcast receivers back. Would you use it?

**Comment by ivanboytsov** [comment]
I like the way it works now, so yes, I would.
It's not less intuitive, than Tasker itself. Honestly, I haven't seen worse interface ever XD.
But comprehensive manual of using this feature will solve everything.
Now I am trying to set automated sms parsing and adding transaction. If I succeed, I will recommend firefly and your app to community of users of another financial app (Zenmoney) as a good alternative.
It's ~9000 members.

**Comment by ivanboytsov** [comment]
@emansih return wiki on using intents, please.

**Comment by emansih** [comment]
@ivanboytsov , Hi. Try the latest APK in the release page. It has support for Tasker variables.

**Comment by ivanboytsov** [comment]
Don't you have plans to support both intents and plugin? In my opinion intents are more universal than one-vendor specific plugin.

**Comment by emansih** [comment]
To be honest, I am not so sure about it myself. The plugin is an _universe_ protocol, it should work on [Automate](https://llamalab.com/automate/) and [macrodroid](https://play.google.com/store/apps/details?id=com.arlosoft.macrodroid). What is your usecase?

**Comment by ivanboytsov** [comment]
After update I've lost ability to login :(((
![Screenshot_20200830-151949_Firefly III Mobile](https://user-images.githubusercontent.com/70232503/91658825-4e8c3800-ead4-11ea-867e-2eda8a6c4495.jpg)

**Comment by ivanboytsov** [comment]
When using PAT there is such log 
[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/5146765/Fireflyiii-mobile.txt)

**Comment by emansih** [comment]
Are you using self signed cert?

**Comment by ivanboytsov** [comment]
Regarding usecase, I just figured out how to trigger transaction adding on receiving bank sms and very happy about that)

**Comment by ivanboytsov** [comment]
> Are you using self signed cert?

Yes, but I've imported it into android storage. Yesterday I was able to log in.

**Comment by ivanboytsov** [comment]
Certificate is in crt format, so I can't choose it via app. It is able to use only pem certs.

**Comment by emansih** [comment]
Really? The app supports both pem and crt

**Comment by emansih** [comment]
I don't test much for self signing since I don't self sign.

**Comment by ivanboytsov** [comment]
![Screenshot_20200830-153129_Files](https://user-images.githubusercontent.com/70232503/91659069-f5250880-ead5-11ea-8a7b-2e4e70d17712.jpg)
looks like pem-only)

**Comment by emansih** [comment]
strange, crt does not work anymore. 

 Convert your `crt` file to `pem` format
`openssl x509 -in /etc/ssl/certs/selfsigned.crt -out $HOME/selfsigned.pem -outform PEM`

**Comment by ivanboytsov** [comment]
Tested on demo site.
Can you make Destination Account not obligated in withdrawal?
It is not always possible to set it precisely.
![Screenshot_20200830-162838_Tasker](https://user-images.githubusercontent.com/70232503/91660286-1b4ea680-eade-11ea-9075-4af1fe8c414c.jpg)

**Comment by ivanboytsov** [comment]
@emansih in which format I can send date with time? I am trying 2020-8-30 11:13

**Comment by emansih** [comment]
Ok, I will look into the withdrawal submission. 

Date and time should be in YYYY-MM-DD and HH:MM

**Comment by ivanboytsov** [comment]
Thanks! Yeah, plugin works on transactions as well, but there is a bug: when editing action it clears every field without ability to return their previoud values.

**Comment by emansih** [comment]
@ivanboytsov I have brought back support for broadcast receivers. Will be available in the next release.

**Comment by ivanboytsov** [comment]
Thank you very much! Great work!

**Comment by ivanboytsov** [comment]
@emansih since you brought back intents support, do you consider publishing it's definition on official intents page of autoshare? https://joaoapps.com/autoshare/intents/
