### ISSUE TITLE
Crash de l'application lors de la connexion

### ISSUE THREAD

**Issue by domosolution67** [emansih/FireflyMobile#115]
**Firefly III Server Version: 5.2.0

**Firefly III Mobile Version: 2.1.2

**Android Version: 9

**Device Information: 

- BRAND: Samsung
- MODEL: galaxy S5 LineageOS 16.0
--------------------------------------
Bonjour,

J'arrive bien à me connecter au server firefly via l'application mais après le Welcome, l'application crash. Impossible d'avoir une visualisation. Test fait en passant par OAuth Clients ou Personal Access Tokens. Même comportement avec les deux système d'authentification.

Brice.

**Comment by emansih** [comment]
Bonjour, I don't speak French. You are running a old version of Firefly and the mobile app. Please update them. Merci

**Comment by domosolution67** [comment]
Sorry I can speak English.
The update is running on the firefly server. For the APK where is the last update ? 
Thank's

**Comment by emansih** [comment]
Where did you get the APK from? I have builds in the [release](https://github.com/emansih/FireflyMobile/releases) page and my personal self hosted [FDroid](https://foss.hisname.xyz/fdroid/firefly). APK can also be downloaded directly from official [FDroid](https://f-droid.org/packages/xyz.hisname.fireflyiii/)

**Comment by domosolution67** [comment]
I have download the APK on the F-droid (not on your repository but on the F-droid repository)

**Comment by emansih** [comment]
Ok. You are running an old version of Firefly III without the bug fix for default currency firefly-iii/firefly-iii#3493

**Comment by domosolution67** [comment]
Ok I have update with the last released APK.
For the firefly server, I'm on YunoHost. He does not offer me an update..

**Comment by domosolution67** [comment]
[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/5142528/Fireflyiii-mobile.txt)

**Comment by emansih** [comment]
Yeah, I know what's the reason for the crash. Like I said, it's due to old version of Firefly III. There is nothing I can do about it.

**Comment by emansih** [comment]
If you can't update Firefly III, use version 2.0.6 of my app.

**Comment by emansih** [comment]
@domosolution67 I added a hack to support older version of Firefly III. Try this https://drive.google.com/file/d/1wQhtcOPalPBq7-fAPDYT3ZjX2du1A0Mz/view?usp=sharing

**Comment by domosolution67** [comment]
It works now with the APK. Thank's for our help and thank's for our job !!
