### ISSUE TITLE
When making a new withdrawal I only see my income accounts in the dropdown menu

### ISSUE THREAD

**Issue by TobiasDev** [emansih/FireflyMobile#12]
**Firefly III Server Version:**
4.7.8

**Firefly III Mobile Version:**
0.14

**Android Version:**  
7.1.5

**Device Information:**  

- BRAND: OnePlus
- MODEL: 3
--------------------------------------

Not sure if this a bug or just me not understanding the app.

When I make a new withdrawal I can write destination account, is that where I should write the store I was in or the account I payed from (Eg. Bank, cash, kredit, etc.)

Also when making a new withdrawal in the dropdown menu I only see my income accounts, not any expense accounts.

https://cloud.postnow.eu/index.php/s/Haai5nLN5C8jPPb

The one in that menu is my employer. So that is for me an income account.

**Comment by emansih** [comment]
From the image: 
You are circling the source account. Source accounts [must be an existing asset account for transfers and withdrawals](https://firefly-iii.readthedocs.io/en/latest/api/transactions.html#id2).  Destination accounts [may both be blank for a cash withdrawal, or create a new expense account for withdrawals](https://firefly-iii.readthedocs.io/en/latest/api/transactions.html#id2).  

[Previous discussion can be found here](https://github.com/emansih/FireflyMobile/issues/7)

**Comment by TobiasDev** [comment]
I'm sorry I tried reading the thread but I'm still not sure about where I choice which account I payed with. Eg. Cash or VISA or my Bank account. 

I guess it is different in the app, since it shows me my revenue accounts in the dropdown. Maybe I'm understanding Firefly wrong but I guess from the thread that the source accounts in the app is the revenue accounts. So where do I set asset account? And where do I set Expense account?

I'm probably just missunderstanding some, but would love if you could me some more help. :( Sorry.

**Comment by TobiasDev** [comment]
Here is a picture of the revenue accounts, and that is the ones I see in the dropdown in the app. :)

https://cloud.postnow.eu/index.php/s/LC8iaTpbNL4jtGT

**Comment by TobiasDev** [comment]
Awesome! Looking forward to trying it out now. :)
