### ISSUE TITLE
Offline transaction submission fails

### ISSUE THREAD

**Issue by bmml1** [emansih/FireflyMobile#122]
**Firefly III Server Version:**
 5.3.3
**Firefly III Mobile Version:**
3.0.3 apk from Github
**Android Version:**  
10
**Device Information:**  

- BRAND: Pixel
- MODEL: 3a
--------------------------------------
## Expected Behavior
Create an offline transaction
## Current Behavior
When offline transaction is submitted a notification is displayed "need to get a valid source account ID and /or valid source account name" even though this field is filled. 

## Steps to Reproduce
Create off transaction with source account field filled and wait for submission.

**Comment by emansih** [comment]
ah... I should be doing unit test for this.

**Comment by bmml1** [comment]
fixed
