### ISSUE TITLE
Offline transaction with attachment

### ISSUE THREAD

**Issue by bmml1** [emansih/FireflyMobile#124]
**Firefly III Server Version:**
 5.3.3
**Firefly III Mobile Version:**
3.0.3 apk from Github
**Android Version:**  
10
**Device Information:**  

- BRAND: Pixel
- MODEL: 3a
--------------------------------------
## Expected Behavior
Create an offline transaction with attachment.
## Current Behavior
Attachment is gone after the transaction was saved locally.

## Steps to Reproduce
Create off transaction with an attachment.

**Comment by emansih** [comment]
yeah... I deliberately disable it because the app have no guarantee that the file will exist when uploading at a later time. I _could_ copy the file to the app private directory. I am still thinking of the design.

**Comment by darnir** [comment]
I would absolutely love this feature!

**Comment by emansih** [comment]
@darnir the feature has existed for quite some time. try it.
