### ISSUE TITLE
App stops working after 2 or 3 weeks

### ISSUE THREAD

**Issue by uSyzex** [emansih/FireflyMobile#129]
Hi,

So it's not the first time that the app stops working, and I just have to reinstall it to make it work again. Here is the log, hope it can help to find some bugs !

[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/5434421/Fireflyiii-mobile.txt)

**Comment by emansih** [comment]
Did it crash immediately on open?

**Comment by emansih** [comment]
From what I can tell from the logs, are you adding an invalid currency?

**Comment by uSyzex** [comment]
> 
> 
> Did it crash immediately on open?

It crashes when I add a new transaction, but it seems that the app doesn't refresh with the server, like it is not synchronised with it. 

> 
> 
> From what I can tell from the logs, are you adding an invalid currency?
I didn't change that, I'm gonna check

**Comment by emansih** [comment]
I _know_ the reason why it crashes but I have no idea why it only crashes after 2 - 3 weeks.

**Comment by uSyzex** [comment]
I find it  really  weird too. First I was thinking about different version.
But this time it's not the case, I'm still up to update with the app and
the server is running fine.

If I can provide anything to help you with, please le me know

**Comment by uSyzex** [comment]
Hi, here is another log file from when I tried to refresh token.
[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/5447063/Fireflyiii-mobile.txt)

**Comment by uSyzex** [comment]
Fixed the problem by logging out, and login in again. 

Hope it help you to improve the app ! 

Thank you

**Comment by emansih** [comment]
It could be due to invalid token but the JWT expires after a year. I will have to add some checks for token validity later on.
