### ISSUE TITLE
Trandactions are not shown

### ISSUE THREAD

**Issue by ivanboytsov** [emansih/FireflyMobile#131]
**Firefly III Server Version:**
5.3.3
**Firefly III Mobile Version:**
3.0.9
**Android Version:**  
9
**Device Information:**  

- BRAND:samsung
- MODEL: j7
--------------------------------------

## Expected Behavior
In transaction section of the app I see my transactions
## Current Behavior
There are no transactions at all. Despite there is a withdrawal for October 31 for example. 
## Steps to Reproduce

![Screenshot_20201031-111803_Firefly III Mobile](https://user-images.githubusercontent.com/70232503/97774724-48b1e200-1b6b-11eb-869d-ed1feabc5ae1.jpg)
![Screenshot_20201031-111756_Chrome](https://user-images.githubusercontent.com/70232503/97774729-4f405980-1b6b-11eb-9394-a4588c307676.jpg)

**Comment by ivanboytsov** [comment]
Still no transactions in the app
![Screenshot_20201116-143832_Firefly III Mobile](https://user-images.githubusercontent.com/70232503/99248577-bde30f80-2819-11eb-9885-ed45d99966a9.jpg)
![Screenshot_20201116-143801_Chrome](https://user-images.githubusercontent.com/70232503/99248590-c3405a00-2819-11eb-9f79-486a7cd76fc5.jpg)

**Comment by emansih** [comment]
The issue is I can't replicate your bug

**Comment by ivanboytsov** [comment]
> The issue is I can't replicate your bug

There is nothing special in my case but a lot of splitted transactions. I'll try to prepare testing instance for you.

**Comment by emansih** [comment]
Could you try this APK? https://drive.google.com/file/d/1iI5Swv_G9qRkT1UVqIjQLRP90AVcfS8d/view?usp=sharing

**Comment by ivanboytsov** [comment]
> Could you try this APK? https://drive.google.com/file/d/1iI5Swv_G9qRkT1UVqIjQLRP90AVcfS8d/view?usp=sharing

No difference. Transactions sections ale completely empty.

**Comment by emansih** [comment]
All good?

**Comment by ivanboytsov** [comment]
> All good?

Fixed now.
But do you consider adding groups of transactions like it is done in web interface? Usually I split big transactions per item. For example, supermarket transaction may has up to 50 splits. And it will be convenient to see that all splitted transactions actually relate to one transaction.
![Screenshot_20201121-172656_Firefly III Mobile](https://user-images.githubusercontent.com/70232503/99879578-f2dad200-2c1e-11eb-85e1-56d110a9a96b.jpg)
![Screenshot_20201121-173437_Chrome](https://user-images.githubusercontent.com/70232503/99879756-dbe8af80-2c1f-11eb-913e-71c8d83774e0.jpg)
