### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [emansih/FireflyMobile#134]
https://f-droid.org/wiki/index.php?title=xyz.hisname.fireflyiii/lastbuild_74&oldid=282752

Looking at history, might not be a network glitch: https://f-droid.org/wiki/index.php?title=xyz.hisname.fireflyiii/lastbuild_73&action=history

ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7732

**Comment by emansih** [comment]
I have no issue building on my local machine and I'm also not sure why the build is trying to look for msg-simple-1.1.jar. I will have to look into it

**Comment by emansih** [comment]
ah. I know what is the issue. Thanks for the heads up
