### ISSUE TITLE
App crashes while trying to refresh the oauth token

### ISSUE THREAD

**Issue by leander091** [emansih/FireflyMobile#135]
**Firefly III Server Version:**
5.4.6
**Firefly III Mobile Version:**
3.0.4
**Android Version:**  
10
**Device Information:**  

- BRAND: ONEPLUS 
- MODEL: ONEPLUS A6003 (OnePlus6)
--------------------------------------

## Expected Behavior
The token will be created and used in the app without any errors.
## Current Behavior
The app crashes when it tries to refresh the token. Within ff3 you will see an new authorized application.

## Steps to Reproduce
Push the button in the settings to refresh the token. 

I've attached the stacktrace
[Fireflyiii-mobile-stacktrace-11-15-2020.txt](https://github.com/emansih/FireflyMobile/files/5542592/Fireflyiii-mobile-stacktrace-11-15-2020.txt)

**Comment by emansih** [comment]
You are using an old version. Get a newer version on the release page.

**Comment by leander091** [comment]
Sure, thanks for the response. I am going to test the new version when it is published on fdroid.

**Comment by emansih** [comment]
There are some issues with the official F-Droid builds and it might take some time to be published. In the mean time, you can either get the APK via the release page OR via my self hosted F-Droid

**Comment by leander091** [comment]
@emansih, thank your for the guidelines. I've tested the latest version and the token refreshes fine :)
