### ISSUE TITLE
Authentication crash

### ISSUE THREAD

**Issue by axlerose** [emansih/FireflyMobile#136]
**Firefly III Server Version:**
5.4.6

**Firefly III Mobile Version:**
3.08

**Android Version:**  
10 Miui 12.0.3

**Device Information:**  
- BRAND: Xiaomi
- MODEL: Mi9 T Pro
--------------------------------------

## Expected Behavior

Connection to my local instance of Firefly by OAuth

## Current Behavior
the app crash after login 

## Steps to Reproduce
Open the app select OAuth insert the parameter, redirect to the login page, after login the app crash

[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/5542816/Fireflyiii-mobile.txt)

**Comment by emansih** [comment]
Hi, this issue should be fixed in the latest release. (v4.0.1)
