### ISSUE TITLE
Sign in using PAT Base URL Required

### ISSUE THREAD

**Issue by bartmaniac** [emansih/FireflyMobile#137]
**Firefly III Server Version: 5.4.6**

**Firefly III Mobile Version:3.0.9**

**Android Version:** 10 

**Device Information:**  

- BRAND: Samsung
- MODEL:  Galaxy S10
--------------------------------------

## Current Behavior: Unable to fill in the url because there is no field for the url. 
![Screenshot_20201119-235903_Firefly III Mobile](https://user-images.githubusercontent.com/44246750/99735346-c0b55d00-2ac4-11eb-968d-7d8ad9e26e5a.jpg)

**Comment by emansih** [comment]
Hi, I assume the bug is fixed for you? I will be closing this issue, if you are still facing this bug feel free to reopen. Thanks!
