### ISSUE TITLE
Division by zero in BudgetSummaryViewModel

### ISSUE THREAD

**Issue by bendardenne** [emansih/FireflyMobile#138]
REPORT_ID=3432bfce-ee1b-439d-818a-975190ed4971
APP_VERSION_NAME=3.0.11
PHONE_MODEL=Moto G (5S) Plus
BRAND=motorola
PRODUCT=sanders_n
ANDROID_VERSION=8.1.0
BUILD_CONFIG=
STACK_TRACE=java.lang.ArithmeticException: Division by zero
	at java.math.BigDecimal.divide(BigDecimal.java:1030)
	at xyz.hisname.fireflyiii.ui.budget.BudgetSummaryViewModel.getTransaction(BudgetSummaryViewModel.kt:38)
	at xyz.hisname.fireflyiii.ui.budget.BudgetSummaryViewModel$getTransaction$1.invokeSuspend(Unknown Source:11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

LOGCAT=--------- beginning of system
11-21 20:51:37.700 E/SchedPolicy(24320): open of /dev/cpuctl/bg_non_interactive/tasks failed: No such file or directory
--------- beginning of main
11-21 23:58:58.069 W/RecyclerView(24320): No adapter attached; skipping layout
11-21 23:58:58.069 I/zygote  (24320): Deoptimizing int com.mikepenz.fastadapter.FastAdapter.getItemViewType(int) due to JIT inline cache
11-21 23:58:59.272 I/zygote  (24320): Background concurrent copying GC freed 37076(1864KB) AllocSpace objects, 2(104KB) LOS objects, 49% free, 14MB/28MB, paused 167us total 152.679ms
11-21 23:59:27.746 I/zygote  (24320): Deoptimizing boolean com.google.android.material.floatingactionbutton.FloatingActionButton$BaseBehavior.onLayoutChild(androidx.coordinatorlayout.widget.CoordinatorLayout, com.google.android.material.floatingactionbutton.FloatingActionButton, int) due to JIT inline cache
11-21 23:59:27.749 I/zygote  (24320): Deoptimizing boolean com.google.android.material.floatingactionbutton.FloatingActionButton$BaseBehavior.onDependentViewChanged(androidx.coordinatorlayout.widget.CoordinatorLayout, android.view.View, android.view.View) due to JIT inline cache
11-21 23:59:41.365 I/zygote  (24320): Deoptimizing boolean androidx.drawerlayout.widget.DrawerLayout.onTouchEvent(android.view.MotionEvent) due to JIT inline cache
11-21 23:59:43.165 I/zygote  (24320): Deoptimizing boolean androidx.coordinatorlayout.widget.CoordinatorLayout.onStartNestedScroll(android.view.View, android.view.View, int, int) due to JIT inline cache
11-22 00:01:18.719 I/zygote  (24320): Deoptimizing void androidx.recyclerview.widget.RecyclerView$5.removeViewAt(int) due to JIT inline cache
11-22 00:01:19.907 I/zygote  (24320): Deoptimizing void com.mikepenz.fastadapter.listeners.OnBindViewHolderListenerImpl.unBindViewHolder(androidx.recyclerview.widget.RecyclerView$ViewHolder, int) due to JIT inline cache
11-22 00:01:21.686 W/RecyclerView(24320): No adapter attached; skipping layout
11-22 00:01:26.150 W/RecyclerView(24320): No adapter attached; skipping layout
11-22 00:01:26.433 W/RecyclerView(24320): No adapter attached; skipping layout
11-22 00:01:26.861 I/zygote  (24320): Deoptimizing void com.github.mikephil.charting.data.DataSet.calcMinMaxX(com.github.mikephil.charting.data.Entry) due to JIT inline cache
11-22 00:01:26.862 I/zygote  (24320): Deoptimizing void com.github.mikephil.charting.renderer.LegendRenderer.computeLegend(com.github.mikephil.charting.data.ChartData) due to JIT inline cache
11-22 00:01:32.996 I/FloatingActionButton(24320): Setting a custom background is not supported.
11-22 00:01:33.155 V/View    (24320): dispatchProvideAutofillStructure(): not laid out, ignoring 1 children of 1073741865
11-22 00:01:33.155 V/View    (24320): dispatchProvideAutofillStructure(): not laid out, ignoring 1 children of 1073741877
11-22 00:01:33.155 V/View    (24320): dispatchProvideAutofillStructure(): not laid out, ignoring 0 children of 1073741826
11-22 00:01:33.155 V/View    (24320): dispatchProvideAutofillStructure(): not laid out, ignoring 1 children of 1073741878
11-22 00:01:33.159 V/View    (24320): dispatchProvideAutofillStructure(): not laid out, ignoring 1 children of 1073741880
11-22 00:01:33.159 V/View    (24320): dispatchProvideAutofillStructure(): not laid out, ignoring 1 children of 1073741881
11-22 00:01:33.159 V/View    (24320): dispatchProvideAutofillStructure(): not laid out, ignoring 0 children of 1073741830
11-22 00:01:33.162 V/View    (24320): dispatchProvideAutofillStructure(): not laid out, ignoring 1 children of 1073741900
11-22 00:01:33.162 V/View    (24320): dispatchProvideAutofillStructure(): not laid out, ignoring 1 children of 1073741901
11-22 00:01:33.162 V/View    (24320): dispatchProvideAutofillStructure(): not laid out, ignoring 0 children of 1073741837
11-22 00:01:33.162 V/View    (24320): dispatchProvideAutofillStructure(): not laid out, ignoring 1 children of 1073741902
11-22 00:01:33.195 I/AssistStructure(24320): Flattened final assist data: 19708 bytes, containing 2 windows, 86 views
11-22 00:01:33.311 D/OpenGLRenderer(24320): endAllActiveAnimators on 0x8db89200 (MenuPopupWindow$MenuDropDownListView) with handle 0x92b764b0
11-22 00:01:37.776 I/FloatingActionButton(24320): Setting a custom background is not supported.
11-22 00:01:37.872 I/zygote  (24320): Background concurrent copying GC freed 85167(3MB) AllocSpace objects, 5(112KB) LOS objects, 49% free, 17MB/35MB, paused 149us total 189.637ms
11-22 00:01:37.877 E/SpellCheckerSession(24320): ignoring processOrEnqueueTask due to unexpected mState=TASK_CLOSE scp.mWhat=TASK_CLOSE
11-22 00:01:37.878 I/chatty  (24320): uid=10182(xyz.hisname.fireflyiii) FinalizerDaemon identical 2 lines
11-22 00:01:37.878 E/SpellCheckerSession(24320): ignoring processOrEnqueueTask due to unexpected mState=TASK_CLOSE scp.mWhat=TASK_CLOSE
11-22 00:01:38.094 D/OpenGLRenderer(24320): endAllActiveAnimators on 0x8ee87600 (MenuPopupWindow$MenuDropDownListView) with handle 0x929f8f30
11-22 00:01:38.556 I/zygote  (24320): Deoptimizing java.lang.String xyz.hisname.fireflyiii.data.remote.firefly.api.AccountsService$DefaultImpls.getString(android.widget.EditText) due to JIT inline cache
11-22 00:01:38.561 I/zygote  (24320): Deoptimizing okhttp3.Request retrofit2.RequestFactory.create(java.lang.Object[]) due to JIT inline cache
11-22 00:01:47.748 E/MPAndroidChart(24320): Can't select by touch. No data set.
11-22 00:01:55.301 W/RecyclerView(24320): No adapter attached; skipping layout
11-22 00:02:00.276 I/zygote  (24320): Deoptimizing void androidx.fragment.app.FragmentStateManager.createView() due to JIT inline cache
11-22 00:02:00.289 W/ListPreference(24320): Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
11-22 00:02:02.784 I/zygote  (24320): Deoptimizing boolean j$.time.format.v.f(j$.time.format.D, java.lang.StringBuilder) due to JIT inline cache
11-22 00:02:03.225 I/zygote  (24320): Deoptimizing void androidx.recyclerview.widget.RecyclerView$Recycler.addViewHolderToRecycledViewPool(androidx.recyclerview.widget.RecyclerView$ViewHolder, boolean) due to JIT inline cache
11-22 00:02:07.450 W/ListPreference(24320): Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
11-22 00:02:16.434 W/ListPreference(24320): Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
11-22 00:02:21.792 W/ListPreference(24320): Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
11-22 00:02:30.716 I/zygote  (24320): Do full code cache collection, code=2MB, data=1679KB
11-22 00:02:30.722 I/zygote  (24320): After code cache collection, code=2MB, data=1506KB
11-22 00:02:50.351 W/RecyclerView(24320): No adapter attached; skipping layout
11-22 00:03:06.895 E/SpellCheckerSession(24320): ignoring processOrEnqueueTask due to unexpected mState=TASK_CLOSE scp.mWhat=TASK_CLOSE
11-22 00:03:06.895 I/chatty  (24320): uid=10182(xyz.hisname.fireflyiii) FinalizerDaemon identical 2 lines
11-22 00:03:06.896 E/SpellCheckerSession(24320): ignoring processOrEnqueueTask due to unexpected mState=TASK_CLOSE scp.mWhat=TASK_CLOSE
--------- beginning of crash
11-22 00:04:27.129 E/AndroidRuntime(24320): FATAL EXCEPTION: DefaultDispatcher-worker-2
11-22 00:04:27.129 E/AndroidRuntime(24320): Process: xyz.hisname.fireflyiii, PID: 24320
11-22 00:04:27.129 E/AndroidRuntime(24320): java.lang.ArithmeticException: Division by zero
11-22 00:04:27.129 E/AndroidRuntime(24320): 	at java.math.BigDecimal.divide(BigDecimal.java:1030)
11-22 00:04:27.129 E/AndroidRuntime(24320): 	at xyz.hisname.fireflyiii.ui.budget.BudgetSummaryViewModel.getTransaction(BudgetSummaryViewModel.kt:38)
11-22 00:04:27.129 E/AndroidRuntime(24320): 	at xyz.hisname.fireflyiii.ui.budget.BudgetSummaryViewModel$getTransaction$1.invokeSuspend(Unknown Source:11)
11-22 00:04:27.129 E/AndroidRuntime(24320): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
11-22 00:04:27.129 E/AndroidRuntime(24320): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
11-22 00:04:27.129 E/AndroidRuntime(24320): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
11-22 00:04:27.129 E/AndroidRuntime(24320): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
11-22 00:04:27.129 E/ACRA    (24320): ACRA caught a ArithmeticException for xyz.hisname.fireflyiii
11-22 00:04:27.129 E/ACRA    (24320): java.lang.ArithmeticException: Division by zero
11-22 00:04:27.129 E/ACRA    (24320): 	at java.math.BigDecimal.divide(BigDecimal.java:1030)
11-22 00:04:27.129 E/ACRA    (24320): 	at xyz.hisname.fireflyiii.ui.budget.BudgetSummaryViewModel.getTransaction(BudgetSummaryViewModel.kt:38)
11-22 00:04:27.129 E/ACRA    (24320): 	at xyz.hisname.fireflyiii.ui.budget.BudgetSummaryViewModel$getTransaction$1.invokeSuspend(Unknown Source:11)
11-22 00:04:27.129 E/ACRA    (24320): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
11-22 00:04:27.129 E/ACRA    (24320): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
11-22 00:04:27.129 E/ACRA    (24320): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
11-22 00:04:27.129 E/ACRA    (24320): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

IS_SILENT=false
USER_CRASH_DATE=2020-11-22T00:04:27.134+01:00

**Comment by emansih** [comment]
Hi, I have fixed this bug in the latest release.
