### ISSUE TITLE
Crash on budgets list opening when editing transaction

### ISSUE THREAD

**Issue by ivanboytsov** [emansih/FireflyMobile#139]
**Firefly III Server Version:**
5.3.3
**Firefly III Mobile Version:**
4.0.0
**Android Version:**  
9
**Device Information:**  

- BRAND:samsung
- MODEL: j7
--------------------------------------

## Expected Behavior
When editing transaction I open list of budgets to choose one.
## Current Behavior
Instead of showing budgets list it crashes.
## Steps to Reproduce
1. Choose transaction.
2. Cluck on icon in budget field.
3. Crashed.

**Comment by ivanboytsov** [comment]
[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/5734177/Fireflyiii-mobile.txt)

**Comment by emansih** [comment]
yeah I have fixed it.
