### ISSUE TITLE
Withdrawal Tasker Plugin crash when saving configuration with Automate

### ISSUE THREAD

**Issue by gimiki** [emansih/FireflyMobile#141]
**Firefly III Server Version:**5.4.6

**Firefly III Mobile Version:**4.0.1

**Android Version:** 9

**Device Information:**  

- BRAND: LG
- MODEL: V30+ H930DS
--------------------------------------

## Expected Behavior
I want to configure withdrawal automation via Tasker plugin (Automate android app).
## Current Behavior
When I click save on the configuration page of the Firefly Withdrawal Tasker plugin in Automate, Firefly seems to crash and no settings is saved.
Automate log: 
`java.lang.IllegalStateException: Plug-in failed with result code: 2`
Issue report:
[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/5754338/Fireflyiii-mobile.txt)

## Steps to Reproduce
Firefly III installed and configured correctly
- Add a Plug-In Action block in any Automate flow
- Click on that block, pick Firefly III Mobile Withdrawal Plugin, and then click "Configure"
- Configure the plugin and then click Save -> app seems to crash and the issue report is displayed

I didn't have this problem with the previous Firefly version and Automate. I also tried Transfer Plugin and the behaviour seems the same.

**Comment by emansih** [comment]
My bad. It was due to the added support for attachments. Will be fixed in the next release.
