### ISSUE TITLE
Editing a transaction requires luck 😂

### ISSUE THREAD

**Issue by gthbusrr** [emansih/FireflyMobile#145]
**Firefly III Server Version:**
- 5.4.6 (Latest)

**Firefly III Mobile Version:**
- 4.0.2 (Latest)

**Android Version:**  
- 10

**Device Information:**  

- BRAND: Samsung
- MODEL: Galaxy Note20 Ultra
--------------------------------------

## Expected Behavior
- Able to update transactions.

## Current Behavior
- Sometimes, when I try to edit a transaction, it just jump right back to detail screen and display "Transaction Updated" or something like that when I tab "Edit" and nothing happens.
- Sometimes, when I try to edit a split transaction, it DELETES my entry...
- Sometimes, when I try to edit a transaction, it jumped right back to detail screen and display "Transaction Updated" or something like that when I tab "Edit" and it edits my entry BASE ON THE PREVIOUS ENTRY THAT I CREATED.
- Sometimes, I'll have to close and reopen the app before I am allowed to edit.
 
## Steps to Reproduce
- Create a transaction
- Edit a transaction

**Comment by emansih** [comment]
kinda hard to replicate such an issue.

**Comment by gthbusrr** [comment]
I'll try to do screen recordings of me editing transactions next time. But just my guess, it might be something to do with variables not resetting / initialising correctly after each submission / cancellation

**Comment by gthbusrr** [comment]
Hi, I've successfully recreated the bug.

**Step to Reproduce**
1. Edit "Transaction A"
2. Save (Transaction Updated shown and Transaction A successfully updated)
3. Tab Edit in details page of "Transaction B" (Jumped right back to details page of "Transaction B", showing "Transaction Updated" at the bottom and Transaction B updated with details of transaction A... I don't even have the chance to type in anything)

**Comment by emansih** [comment]
Will be fixed in the next release
