### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by DarkWingMcQuack** [emansih/FireflyMobile#15]
**Firefly III Server Version:**
4.8.7

**Firefly III Mobile Version:**
1.0.2

**Android Version:**  
LineageOs 14.1

**Device Information:**  
Nexus 5X

--------------------------------------
I tried logging in using OAuth, but when I need to click on the "authorize" button, nothing happens.
When I use a  Personal Access Token, I can get past the login screen in FireflyMobile, but cannot see any data. When I try to refresh something, I get an AuthenticationException.
I would realy love to use your App, but currently I am not able to log into my firefly account.
## Expected Behavior
OAuth should work.
When using a Personal Access Token it should only possible to get past the login screen, if the token is valid.
Aside from that I dont know why my Personal Access Token didnt work.

## Current Behavior
OAuth doent work at all with the default LineageOS nor the lightning browser and FireflyMobile 1.0.2.
Personal Access Token should work.
When using a wrong Personal Access Token FireflyMobile should tell and stay at the login screen.

## Steps to Reproduce
Trying OAuth with thy LineageOS or lightning browser.
Trying any Personal Access Token which does not exist.
Trying Personal Access Token which was produced by Firefly-iii does not work, too.

**Comment by DarkWingMcQuack** [comment]
I was able to complete OAuth using the Chrome browser

**Comment by DarkWingMcQuack** [comment]
Ok perfect.
The problem that the Personal Access Token does not get checked while logging in is still present i think.
Once logged in with a non valid PAT a lot of bugs occur and the app crashes a lot. So it would be the easiest fix to not make it possible getting past the login screen with a non valid PTA.

**Comment by emansih** [comment]
For OAuth using Firefox, this is what i did. 

1. Open app
2. Click OAuth
3. Type in your details
4. Click sign in
5. Open web browser
6. sign in to your Firefly III from your browser

This is the *most* important part

7. Click on `Refresh`
8. Click on the Android Icon next to your address bar
![screenshot](https://user-images.githubusercontent.com/5896415/50226682-cd177380-03de-11e9-80c3-0ce4d6079046.png)

**Comment by emansih** [comment]
Regarding having a valid PAT.... I will have to parse the JWT, currently I _rely_ on users passing a valid token

**Comment by emansih** [comment]
@DarkWingMcQuack Hey, I have fixed the issue where invalid PAT auth allows user to sign in
