### ISSUE TITLE
Crash when trying to access account in settings

### ISSUE THREAD

**Issue by corch1988** [emansih/FireflyMobile#151]
**Firefly III Server Version:**
5.4.6

**Firefly III Mobile Version:**
4.0.4

**Android Version:**  
11
Oxygen OS 11.0.3.3.IN11BA

**Device Information:**  

- BRAND: OnePlus
- MODEL: 8 Pro (IN2023)
--------------------------------------

## Expected Behavior
Accessing some account settings

## Current Behavior
App Crash

## Steps to Reproduce
Login with personal token. Try accessing "Settings -> Account"

`REPORT_ID=01ef2c9a-5050-408f-8008-711ce24dbe9c
APP_VERSION_NAME=4.0.4
PHONE_MODEL=IN2023
BRAND=OnePlus
PRODUCT=OnePlus8Pro_EEA
ANDROID_VERSION=11
BUILD_CONFIG=
STACK_TRACE=java.lang.NullPointerException: accountManager.getUserDa…ount, "token_expires_in") must not be null
	at xyz.hisname.fireflyiii.data.local.account.AuthenticatorManager.getTokenExpiry(AuthenticatorManager.kt:1)
	at xyz.hisname.fireflyiii.ui.settings.SettingsAccountFragment.onCreatePreferences(SettingsAccountFragment.kt:14)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:10)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:6)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:23)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:68)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:7959)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

LOGCAT=02-17 12:56:51.448 E/name.fireflyii(26471): Invalid ID 0x00000010.
02-17 12:56:51.448 E/name.fireflyii(26471): Invalid ID 0x00000010.
02-17 12:56:51.449 E/name.fireflyii(26471): Invalid ID 0x0000000f.
02-17 12:56:51.449 E/name.fireflyii(26471): Invalid ID 0x0000000f.
02-17 12:56:51.449 E/name.fireflyii(26471): Invalid ID 0x00000003.
02-17 12:56:51.449 E/name.fireflyii(26471): Invalid ID 0x00000003.
02-17 12:56:51.449 E/name.fireflyii(26471): Invalid ID 0x00000004.
02-17 12:56:51.449 E/name.fireflyii(26471): Invalid ID 0x00000004.
02-17 12:56:51.449 E/name.fireflyii(26471): Invalid ID 0x00000005.
02-17 12:56:51.449 E/name.fireflyii(26471): Invalid ID 0x00000005.
02-17 12:56:51.449 E/name.fireflyii(26471): Invalid ID 0x00000002.
02-17 12:56:51.449 E/name.fireflyii(26471): Invalid ID 0x00000002.
02-17 12:56:51.449 E/name.fireflyii(26471): Invalid ID 0x00000006.
02-17 12:56:51.449 E/name.fireflyii(26471): Invalid ID 0x00000006.
02-17 12:56:51.450 E/name.fireflyii(26471): Invalid ID 0x0000000e.
02-17 12:56:51.450 E/name.fireflyii(26471): Invalid ID 0x0000000e.
02-17 12:56:51.450 E/name.fireflyii(26471): Invalid ID 0x00000013.
02-17 12:56:51.450 E/name.fireflyii(26471): Invalid ID 0x00000013.
02-17 12:56:51.450 E/name.fireflyii(26471): Invalid ID 0x00000016.
02-17 12:56:51.450 E/name.fireflyii(26471): Invalid ID 0x00000016.
02-17 12:56:51.450 E/name.fireflyii(26471): Invalid ID 0x00000014.
02-17 12:56:51.450 E/name.fireflyii(26471): Invalid ID 0x00000014.
02-17 12:56:51.452 E/name.fireflyii(26471): Invalid ID 0x00000000.
02-17 12:56:51.453 I/chatty  (26471): uid=10433(xyz.hisname.fireflyiii) identical 16 lines
02-17 12:56:51.453 E/name.fireflyii(26471): Invalid ID 0x00000000.
02-17 12:56:51.453 E/name.fireflyii(26471): Invalid ID 0x00000001.
02-17 12:56:51.453 I/chatty  (26471): uid=10433(xyz.hisname.fireflyiii) identical 2 lines
02-17 12:56:51.453 E/name.fireflyii(26471): Invalid ID 0x00000001.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000002.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000002.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000006.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000006.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000010.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000010.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x0000000f.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x0000000f.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000003.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000003.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000004.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000004.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000005.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000005.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000002.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000002.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000006.
02-17 12:56:51.454 E/name.fireflyii(26471): Invalid ID 0x00000006.
02-17 12:56:51.455 E/name.fireflyii(26471): Invalid ID 0x0000000e.
02-17 12:56:51.455 E/name.fireflyii(26471): Invalid ID 0x0000000e.
02-17 12:56:51.455 E/name.fireflyii(26471): Invalid ID 0x00000013.
02-17 12:56:51.455 E/name.fireflyii(26471): Invalid ID 0x00000013.
02-17 12:56:51.455 E/name.fireflyii(26471): Invalid ID 0x00000016.
02-17 12:56:51.455 E/name.fireflyii(26471): Invalid ID 0x00000016.
02-17 12:56:51.455 E/name.fireflyii(26471): Invalid ID 0x00000014.
02-17 12:56:51.455 E/name.fireflyii(26471): Invalid ID 0x00000014.
02-17 12:56:51.460 E/name.fireflyii(26471): Invalid ID 0x00000013.
02-17 12:56:51.594 I/chatty  (26471): uid=10433(xyz.hisname.fireflyiii) identical 32 lines
02-17 12:56:51.594 E/name.fireflyii(26471): Invalid ID 0x00000013.
02-17 12:56:52.202 E/name.fireflyii(26471): Invalid ID 0x00000000.
02-17 12:56:52.202 E/name.fireflyii(26471): Invalid ID 0x00000000.
02-17 12:56:52.214 D/AndroidRuntime(26471): Shutting down VM
--------- beginning of crash
02-17 12:56:52.214 E/AndroidRuntime(26471): FATAL EXCEPTION: main
02-17 12:56:52.214 E/AndroidRuntime(26471): Process: xyz.hisname.fireflyiii, PID: 26471
02-17 12:56:52.214 E/AndroidRuntime(26471): java.lang.NullPointerException: accountManager.getUserDa…ount, "token_expires_in") must not be null
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at xyz.hisname.fireflyiii.data.local.account.AuthenticatorManager.getTokenExpiry(AuthenticatorManager.kt:1)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at xyz.hisname.fireflyiii.ui.settings.SettingsAccountFragment.onCreatePreferences(SettingsAccountFragment.kt:14)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:10)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:6)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:23)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:68)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:1)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at android.os.Handler.handleCallback(Handler.java:938)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at android.os.Looper.loop(Looper.java:233)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at android.app.ActivityThread.main(ActivityThread.java:7959)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at java.lang.reflect.Method.invoke(Native Method)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
02-17 12:56:52.214 E/AndroidRuntime(26471): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
02-17 12:56:52.214 E/ACRA    (26471): ACRA caught a NullPointerException for xyz.hisname.fireflyiii
02-17 12:56:52.214 E/ACRA    (26471): java.lang.NullPointerException: accountManager.getUserDa…ount, "token_expires_in") must not be null
02-17 12:56:52.214 E/ACRA    (26471): 	at xyz.hisname.fireflyiii.data.local.account.AuthenticatorManager.getTokenExpiry(AuthenticatorManager.kt:1)
02-17 12:56:52.214 E/ACRA    (26471): 	at xyz.hisname.fireflyiii.ui.settings.SettingsAccountFragment.onCreatePreferences(SettingsAccountFragment.kt:14)
02-17 12:56:52.214 E/ACRA    (26471): 	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:10)
02-17 12:56:52.214 E/ACRA    (26471): 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:6)
02-17 12:56:52.214 E/ACRA    (26471): 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
02-17 12:56:52.214 E/ACRA    (26471): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:23)
02-17 12:56:52.214 E/ACRA    (26471): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:68)
02-17 12:56:52.214 E/ACRA    (26471): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:10)
02-17 12:56:52.214 E/ACRA    (26471): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:12)
02-17 12:56:52.214 E/ACRA    (26471): 	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:1)
02-17 12:56:52.214 E/ACRA    (26471): 	at android.os.Handler.handleCallback(Handler.java:938)
02-17 12:56:52.214 E/ACRA    (26471): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-17 12:56:52.214 E/ACRA    (26471): 	at android.os.Looper.loop(Looper.java:233)
02-17 12:56:52.214 E/ACRA    (26471): 	at android.app.ActivityThread.main(ActivityThread.java:7959)
02-17 12:56:52.214 E/ACRA    (26471): 	at java.lang.reflect.Method.invoke(Native Method)
02-17 12:56:52.214 E/ACRA    (26471): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
02-17 12:56:52.214 E/ACRA    (26471): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
IS_SILENT=false
USER_CRASH_DATE=2021-02-17T12:56:52.217+01:00`

**Comment by emansih** [comment]
Will be fixed in the next release

**Comment by emansih** [comment]
Fixed in 4.1.0, it's being rolled out via play store now.
