### ISSUE TITLE
Crash on launch since update to v4

### ISSUE THREAD

**Issue by haho16** [emansih/FireflyMobile#153]
**Firefly III Server Version:**
v5.4.6
**Firefly III Mobile Version:**
4.1.0 (latest on Fdroid)
**Android Version:**  
7.1.2 (lineageOS 14.1)
**Device Information:**  

- BRAND: Xiaomi
- MODEL: Redmi4a
--------------------------------------

## Expected Behavior
Start the app after update
## Current Behavior
Getting crash reports
## Steps to Reproduce

[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/6063117/Fireflyiii-mobile.txt)

Hey, first thanks for maintaining this app - it is a great addition to my Firefly setup :). I tried to look through the issues for similar errors but didn't find any. I have been experiencing crashes since updating to v4.0 from Fdroid. I waited for another release on Fdroid (4.1.0) but after updating I am having the same logs. Seems something related to default currency. 
I also updated my server running on a raspberry pi to latest release of server app. 

It seems it is not able to send the request to the server app as I don't get any entry logs. Let me know if you need any more debugging on my side ;).

**Comment by emansih** [comment]
I'm not sure why this issue is happening. Are you connected to your server?

**Comment by haho16** [comment]
Hey @emansih. After reinstalling the app and connecting with a new personal token it is working well now :) Maybe it was a connection issue with the server due to misconfiguration unknown to me. Closing the issue and thanks a lot for the help!
