### ISSUE TITLE
Feature proposal

### ISSUE THREAD

**Issue by luifermoron** [emansih/FireflyMobile#154]
**Feature proposal:**

After making a transaction the bank app give me a image with transaction details, but I have to write manually again on the app. I am working on automatization through OCR. This is still a Hello World but I would be great if you accept this feature so we can work together.

**Proposal workflow:**  
1) User go to OCR settings and set "Tags" in order for looking up later thorugh OCR.
2) From his gallery user can select the FireflyMobile app and the open on AddTransactionActivity
3) Background tasks will go through every "Tag" registered before and extracting text. Then set automatically to the fields: description and amount.

Note: All the registered tag will be saved on Device db only in this version for simplicity.

I have the hello world code in a separete branch. It still does not hit database nor have an structure for Tags. Just hardcoded for now. In the following days I will be working on that.

![video](https://user-images.githubusercontent.com/26443806/110855998-77646580-828d-11eb-99bc-827d0052de6a.gif)

Please give me your impression and if there is a possibility on adding this feature.

**Comment by emansih** [comment]
Does it use any 3rd party libs? I am hesitant to add architecture specific libs since fdroid users will see an increase in APK size. However, your idea looks cool and I would love to see some implementation. I will assist you if you need any help in the code base.(The code isn't clean ;p)

**Comment by luifermoron** [comment]
Yes it does. In fact, I imported [this]( https://github.com/SubhamTyagi/android-ocr) project as a module and remove all UI stuffs. I can make a pull request of the branch so you can analyse it deeper. 

Thanks for your help, I am now in the moment of start touching DB, so Help will be needed. I will take a look of it and no doubt about asking if emerged a question.

**Comment by emansih** [comment]
Hi. I am closing this issue.
