### ISSUE TITLE
Creating Transaction Takes forever

### ISSUE THREAD

**Issue by gthbusrr** [emansih/FireflyMobile#155]
I am really greatful for this app, sorry for again reporting an issue (It could be on me)

**Firefly III Server Version:**
- 5.4.6 (Latest)

**Firefly III Mobile Version:**
- 4.4.0 (Latest)

**Android Version:**  
- 11

**Device Information:**  

- BRAND: Samsung
- MODEL: Galaxy Note20 Ultra
--------------------------------------

## Expected Behavior
- Transaction(s) to be created

### Tile
- Click "Transactions" Tile
- Create Withdrawal Transaction
- Loading Circle Spins Forever

### In App
- Click "+ CREATE NEW TRANSACTION"
- Create Deposit Transaction
- Loading Circle Spins Forever
- (Have to create transaction with web UI, i.e. Network is Normal)

**Comment by mehuser** [comment]
Hi,
I'm having the same problem, but in offline mode: could it be related to this [line](https://github.com/emansih/FireflyMobile/blob/befb8d2db73310b858583de2a1f258a8d96744d8/app/src/main/java/xyz/hisname/fireflyiii/repository/transaction/TransactionRepository.kt#L277) outside of the `return try {` block on line 278 of the same file?

**Comment by emansih** [comment]
The reason it is loading forever because Firefly III is returning an unexpected json value. I am not able to replicate this behavior on 5.4.6, however I am able to replicate this behavior on the demo site(5.5.0-beta.1). 

The issue is with bill_id returning an integer value of "0" on 5.4.6 when no bill is attached to the transaction. On 5.5.0-beta.1, bill_id returns an empty string when no bill is attached to the transaction. 

I have a bug report opened regarding the inconsistency in the API https://github.com/firefly-iii/firefly-iii/issues/4482#issuecomment-792670561

@JC5

**Comment by emansih** [comment]
This is the output of 5.4.6

```
{
  "data": {
    "type": "transactions",
    "id": "5",
    "attributes": {
      "created_at": "2021-03-13T09:50:13+11:00",
      "updated_at": "2021-03-13T09:50:13+11:00",
      "user": 1,
      "group_title": null,
      "transactions": [
        {
          "user": 1,
          "transaction_journal_id": 5,
          "type": "withdrawal",
          "date": "2021-03-13T00:00:00+11:00",
          "order": 0,
          "currency_id": 1,
          "currency_code": "EUR",
          "currency_name": "Euro",
          "currency_symbol": "\u20ac",
          "currency_decimal_places": 2,
          "foreign_currency_id": 0,
          "foreign_currency_code": null,
          "foreign_currency_symbol": null,
          "foreign_currency_decimal_places": 0,
          "amount": "123.000000000000",
          "foreign_amount": null,
          "description": "Test",
          "source_id": 1,
          "source_name": "Test bank",
          "source_iban": null,
          "source_type": "Asset account",
          "destination_id": 5,
          "destination_name": "Test name",
          "destination_iban": null,
          "destination_type": "Expense account",
          "budget_id": 0,
          "budget_name": null,
          "category_id": 0,
          "category_name": null,
          "bill_id": 0,
          "bill_name": null,
          "reconciled": false,
          "notes": null,
          "tags": [],
          "internal_reference": null,
          "external_id": null,
          "original_source": "ff3-v5.4.6|api-v1.4.0",
          "recurrence_id": null,
          "recurrence_total": null,
          "recurrence_count": null,
          "bunq_payment_id": null,
          "external_uri": null,
          "import_hash_v2": "064f16eeef3e46a9b8daeaa9267cb209575a705ac2e272530eb5dab0ca69c7de",
          "sepa_cc": null,
          "sepa_ct_op": null,
          "sepa_ct_id": null,
          "sepa_db": null,
          "sepa_country": null,
          "sepa_ep": null,
          "sepa_ci": null,
          "sepa_batch_id": null,
          "interest_date": null,
          "book_date": null,
          "process_date": null,
          "due_date": null,
          "payment_date": null,
          "invoice_date": null
        }
      ]
    }
}
```


This is the output of the demo site

```
{
  "data": {
    "type": "transactions",
    "id": "462",
    "attributes": {
      "created_at": "2021-03-12T23:59:29+01:00",
      "updated_at": "2021-03-12T23:59:29+01:00",
      "user": "1",
      "group_title": null,
      "transactions": [
        {
          "user": "1",
          "transaction_journal_id": 467,
          "type": "withdrawal",
          "date": "2021-03-12T14:00:00+01:00",
          "order": 0,
          "currency_id": "1",
          "currency_code": "EUR",
          "currency_name": "Euro",
          "currency_symbol": "\u20ac",
          "currency_decimal_places": 2,
          "foreign_currency_id": "0",
          "foreign_currency_code": null,
          "foreign_currency_symbol": null,
          "foreign_currency_decimal_places": 0,
          "amount": "123.000000000000",
          "foreign_amount": null,
          "description": "Test",
          "source_id": "1",
          "source_name": "Checking Account",
          "source_iban": "NL11XOLA6707795988",
          "source_type": "Asset account",
          "destination_id": "49",
          "destination_name": "Cafe",
          "destination_iban": null,
          "destination_type": "Expense account",
          "budget_id": "0",
          "budget_name": null,
          "category_id": "0",
          "category_name": null,
          "bill_id": "",
          "bill_name": null,
          "reconciled": false,
          "notes": null,
          "tags": [],
          "internal_reference": null,
          "external_id": null,
          "original_source": "ff3-v5.5.0-beta.1|api-v1.5.0",
          "recurrence_id": null,
          "recurrence_total": null,
          "recurrence_count": null,
          "bunq_payment_id": null,
          "external_uri": null,
          "import_hash_v2": "de1f73b0bc1919e62b095b4a961ae1dae72670f4b0ff8b83c22b26f6a2bf1159",
          "sepa_cc": null,
          "sepa_ct_op": null,
          "sepa_ct_id": null,
          "sepa_db": null,
          "sepa_country": null,
          "sepa_ep": null,
          "sepa_ci": null,
          "sepa_batch_id": null,
          "interest_date": null,
          "book_date": null,
          "process_date": null,
          "due_date": null,
          "payment_date": null,
          "invoice_date": null,
          "longitude": null,
          "latitude": null,
          "zoom_level": null
        }
      ]
    }
  }
}
```

Notice how various id is now a string instead of integer / long value? It's breaking the json parsing. This only occurs on beta versions though. Please check if you are really running on **stable** version

**Comment by JC5** [comment]
Bill ID should now be null or a string. Hope to release beta 2 and the updated API docs this weekend.

**Comment by emansih** [comment]
It can't be an integer value for id(s)? I feel it's easier to parse than string

**Comment by JC5** [comment]
https://jsonapi.org/format/#document-resource-objects

It appears they must be strings. I'm pouring over the API to update it.

**Comment by gthbusrr** [comment]
> This is the output of 5.4.6
> 
> ```
> {
>   "data": {
>     "type": "transactions",
>     "id": "5",
>     "attributes": {
>       "created_at": "2021-03-13T09:50:13+11:00",
>       "updated_at": "2021-03-13T09:50:13+11:00",
>       "user": 1,
>       "group_title": null,
>       "transactions": [
>         {
>           "user": 1,
>           "transaction_journal_id": 5,
>           "type": "withdrawal",
>           "date": "2021-03-13T00:00:00+11:00",
>           "order": 0,
>           "currency_id": 1,
>           "currency_code": "EUR",
>           "currency_name": "Euro",
>           "currency_symbol": "\u20ac",
>           "currency_decimal_places": 2,
>           "foreign_currency_id": 0,
>           "foreign_currency_code": null,
>           "foreign_currency_symbol": null,
>           "foreign_currency_decimal_places": 0,
>           "amount": "123.000000000000",
>           "foreign_amount": null,
>           "description": "Test",
>           "source_id": 1,
>           "source_name": "Test bank",
>           "source_iban": null,
>           "source_type": "Asset account",
>           "destination_id": 5,
>           "destination_name": "Test name",
>           "destination_iban": null,
>           "destination_type": "Expense account",
>           "budget_id": 0,
>           "budget_name": null,
>           "category_id": 0,
>           "category_name": null,
>           "bill_id": 0,
>           "bill_name": null,
>           "reconciled": false,
>           "notes": null,
>           "tags": [],
>           "internal_reference": null,
>           "external_id": null,
>           "original_source": "ff3-v5.4.6|api-v1.4.0",
>           "recurrence_id": null,
>           "recurrence_total": null,
>           "recurrence_count": null,
>           "bunq_payment_id": null,
>           "external_uri": null,
>           "import_hash_v2": "064f16eeef3e46a9b8daeaa9267cb209575a705ac2e272530eb5dab0ca69c7de",
>           "sepa_cc": null,
>           "sepa_ct_op": null,
>           "sepa_ct_id": null,
>           "sepa_db": null,
>           "sepa_country": null,
>           "sepa_ep": null,
>           "sepa_ci": null,
>           "sepa_batch_id": null,
>           "interest_date": null,
>           "book_date": null,
>           "process_date": null,
>           "due_date": null,
>           "payment_date": null,
>           "invoice_date": null
>         }
>       ]
>     }
> }
> ```
> 
> This is the output of the demo site
> 
> ```
> {
>   "data": {
>     "type": "transactions",
>     "id": "462",
>     "attributes": {
>       "created_at": "2021-03-12T23:59:29+01:00",
>       "updated_at": "2021-03-12T23:59:29+01:00",
>       "user": "1",
>       "group_title": null,
>       "transactions": [
>         {
>           "user": "1",
>           "transaction_journal_id": 467,
>           "type": "withdrawal",
>           "date": "2021-03-12T14:00:00+01:00",
>           "order": 0,
>           "currency_id": "1",
>           "currency_code": "EUR",
>           "currency_name": "Euro",
>           "currency_symbol": "\u20ac",
>           "currency_decimal_places": 2,
>           "foreign_currency_id": "0",
>           "foreign_currency_code": null,
>           "foreign_currency_symbol": null,
>           "foreign_currency_decimal_places": 0,
>           "amount": "123.000000000000",
>           "foreign_amount": null,
>           "description": "Test",
>           "source_id": "1",
>           "source_name": "Checking Account",
>           "source_iban": "NL11XOLA6707795988",
>           "source_type": "Asset account",
>           "destination_id": "49",
>           "destination_name": "Cafe",
>           "destination_iban": null,
>           "destination_type": "Expense account",
>           "budget_id": "0",
>           "budget_name": null,
>           "category_id": "0",
>           "category_name": null,
>           "bill_id": "",
>           "bill_name": null,
>           "reconciled": false,
>           "notes": null,
>           "tags": [],
>           "internal_reference": null,
>           "external_id": null,
>           "original_source": "ff3-v5.5.0-beta.1|api-v1.5.0",
>           "recurrence_id": null,
>           "recurrence_total": null,
>           "recurrence_count": null,
>           "bunq_payment_id": null,
>           "external_uri": null,
>           "import_hash_v2": "de1f73b0bc1919e62b095b4a961ae1dae72670f4b0ff8b83c22b26f6a2bf1159",
>           "sepa_cc": null,
>           "sepa_ct_op": null,
>           "sepa_ct_id": null,
>           "sepa_db": null,
>           "sepa_country": null,
>           "sepa_ep": null,
>           "sepa_ci": null,
>           "sepa_batch_id": null,
>           "interest_date": null,
>           "book_date": null,
>           "process_date": null,
>           "due_date": null,
>           "payment_date": null,
>           "invoice_date": null,
>           "longitude": null,
>           "latitude": null,
>           "zoom_level": null
>         }
>       ]
>     }
>   }
> }
> ```
> 
> Notice how various id is now a string instead of integer / long value? It's breaking the json parsing. This only occurs on beta versions though. Please check if you are really running on **stable** version

Yes, I've double checked that I'm running on the stable version. Thanks.

Debug information generated at 2021-03-13 14:26:55 Asia/Hong_Kong for Firefly III version **5.4.6**.

| Scope | Version |
| --- | --- |
| Firefly III | 5.4.6 |
| Firefly III API | 1.4.0 |
| PHP | 7.4.14 |
| Host | Linux |

| System info | Value |
| --- | --- |
| Using docker? | true |
| Telemetry | false |
| Layout | v1 |
| App environment | local |
| App debug mode | true |
| App cache driver | file |
| App logging | notice, stack |
| Display errors | Off |
| Error reporting | ALL errors |
| Interface | apache2handler |
| Default language | en_US |
| Default locale | equal |
| BCscale | 12 |
| DB drivers | mysql, pgsql, sqlite |
| Current driver | mysql |
| DB version | 15 (exp. 15) |
| Login provider | eloquent  |
| Trusted proxies (.env) | ** |

| User info | Value |
| --- | --- |
| Session start | 2021-03-01 00:00:00 |
| Session end | 2021-03-31 23:59:59 |
| Session first | 2020-12-31 00:00:00 |
| User ID | 1 |
| User language | en_GB |
| User locale | en_GB |
| Attempt at "en_GB.utf8" | 'en_GB.utf8' |
| Attempt at "en_GB.UTF-8" | 'en_GB.UTF-8' |

**Comment by emansih** [comment]
@gthbusrr  can you try this APK? It will display the error 
https://drive.google.com/file/d/1K4qGbDDRsqez3GIE4V-TJ_7DiXgMOz8s/view?usp=sharing

**Comment by gthbusrr** [comment]
> @gthbusrr can you try this APK? It will display the error
> https://drive.google.com/file/d/1K4qGbDDRsqez3GIE4V-TJ_7DiXgMOz8s/view?usp=sharing

@emansih I am terribly sorry that I am not able to produce any error message with the apk you've provided.

# Step to reproduce:
- Click "Transactions" Tile
- Create Withdrawal Transaction
- Loading Circle Spins Forever


![signal-2021-03-13-233019](https://user-images.githubusercontent.com/77537216/111035220-4d3bb080-8411-11eb-8127-086a5b7685f9.jpeg)

**Comment by gthbusrr** [comment]
@emansih Is there a debug version that I can get the log from logcat?

**Comment by emansih** [comment]
@gthbusrr and @mehuser try this APK. It will crash and show you the stack trace. https://drive.google.com/file/d/1D5eNA9is_4VuGj5lh9Yz4XNBPUnQe3zF/view?usp=sharing

**Comment by gthbusrr** [comment]
@emansih I've tried it but still didn't crash. Please see attached screen recording (I've cut it short due to file size constraint on GitHub. The spinning circle spins forever.)

https://user-images.githubusercontent.com/77537216/111054229-ed6df580-8462-11eb-96c1-bb15db70f95d.mp4

**Comment by emansih** [comment]
@gthbusrr After some debugging, I have fixed the issue. https://drive.google.com/file/d/1I-zfk0rqo-MMoUXxANb0mi3tpa6M4nib/view?usp=sharing

**Comment by mehuser** [comment]
Hi, 
I've just tried the last APK. After switching to 4G (going "offline", since my internal FF host is not published) and creating a new transaction, the application crashes with the attached stacktrace (i've redacted my internal FF FQDN)
[firefly-mobile_crash.txt](https://github.com/emansih/FireflyMobile/files/6136335/firefly-mobile_crash.txt)

**Comment by emansih** [comment]
@mehuser Are you able to add transaction when you are connected to your server though?

**Comment by mehuser** [comment]
Yes. As soon as I reconnect to my wifi connection, the transaction is added correctly.

**Comment by emansih** [comment]
@mehuser I will be pushing a new release. Will be available via Google Play in a few hours.

**Comment by mehuser** [comment]
Thank you. Since I'm using the Fdroid release (no play services here on grapheneos), is there a way to get that APK via a different channel?

**Comment by emansih** [comment]
via my self hosted fdroid instance. updates via that channel is instant

**Comment by fazlerabbi37** [comment]
@emansih I am assuming https://github.com/emansih/FireflyMobile/commit/776849a64df504c52c7efa117400561a326ced77 was included in some release? Did it ever make its way to official F-Droid release? Or it was only in Google Play and your self-hosted F-Droid instance?
