### ISSUE TITLE
Transaction not uploaded after returning online

### ISSUE THREAD

**Issue by mehuser** [emansih/FireflyMobile#158]
**Firefly III Server Version:**
 5.5.0-beta.1

**Firefly III Mobile Version:**
4.5.0 

**Android Version:**  

**Device Information:**  
 Android 11 - GrapheneOS
- BRAND: google
- MODEL: Pixel4a
--------------------------------------

## Expected Behaviour
After adding a transaction while offline and receiving the message "will be added when you are back online", the transaction gets synced as soon as the phone regain connectivity with FF Server

## Current Behaviour
The app displays the message will be "added when you are back online" and (while offline) it immediately send notification that states "Error Adding. Please try again later".
When the app regain connectivity to the server, the offline transactions never gets uploaded, even after 30+ minutes.
The app shows the error notification even after regaining connection (i.e quick toggle airplane mode (offline), add transaction, retoggle airplane mode (back online))

## Steps to Reproduce
1. Open the application
2. switch the airplane toggle to reproduce Firefly server unreachability
3. add a transaction from dashboard and get notified with "Error Adding. Please try again later".
4. disable airplane toggle and wait. Offline transaction never gets uploaded

**Comment by emansih** [comment]
yes I notice this bug a few days ago. I will fix it when I have the time
