### ISSUE TITLE
Notes field is not correctly assigned in Tasker Plugin

### ISSUE THREAD

**Issue by luxcel** [emansih/FireflyMobile#160]
**Firefly III Server Version:**
5.4.6
**Firefly III Mobile Version:**
4.3.0
**Android Version:**  
11
**Device Information:**  

- BRAND: ASUS
- MODEL: ZenPhone 6
--------------------------------------

## Expected Behavior
When using the Tasker Plugin to add a new Deposit the "Notes" field should be addes as "Notes".

## Current Behavior
Using the Tasker Plugin to add a new Deposit the "Notes" field is added as a "Bill".
Using the Photuris III App itself works fine, the issue only happens using Tasker.

## Steps to Reproduce
Create a new Deposit using the Tasker Plugin and add any input to the "Notes" field.

![Screenshot_20210318-190832471](https://user-images.githubusercontent.com/10106446/111676025-076e5600-881e-11eb-9c49-077b2cda043f.jpg)
![Screenshot_20210318-190844410](https://user-images.githubusercontent.com/10106446/111676028-0806ec80-881e-11eb-818a-9a9e61fcc47b.jpg)

**Comment by emansih** [comment]
Fixed. Will be pushed to Play store in a few days time. If you are enrolled to Play Store beta testing program, you will receive the update soon. You will have to delete the task before adding before taking effect though. sorry about that
