### ISSUE TITLE
Budget values dont show in the budget tab

### ISSUE THREAD

**Issue by corcom** [emansih/FireflyMobile#162]
**Firefly III Server Version:**
5.5.3
**Firefly III Mobile Version:**
4.6.0
**Android Version:**  
11
**Device Information:**  

- BRAND: google
- MODEL: pixel 4a
- OS: CalyxOS 2.4.0
--------------------------------------

## Expected Behavior
Open the budget tab and see the set value for each budget and how much was already used
## Current Behavior
Budget tab only shows the amount used while show 0 as the set budget although when editing a budget the set amount is correct

Note:
It says that all my budgets are auto budgets even though they are not and are in fact regular budgets.
## Steps to Reproduce
Create budgets in the web app then view them from the android app

![signal-2021-04-12-174614](https://user-images.githubusercontent.com/82392239/114413883-0b8c5a00-9bb7-11eb-8d68-59b2885dbfb3.jpg)
![signal-2021-04-12-175029](https://user-images.githubusercontent.com/82392239/114414619-a6853400-9bb7-11eb-9523-cb72dec6e574.png)

**Comment by emansih** [comment]
Hi. I am aware of this issue. There are new API updates on Firefly 5.5.3. I will fix it this weekend.

**Comment by corcom** [comment]
Thats great! Thanks for all the great work!

**Comment by emansih** [comment]
It's rolling out via Google Play Store as we speak.

**Comment by corcom** [comment]
Great! F-droid too?

**Comment by emansih** [comment]
It will take a couple of days for it to show up on official fdroid store.

**Comment by corcom** [comment]
Is there a private repository that i can add?

**Comment by emansih** [comment]
https://github.com/emansih/FireflyMobile/wiki/FDroid

**Comment by corcom** [comment]
Thanks a lot!
