### ISSUE TITLE
Problem authenticating with oauth

### ISSUE THREAD

**Issue by angubite** [emansih/FireflyMobile#164]
**Firefly III Server Version:**
5.5.9
**Firefly III Mobile Version:**
4.7.0
**Android Version:**  
10
**Device Information:**  

- BRAND:
- MODEL: 
--------------------------------------

## Expected Behavior
Connect to private yunohost server through mobile app using oauth
## Current Behavior
I'm running a firefly instance on my yunohost server. I created an oauth client and then tried authenticating with the URL, client ID and client secret. The default browser opens and I get redirected to my yunohost login page. After login I get redirected to the firefly login page. Now I would expect to see the option to authorize or cancle. Instead I am presented with a popup asking for a username and password again. I have tried reentering my yunohost as well as my firefly login details, but both are not accepted. switching default browser gives the same results.
I have not seen any other similar issues so it may be a problem with yunohost...(?).
I'd appreciate any help. Thanks

**Comment by emansih** [comment]
Hi. I have not tested against yunohost. From what I can tell, the issue is that the redirect uri does not contain a token.

**Comment by emansih** [comment]
@angubite Hi. Are you still having OAuth issues?

**Comment by JesApp** [comment]
I have the some problem and I also host via yunohost. Seems to be related to that specific setup, rather than the app.

**Comment by JesApp** [comment]
Also, yunohost currently ships firefly II v5.4.6. I have opened an issue [here](https://github.com/YunoHost-Apps/firefly-iii/issues/39).

**Comment by emansih** [comment]
@JesApp does Personal Access Token work?

**Comment by JesApp** [comment]
No, it throws a JSON parsing error. I was going to create an issue on that, when I found out that yunohost is out of date. If that problem still occurs after an update, I'll let you know.

**Comment by emansih** [comment]
Ah yes. I forgot it wouldn't work since the app is using the newer Firefly III API for Personal Access Token.
