### ISSUE TITLE
Can't authenticate, "Please install a web browser"

### ISSUE THREAD

**Issue by j0risj** [emansih/FireflyMobile#168]
**Firefly III Server Version:**
5.5.10
**Firefly III Mobile Version:**
4.8.0
**Android Version:**  
11
**Device Information:**  
- BRAND: Google
- MODEL: Pixel 4a
--------------------------------------

## Current Behavior
When trying to authenticate via oauth the error message "No application can handle this request. Please install a web browser" pops up. It doesn't matter which URL you put into the URL field. Same thing happens when tapping the help button in the top right corner.
## Steps to Reproduce
Install the app, then tap the help button in the top right corner or try to authenticate to some URL via oauth.

[Screenshot of error message](https://imgur.com/a/MxpCm9t)

**Comment by emansih** [comment]
What browser are you using?

**Comment by j0risj** [comment]
I have Firefox and Firefox Focus installed. I already tried to change the default browser, but that doesn't seem to help.

**Comment by emansih** [comment]
Seems to be related to this issue. https://developer.android.com/about/versions/11/privacy/package-visibility

**Comment by emansih** [comment]
@j0risj try this https://drive.google.com/file/d/1SNFXQkYfo62B7PNgkvhDhFyeOcTWoEEf/view?usp=sharing

**Comment by j0risj** [comment]
That fixed it, thank you very much.

**Comment by emansih** [comment]
nice. I will push a release tonight.
