### ISSUE TITLE
Multiple logins to different user accounts/Firefly instances

### ISSUE THREAD

**Issue by tomasz-lasko** [emansih/FireflyMobile#174]
Hello, nice app, but is it planned to support having multiple users and/or Firefly servers instances logged in and switching between them?  

For example: if I have Alice on https://some.example.com and Bob on https://other.example.com, then I would like to have them both logged in and switch between them, and even use them offline.

From what I see in the app UI, the email address of my user seems to be a UI widget that can be switched, but there is no option to add another account. So it looks like it is planned to be implemented in the future. Am I correct? If yes then what is its priority in feature backlog? :) Thanks!

**Comment by emansih** [comment]
Hello. I did thought of implementing such a feature but 

- You are using this on a _mobile_ device. Do you need to have multiple accounts?
- Firefly III doesn't support multiple accounts

If such a feature is in hot demand, I can implement it but it will probably take half a month due to my current life commitments

**Comment by tomasz-lasko** [comment]
Yes, exactly - one mobile device application and inside this application I switch between different Firefly III user accounts. These accounts can be on same Firefly III server installation, and/or can be on separate server installation - actually nobody cares on which server they are, because indeed they are completely separate on the server. So Firefly III server supports multiple accounts, they are just completely separated from each other.

So this feature is exactly the same as in any email client application. If you have three mails (alice@mydomain.net, bob@gmail.com, charlie@gmail.com) and they can be completely separate email accounts, isolated from each other (even if bob and charlie are on the same GMail server), then you can still have three totally separate mail accounts in one mail client application and switch between those accounts and use them normally. This is instead of having three different mail client applications that each could have only one email account configured.

I am not sure if this is a hot demand for everybody in the world, but people I know will use multiple accounts, so that they can have e.g. one private account for their personal money, and other accounts to track shared expenses with other people - in e.g. an organization they are part of, or if they have some small shared activity project that two or more people are participating in.

This is important to have it in your mobile app because it can have operations offline from a mobile phone, authenticated. Otherwise - if there is no such multi-account feature in the mobile app (= current state of the app) - then one has to login to Firefly III server from the mobile web browser to one account. And in order to quickly switch to another account in a mobile browser, one has to either use multiple mobile browsers (e.f. Firefox for one account, Brave for another, etc - where you have to trust the browser's manufacturer), or stick to one browser but then logout and login to another account by entering password each time in the mobile keyboard or having the passwords remembered in the browser. This is not too safe, and convenient altogether.

I do not dare to ask you to implement this multi-account right now, but you can on your own think for how many users of your application this would be important. But people I know that use Firefly III will definitely wait patiently, hoping very much to see this multi-account feature implemented in your mobile app.

**Comment by emansih** [comment]
@tomasz-lasko Hello. Just an update on this issue. I am still working on this feature. If you look at `dev` branch, there is some early work on it.

**Comment by emansih** [comment]
Hello @tomasz-lasko . I can finally close this. This feature will be available in the next release. I am currently pushing a new build via Google Play.

**Comment by tomasz-lasko** [comment]
Thank @emansih  you very much, looking forward to seeing this :) Actually I am using F-Droid repo for your app, but I guess it will be there in near future too :)
