### ISSUE TITLE
Allow http connection

### ISSUE THREAD

**Issue by kopach** [emansih/FireflyMobile#176]
Please, allow insecure connection to firefly III server over http. I do have firefly server running in my local env. When I need to access server over internet - I use VPN to connect to local network. There is no reason trying to setup https in this case. 
Any chance this mobile app could allow insecure connection? Maybe with some danger warning?

**Comment by emansih** [comment]
I have stated many times, http is not supported. i have made it easy to import self signed cert. If you need http support, build the app with the following changes: https://github.com/blacjac21/FireflyMobile/commit/a95406cf572b88e65727bdda2e101a6151adfc76
