### ISSUE TITLE
Income of current month in dashboard page is incorrectly calculated

### ISSUE THREAD

**Issue by leander091** [emansih/FireflyMobile#177]
**Firefly III Server Version:**
5.5.13
**Firefly III Mobile Version:**
4.11.0
**Android Version:**  
11
**Device Information:**  

- BRAND:ONEPLUS
- MODEL: ONEPLUS A6003 (OnePlus6)
--------------------------------------

## Expected Behavior
The net earning graph being generated based on the correct amount of income and expense.
## Current Behavior
The income graph of the current month is way to high.  Based on the imported transactions of this month I should have an income of 60.86 euros. But it is shown as 2.64k (euros). It is coincidentally the same amount as the first displayed month in the graph.
The table right behind the graph shows the correct details of income and expenses for this month.
## Steps to Reproduce
I am not sure how to reproduce this. 
I've cleared the cache of the app already. but it does not solve this bug

**Comment by emansih** [comment]
Hi. I will look into it. I currently have a couple of backlogs and I don't have the capability to fix it immediately. Sorry about it.

**Comment by leander091** [comment]
Hi @emansih, i did some digging and debugging and found the bug. I've also created an pull request to solve this issue. 
So maybe this could help to reduce your backlog a little bit :)
