### ISSUE TITLE
Menu not opening when Security option enabled

### ISSUE THREAD

**Issue by MichalRybecky** [emansih/FireflyMobile#180]
**Firefly III Server Version:**
5.4.6
**Firefly III Mobile Version:**
4.12.0
**Android Version:**  
11
**Device Information:**  
Google Pixel 5 running CalyxOS with microG enabled, Photuris III downloaded from F-droid
- BRAND: Google
- MODEL: Pixel 5
--------------------------------------

## Expected Behavior
Menu opens after clicking Menu button.
## Current Behavior
Menu does not open, button does "clicked animation".
## Steps to Reproduce
1. "Options" -> "Settings" -> Check "Security"
2. Relaunch App
3. Authenticate with biometrics
4. Click on Menu button
5. Menu does not open.

I was able to open menu by long-press and swipe to the right on the very left edge of the button.

**Comment by emansih** [comment]
Seems like the drawer isn't being initialised. I will look into it.

**Comment by emansih** [comment]
Will be fixed in the next release

**Comment by MichalRybecky** [comment]
Thank you!
