### ISSUE TITLE
[Feature Request] Adding BasicAuth support

### ISSUE THREAD

**Issue by SD-Chargers** [emansih/FireflyMobile#189]
**Firefly III Server Version:** 5.6.5

**Firefly III Mobile Version:** 4.14.2

**Android Version:** 10

**Device Information:**  
- BRAND: Huawei
- MODEL: P30

--------------------------------------

Hello,
as stated above i was wondering if it would be possible to add support for HTTP BasicAuth for the app (or if it is working but i am doing something wrong)?

I am currenty using an NGINX webserver / proxy with BasicAuth infront the Firefly installation.
Just because i normally don't put open web applications in the wild.

The app (using Personal Access Token) is not able to use Basic Auth as far as i can tell. I've tried setting 'https://user:password@example.com' as the URL with no luck, it did not send the user / password and resulted in a 401.

Is it possible to add this or any other mean to 'hide' the website whilst still using the app? Another solution would be using a VPN in between the connection but I wanted to ask beforehand.

Thanks for this marvelous app and your time.

**Comment by emansih** [comment]
Hi. You will have to punch a hole through your firewall for this app to work. There was some discussion regarding this. https://github.com/emansih/FireflyMobile/issues/100


Also do you use NextCloud? If so, how does NextCloud handle it?

**Comment by SD-Chargers** [comment]
A hole in the firewall aint the problem as the instance itself is in a sandboxed enviroment.

I will try an authelia setup for debugging purposes, was hoping to get around increasing complexity in the setup regardless - you cant possible get any simpler by using BasicAuth provided by the webserver.

However maybe ill find a way around the limitation by playing around with it and the issue you've linked.

No real experience using nextcloud for more but quick pc to server file syncs in a vpn enviroment.

**Comment by emansih** [comment]
The app will function the same way as how you connect to other apps(such as Nextcloud), via a VPN.

**Comment by SD-Chargers** [comment]
Okay so I've now have roughly the same setup as stated in #100 

I am however not really ok with that and will workaround the problem using a nginx config that asks for a valid BasicAuth user via WAN and skips this step if the requests comes via the VPN network.

Not happy with that either but its a solution till I figure out if i keep FireflyIII or not.

Thanks for your help.
