### ISSUE TITLE
unable to sign in

### ISSUE THREAD

**Issue by bartmaniac** [emansih/FireflyMobile#19]
**Firefly III Server Version:4.7.9

**Firefly III Mobile Version:1.0.2

**Android Version:8.1.0

**Device Information:

- BRAND: Huawei
- MODEL: Nexus 6P
--------------------------------------

## Expected Behavior
Able to login succesfully 

## Current Behavior

I followed the steps.
On firefly-III I Created a new client under OAuth Clients. 
Name: I picked a name
Redirected URL: http://empty
I got an id and a secret key

Back on the android smartphone I choose Oauth Auth and filled in the URL Client ID and Secret fields with the same values as the one in firefly-iii. After pressing Sign in I get 

Authentication Failed
Therer was an issue retrieving access token from your Firefly III instance. Ensure you are using http://empty as your redirected URL in your Firefly III config

I am doing this on the same internal network. Firefly III is running on mac os High Sierra, under Docker

**Comment by bartmaniac** [comment]
I got this release from f-droid telling me i'm [up-to-date.
Where do I find and how to install latest version

Thanks a lot

**Comment by emansih** [comment]
https://github.com/emansih/FireflyMobile/releases

**Comment by filoor** [comment]
Hi @emansih,

I have tried the new version and i'm still getting "Authentication Failed"

**Comment by emansih** [comment]
@filoor have you followed the steps found [here](https://github.com/emansih/FireflyMobile/wiki/Authentication)?

**Comment by bartmaniac** [comment]
Does one need to be on the same network where firefly-iii is running? . I am trying this on my smartphone at work over 4G while my pc where firefly-iii is running is at my home and there is no portforwarding setup up

**Comment by emansih** [comment]
Are you able to access firefly from the web browser?

**Comment by bartmaniac** [comment]
I can access firefly from my webbrowser when i am at home. I enter localhost:8081/login and get the login page

**Comment by bartmaniac** [comment]
Probably not I guess. I guess i have to enter an internet ip adress not a local 192.168.0.xx

**Comment by emansih** [comment]
@bartmaniac yes! you are getting onto something

**Comment by emansih** [comment]
@bartmaniac anymore issues?

**Comment by bartmaniac** [comment]
well I have no idea how I could make this work. on one hand there is the local firefly database with all the data (running on a local pc with a 192.168.0 .22 ip address and on the other hand the smartphone on a mobile network.

**Comment by emansih** [comment]
Since I assume you are running purely on a local network( no port forwarding, no ports open to outside world), simply ensure that both your PC and phone are on the same network. Then use 192.168.0.22 as the url

**Comment by emansih** [comment]
@bartmaniac are you still having issues?
