### ISSUE TITLE
App crash - char sequence is empty.

### ISSUE THREAD

**Issue by sysoppl** [emansih/FireflyMobile#195]
**Firefly III Server Version:**
5.6.10
**Firefly III Mobile Version:**
5.0.3 (Google Play) AND from https://github.com/emansih/FireflyMobile/issues/192#issuecomment-1013785197
**Android Version:**  
12
**Device Information:**  
- BRAND: Google
- MODEL: Pixel 4a
--------------------------------------

So as others, I have problem with launching app. It crashes right away leaving just the fingerprint request popup opened. Because logs from other people are in some way different I'm opening new issue. I can also debug and provide some logs from Android Studio if you want. I also tried version that you provided here https://github.com/emansih/FireflyMobile/issues/192#issuecomment-1013785197 but it also doesn't work (logs below). All I know for now is that your app was working about week ago. Also as I'm on Google Pixel there is no impact from phone brand UI overlay.

Firefly server is running on docker, latest. I auth to your app via API key (or something similar, I don't remember correctly / not OAuth for sure).

**Update:**
So i cleared data and was able to log in via PAT. After this it looks like it is working (dashboard is visible) but after I tried to go to account settings or add new transaction app is crashing. Logs after that: (that was on the GDrive version!)
[3.txt](https://github.com/emansih/FireflyMobile/files/7897314/3.txt)
[2.txt](https://github.com/emansih/FireflyMobile/files/7897315/2.txt)
[1.txt](https://github.com/emansih/FireflyMobile/files/7897316/1.txt)

## Expected Behavior
Do not crash
## Current Behavior
Crash when open
## Steps to Reproduce
Open app -> crash before auth

[GPlay version log.txt](https://github.com/emansih/FireflyMobile/files/7897163/GPlay.version.log.txt)
[GDrive version log.txt](https://github.com/emansih/FireflyMobile/files/7897164/GDrive.version.log.txt)
I'm providing logs from GPlay version (5.0.3) and from URL that you provided in other issues.

**Comment by emansih** [comment]
Weird bug. Google Play showed 0 crashes for the last 14 days. I can only _try_ to replicate the bug
![image](https://user-images.githubusercontent.com/5896415/150423511-e6ed9ac6-8adc-43ef-a9db-0002a7b58b65.png)

**Comment by sysoppl** [comment]
Well, I installed it freshly from Google Play Store. Black screen with one tap is where fingerprint popup show up - it records black screen for privacy. Weirdly GPConsole won't show all crashed for my app either. 

https://user-images.githubusercontent.com/30871217/150482988-730a7fbf-8d1e-4404-bb64-9db5ad20bd16.mp4

**Comment by sysoppl** [comment]
Well, 5.0.4 did nothing, same thing is happening.

**Comment by emansih** [comment]
Uninstalled and install again?

**Comment by sysoppl** [comment]
Yeah, I tried that. Cannot even log in because of crash

**Comment by emansih** [comment]
It's fixed, I hope. I borrowed a friend's phone to test it.

**Comment by sysoppl** [comment]
Yess, 5.0.5 fixed all issues. Thank you
