### ISSUE TITLE
do not init() the default SSLContext

### ISSUE THREAD

**Issue by budda85** [emansih/FireflyMobile#204]
**Firefly III Server Version:**
5.6.10
**Firefly III Mobile Version:**
5.0.3
**Android Version:**  
12
**Device Information:**  
Google Pixel 4a
GrapheneOS
--------------------------------------

## Expected Behavior
Login with https and self signed cert
## Current Behavior
Can't login.
I have install Firefly iii with docker on my synology nas.
I use a reverse proxy with a self signed cert.
With the Browser i have no problem over https.
I try to connect with the APP but there is the error "do not init() the default SSLContext". What am i doing wrong?

![Screenshot_20220127-221442_1](https://user-images.githubusercontent.com/20152200/151446523-9a35b29c-411e-45b3-88b5-5f7970ce424e.png)

**Comment by emansih** [comment]
That's interesting. I used to init() using SSL but I was told that it was _insecure_ (https://gist.github.com/misterAnderson90/1a8107d45e5d427c41f2e55b747409f0) so I started using the default init(). Change occurred in https://github.com/emansih/FireflyMobile/commit/07af778faa3a3177578ffe6346c95bc8e7146226. I will change the behavior again.

**Comment by budda85** [comment]
Is there a workaround, so that i can use the APP?

**Comment by teldosas** [comment]
I went over the gist you posted and there it seems that it is suggested that something like this should be done:
```kotlin
val sslContext = SSLContext.getInstance("TLSv1.2")
```
So, maybe this is why we get the error?

**Comment by emansih** [comment]
I will push out the update tonight

**Comment by budda85** [comment]
It works.
Thank you!
