### ISSUE TITLE
Future Request option to setting 

### ISSUE THREAD

**Issue by michelebossa** [emansih/FireflyMobile#205]
Firefly III Server Version: 5.6.10

Firefly III Mobile Version: 5.0.5

Android Version: 12

Device Information:

BRAND: Samsun
MODEL: A52
--------------------------------------
Dear Developer,
I'd like the possibility to move by some setting some fields from section "Optional Fields" to normal Field under adding of transaction.

I'n my cases i usually fill the Category for each transaction and now i need to do this to made an extra push to open the extra section.

Thanks.
<img width="191" alt="image" src="https://user-images.githubusercontent.com/38975058/151774696-1b6745bd-7432-44fb-b96b-89c312143d6a.png">

**Comment by emansih** [comment]
It is under optional setting because it is.... _optional_, it's the same as Firefly. I feel that this gives users a clear indication. Changing the UI will confuse users since they may think the fields are now mandatory.

**Comment by michelebossa** [comment]
ok i understand the your point of view.
