### ISSUE TITLE
[Feature Request] Make transactions changeable

### ISSUE THREAD

**Issue by DarkWingMcQuack** [emansih/FireflyMobile#21]
**Firefly III Server Version:**
4.7.8

**Firefly III Mobile Version:**
1.1.0
**Android Version:**  
LineageOS 14.1

**Device Information:**  
Nexus 5X

--------------------------------------
It would be nice to be able to change/update existing transactions
## Expected Behavior
Make a transaction view where already existing transactions can be changed and viewed
## Current Behavior
Already existing transactions cannot be changed, updated or deleted

**Comment by emansih** [comment]
It's available in the latest release(v1.1.1)
