### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by fayek** [emansih/FireflyMobile#210]
**Firefly III Server Version: 5.6.16

**Firefly III Mobile Version: 5.0.3

**Android Version: 12

**Device Information:   

- BRAND: Samsung
- MODEL: Galaxy S20 FE
--------------------------------------

## Expected Behavior
I can connect to Firefly iii via Oauth and see the dashboard screen. The functions on the app should be usable.

## Current Behavior
Clicking something on the dashboard screen crashes the app. After that it's impossible to restart the app as it crashes immediately. 
I'll have to reset the app and empty cache to get to login again.

## Steps to Reproduce
Open App
Connect via Oauth
Click on a function on dashboard.

[PhoturisIII_Bug_Report.txt](https://github.com/emansih/FireflyMobile/files/8192269/PhoturisIII_Bug_Report.txt)

**Comment by teldosas** [comment]
This looks like a duplicate of #206

**Comment by fayek** [comment]
That seemed to work. It did crash once more for no special reason but it seems to work now. Thank you.
