### ISSUE TITLE
Changing the Date Time Format makes app crash at start

### ISSUE THREAD

**Issue by jhelterhoff** [emansih/FireflyMobile#237]
**Firefly III Server Version:**
5.7.18

**Firefly III Mobile Version:**
5.0.7

**Android Version:**  
12

**Device Information:**  

- BRAND: motorola
- MODEL: g30
--------------------------------------

## Expected Behavior
No crash

## Current Behavior
Changing the Date Time Format in the Transaction Setting results in the app crashing at every start.

## Steps to Reproduce

- Open the app and connect to the server.
- Change the Date Time Format from unspecified to another format (I tried _"dd MM yyy hh:mm a_", _"dd MM yyy HH:mm"_ and _"dd MMM yyy HH:mm"_)
- Restart the app to apply the changes.
- --> App crashes immediately at every start. Using the app again is only possible after deleting the app storage.

[The log is too long to paste it completely, so I uploaded it to Pastebin.](https://pastebin.com/eSvs3XwX)

**Comment by emansih** [comment]
Hello. [This commit](https://github.com/emansih/FireflyMobile/commit/558e542c4773b430f1a2a8bf0cede2bcbd74934b) fixes the bug
