### ISSUE TITLE
Unable to connect using PAT on non-standard port

### ISSUE THREAD

**Issue by agilob** [emansih/FireflyMobile#27]
**Firefly III Server Version:**
Version 4.7.9

**Firefly III Mobile Version:**
1.2.1

**Android Version:**  
6

## Expected Behavior
Login to my account

## Current Behavior
Authentication failure when trying to connect to my local server on non-standard port 8777 using PAT.

What URL should I give? Should I add `http://` or just `firefly:8777`?

**Comment by emansih** [comment]
You are the first user i have seen with a non standard port.
