### ISSUE TITLE
"X null" Error on accounts

### ISSUE THREAD

**Issue by TMaddox** [emansih/FireflyMobile#33]
**Firefly III Server Version:** 4.7.12

**Firefly III Mobile Version:** 1.2.6

**Android Version:**  9

**Device Information:**  

- BRAND: POCOPHONE
- MODEL: F1
--------------------------------------

## Expected Behavior
When I navigate to either Asset Accounts, Expense Account, Revenue Accounts or Liability accounts, they should display without an error.
## Current Behavior
"X null" is displayed as an error

![photo_2019-02-23_10-03-28](https://user-images.githubusercontent.com/20703314/53284287-82a1d280-3752-11e9-9e8b-cef28bc0d72e.jpg)

**Comment by emansih** [comment]
The 'X' is actually an icon
