### ISSUE TITLE
Text '2019-xx-xx' could not be parsed at index 10

### ISSUE THREAD

**Issue by joshwapohlmann** [emansih/FireflyMobile#35]
**Firefly III Server Version:**
4.7.10

**Firefly III Mobile Version:**
1.2.6

**Android Version:**  
7.0

Error when opening **expenses**. It says *Text '2019-xx-xx' could not be parsed at index 10*

## Expected Behavior
Showing the expenses

## Current Behavior
Shows nothing, only the error.

## Steps to Reproduce
Open the expenses tab 

![photo5452058071846201707](https://user-images.githubusercontent.com/36891156/53402895-e1658700-39b2-11e9-9c25-4a02cc67cf7f.jpg)
![photo5452058071846201706](https://user-images.githubusercontent.com/36891156/53402898-e296b400-39b2-11e9-9d68-3efdafaf50d8.jpg)

**Comment by emansih** [comment]
With Firefly 4.7.11 supports time stamp in transaction output. 

 I still considering this a bug as I would like to be backwards compatible.

**Comment by emansih** [comment]
@joshwapohlmann hey are you able to update your Firefly III instance? It's a pain to write a compatible shims for the  old and new transaction api.

**Comment by joshwapohlmann** [comment]
Yes, I'll do it anyway every once in a while.
