### ISSUE TITLE
Detail view isn't hidden while editing transaction

### ISSUE THREAD

**Issue by jpalczewski** [emansih/FireflyMobile#36]
**Firefly III Server Version:**
4.7.12
**Firefly III Mobile Version:** 
1.2.6
**Android Version:**  
9, latest one
**Device Information:**  

- BRAND: Mobile
- MODEL: Mi A2
--------------------------------------
When editing an transaction, new widgets appears while old one don't hide - maybe new Android again broken something. 
## Expected Behavior
Editing transactions looks nice
## Current Behavior
Absolutely mess while editing a transaction
## Steps to Reproduce
1. create a transaction
2. view one in mobile application
3. from dot menu select edit

https://imgur.com/a/zlDSkx4

**Comment by emansih** [comment]
Hmm...yeah... The bug is not "consistent", I can't replicate the bug sometimes.

**Comment by emansih** [comment]
Thanks for your report. Bug fixed in v1.2.7.
