### ISSUE TITLE
[Feature Request] Specify budget in new transaction

### ISSUE THREAD

**Issue by ImLemni** [emansih/FireflyMobile#37]
**Firefly III Mobile Version: 1.2.6**

Hi,
It would be great if it was possible to specify the budget when adding a new transaction. I don't need a full budget support in the app but adding a box, similar to the "Tag" section, to specify already existing budget could be helpful.

Thank you for this project !

**Comment by emansih** [comment]
Thanks for your suggestion. Support added in v1.2.7.
