### ISSUE TITLE
Can't sign in with OAuth or Access token

### ISSUE THREAD

**Issue by Vardex** [emansih/FireflyMobile#38]
**Firefly III Server Version:**
4.7.14
**Firefly III Mobile Version:**
1.2.6
**Android Version:**  
8.1.0
**Device Information:**  

- BRAND: OnePlus
- MODEL: dumpling
--------------------------------------

## Expected Behavior

I should be able to sign in to my firefly III server.

## Current Behavior

When trying to login via OAuth I get an error: `{"error": "invalid_client", "message": "Client authentication failed"}`.

And when trying to login via access token I get an error: `use jsonreader.setlenient(true) to accept malformed json at line 2 column 1 path $`.

## Additional Information

My Firefly III server is under an OAuth2 authentication (Google OAuth).

**Comment by emansih** [comment]
> My Firefly III server is under an OAuth2 authentication (Google OAuth).

Sandstorm?

**Comment by Vardex** [comment]
> > My Firefly III server is under an OAuth2 authentication (Google OAuth).
> 
> [Sandstorm](https://github.com/firefly-iii/firefly-iii/issues/1965#issuecomment-451440503)?

Nope, running it with the official Docker container.

**Comment by emansih** [comment]
How do you use Google OAuth? ![](https://i.imgur.com/LCYAV4s.jpg)

**Comment by Vardex** [comment]
To access any page on my domain I need to sign in on a specific google user account.

Look like this if I'm on a browser where I never logged on my server.

![googleoauth](https://user-images.githubusercontent.com/12969608/53627320-76ad8900-3c08-11e9-9c98-07a9968e7a9f.png)

**Comment by emansih** [comment]
woah, never seen such a use case before. So you can't access Firefly III via a publicly available URL without going through Google?

**Comment by Vardex** [comment]
Yes, you need to sign in to a specific Google account to access the webpage.

**Comment by emansih** [comment]
Sorry, this adds additional complexity. I won't be adding support for your use case. sorry.
