### ISSUE TITLE
Please add pin-code on launch

### ISSUE THREAD

**Issue by ptah-alexs** [emansih/FireflyMobile#39]
Please add pin-code on launch or blocking of screen.

**Comment by emansih** [comment]
Isn't your device's pin code sufficient?

**Comment by ptah-alexs** [comment]
My cousin or other relatives can use my phone.

**Comment by emansih** [comment]
Will be added in the next release. A few things to note. Assuming someone gains root access, the keyguard can be disabled easily. Your database is also stored unencrypted, if you have root access, it can be read too.
