### ISSUE TITLE
Crashing if Transaction has attachments

### ISSUE THREAD

**Issue by fictitiousexistence** [emansih/FireflyMobile#42]
**Firefly III Server Version:**
4.7.17

**Firefly III Mobile Version:**
1.2.10
**Android Version:**  
7.1.1
**Device Information:**  

- BRAND:LG
- MODEL: Stylo 3 Plus
--------------------------------------

## Current Behavior
App crashes when attempting to view a transaction that has attachments
## Steps to Reproduce
Add attachment to a transaction. View transaction. 

[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/3001028/Fireflyiii-mobile.txt)

**Comment by emansih** [comment]
Are you able to test the apk if I provide you one?

**Comment by emansih** [comment]
Hey @fictitiousexistence as per our last conversation over email, is the bug still present in the latest release?

**Comment by fictitiousexistence** [comment]
Nope. Its working great now. Able to view the transaction and the attachments perfectly. 

Thanks. 

________________________________
