### ISSUE TITLE
App crashes : NumberFormatException

### ISSUE THREAD

**Issue by ImLemni** [emansih/FireflyMobile#43]
**Firefly III Server Version: 4.7.17**

**Firefly III Mobile Version:1.2.14**

**Android Version:9**  

--------------------------------------

## Expected Behavior
The app should launch and show transactions

## Current Behavior
After adding my account, the app tries to download transactions and then crashes.
The app worked well before, I upgraded from android 8 to 9 in the meantime (but I can't tell you that it's the root cause because I didn't use the app for a while)

[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/3054468/Fireflyiii-mobile.txt)

I had a previous log with the value "270,0" instead of ",0"

**Comment by emansih** [comment]
can i know what's your locale?

**Comment by ImLemni** [comment]
My phone was in French. By setting it in English, the app works properly.

**Comment by emansih** [comment]
Thanks for the report, I did not take into account for locales with comma

**Comment by emansih** [comment]
This issue has been fixed in the latest release.
