### ISSUE TITLE
cross platform

### ISSUE THREAD

**Issue by lastlink** [emansih/FireflyMobile#45]
Any thoughts to build this out cross platform. Such as flutter/dart or react native?

**Comment by emansih** [comment]
If by "cross platform" you mean iOS and Android. As of now,no. In the future? The answer is still no.
 
1. I do not have any iOS devices to test on. From what I know, iDevices require a MacBook to deploy and program in. 
2. The amount of man hours poured into this project is way too much for me to port it to another language. Yes Kotlin native exists but the UI toolkit for iOS can't be written in Kotlin
3. The project is build on top of Firefly III APIs anyway, anyone can build on top of it.
