### ISSUE TITLE
Withdrawal Page

### ISSUE THREAD

**Issue by fictitiousexistence** [emansih/FireflyMobile#47]
**Firefly III Server Version:**
4.7.17
**Firefly III Mobile Version:**
1.2.15.1
**Android Version:**  

**Device Information:**  

- BRAND:
- MODEL: 
--------------------------------------

Is there a way to make the Withdrawal page look more like screenshot2 here: https://github.com/emansih/FireflyMobile/blob/master/art/screenshot2.png ?

Where all transactions are shown in a list format. 

Currently the Withdrawal page shows a calendar that takes up most of the screen leaving very little room to see transactions. Also, it is difficult to know the exact date of the transaction you want to view. Having a list view of all transactions for the current month would be great. 

Thanks.

**Comment by emansih** [comment]
I can make a toggle in the settings allowing users to toggle between the views.

**Comment by fictitiousexistence** [comment]
That would be awesome. 

________________________________

**Comment by emansih** [comment]
Will be available in the next release.
