### ISSUE TITLE
No login button on personal access token screen 

### ISSUE THREAD

**Issue by tornoz** [emansih/FireflyMobile#49]
**Firefly III Server Version:** 4.7.17

**Firefly III Mobile Version:** 1.3.0

**Android Version:**  7.1.2

**Device Information:**  

Fairphone 2
with Fairphone Open
Screen resolution : 1080*1920
--------------------------------------

## Expected Behavior
There is a login button under the login with personal access token form

## Current Behavior

There is not and. See screenshot: (I can't scroll either)
![Screenshot_20190508-201656](https://user-images.githubusercontent.com/5543836/57398204-b9727b00-71ce-11e9-921c-6bf78b259d6a.png)
I can't use Oauth because I have the same issue as #48

**Comment by emansih** [comment]
Fixed. Will roll out an update soon. If you have anymore UI issues, feel free to reopen. 

@tornoz P.S. first time seeing a Fairphone in the wild.
