### ISSUE TITLE
New Transaction Page- hard to see options

### ISSUE THREAD

**Issue by fictitiousexistence** [emansih/FireflyMobile#50]
**Firefly III Server Version:**

**Firefly III Mobile Version:**

**Android Version:**  

**Device Information:**  

- BRAND:
- MODEL: 
--------------------------------------

## Steps to Reproduce

Hi!
On the new Transaction page, would it be possible to shorten the space at the top for the description to allow more space to see the options when the keyboard is up?

Thanks!
![Screenshot_20190527-190942](https://user-images.githubusercontent.com/20089581/58441808-0bfad500-80b3-11e9-848d-8dd091d41b87.png)

**Comment by emansih** [comment]
How does this look? It's from my Galaxy S8 with a resolution of 2220 x 1080

![merged](https://user-images.githubusercontent.com/5896415/58482610-40dd5980-8191-11e9-89eb-197f034596f5.png)

**Comment by fictitiousexistence** [comment]
Looks better with any extra room possible. I must have a small screen. Mine is 5.7" 1080x1920 386 ppi

**Comment by emansih** [comment]
Try the latest update.

**Comment by emansih** [comment]
![Screenshot_20190626-230314_Firefly III Mobile](https://user-images.githubusercontent.com/5896415/60191290-ab53e900-9866-11e9-8aaa-aca32e942299.jpg)

@fictitiousexistence I have increased the screen estate. will be available in the next update(v1.3.5)

**Comment by fictitiousexistence** [comment]
THANKS!

Looks like someone else is also making an android firefly companion app.
https://github.com/mconway/firefly-app (https://link.getmailspring.com/link/99EDBAAD-1F5D-4C81-9C58-312CFA2B2066@getmailspring.com/0?redirect=https%3A%2F%2Fgithub.com%2Fmconway%2Ffirefly-app&recipient=cmVwbHkrQUVaSVYzS0JNVkc3S0tHVkZNMkVRTlYzRUM2QjVFVkJOSEhCVlEyVUE0QHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by emansih** [comment]
Yes I know. It's written in the README.md
