### ISSUE TITLE
Cannot login via PAT

### ISSUE THREAD

**Issue by zeridon** [emansih/FireflyMobile#52]
**Firefly III Server Version:**
4.7.17

**Firefly III Mobile Version:**
1.3.3

**Android Version:**  
7.0
**Device Information:**  

- BRAND: Motorola
- MODEL:  Moto G (4)
--------------------------------------

## Expected Behavior
After configuring PAT to be able to see my current data

## Current Behavior
App says "No asset accounts found, do you want to add" If ok -> crash if no-> closes

## Steps to Reproduce
 * Have a FF3 instance with at least 2 pages of accounts.
 * Have used the instance for at least 2 months (mine is at 4 mo usage)
 * Open app
 * Connect via PAT (Oauth is not working for me)

## Nginx logs
That is all i see in the logs
```
==> /var/log/nginx/money-ssl-access.log <==
[11/Jun/2019:12:48:56 +0000] "GET /api/v1/accounts?type=all&page=1 HTTP/1.1" 200 43617 "-" "xyz.hisname.fireflyiii"
[11/Jun/2019:12:48:57 +0000] "GET /api/v1/accounts?type=all&page=2 HTTP/1.1" 200 32818 "-" "xyz.hisname.fireflyiii"
```

**Comment by emansih** [comment]
Ok, just to be clear. What is your url format? 

```
192.168.1.1
192.168.1.1/
192.168.1.1/firefly
192.168.1.1/firefly/
https://192.1688.1.1
https://192.1688.1.1/firefly
https://192.1688.1.1/firefly/
```

**Comment by zeridon** [comment]
https://sub.domain.com

**Comment by zeridon** [comment]
On the first page there are 3 asset accounts listed (as much as i have)

**Comment by emansih** [comment]
I agree that it is more sensible to get only assets accounts.

**Comment by sokai** [comment]
Hey there …

I sadly have the same problem, like @zeridon wrote in the initial description. And I don't know how to fix … – Can someone maybe help? #thx

I get the following Nginx message if I try to login with the app:
`[12/Jul/2019:14:20:49 +0200] "GET /api/v1/accounts?type=asset&page=1 HTTP/2.0" 200 1961 "-" "xyz.hisname.fireflyiii`

I have:
* a fresh installation (under `https://sub.doma.in`) for personal usage (= 1 user)
* configured two (fresh money) accounts
* generated 2 "Personal Access Tokens"

The login (with the "Personal Access Token" in the app) is running very long without success and after some time (feels like 5 minutes or more) I'm on the login screen again.

Thanks and best regards!

**Comment by emansih** [comment]
Thanks for bringing up this issue.
