### ISSUE TITLE
Balance formatting seems to be wrong

### ISSUE THREAD

**Issue by dIELERx** [emansih/FireflyMobile#57]
**Firefly III Server Version:** 4.7.17

**Firefly III Mobile Version:** 1.3.6

**Android Version:**  9

**Device Information:**  

- BRAND: Xiaomi 
- MODEL: Redmi Note 5
--------------------------------------

## Expected Behavior
1. Balance should be €-2,126.00
2. Net Worth should be €5,087.00

## Current Behavior
1. Balance is €-212600.0
2. Net Worth is €0.0

## Steps to Reproduce
Just add a couple of transcations and compare the balance and net worth

**Screenshot from Firefly Webinterface**
![Firefly Webinterface](https://user-images.githubusercontent.com/32218246/61168334-10892900-a54d-11e9-9beb-9a54c0dde81a.png)
**Screenshot from the App**
![App](https://user-images.githubusercontent.com/32218246/61168338-25fe5300-a54d-11e9-9a3a-0e665b9cb4cf.png)

**Comment by corch1988** [comment]
Can confirm this bug.
Firefly Version: 4.7.11
App Version: 1.3.5

**Comment by emansih** [comment]
I have updated the app to use Firefly's new summary API.
