### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by dperezq** [emansih/FireflyMobile#59]
**Firefly III Server Version:**
(4.7.17)
**Firefly III Mobile Version:**
v1.3.6
**Android Version:**  
Android 9
**Device Information:**  

- BRAND: Samsung
- MODEL: Galaxy Note 8
--------------------------------------

## Expected Behavior
Proper login through the application and start using it
## Current Behavior
After follow all the steps indicated in authentication part in the Wiki, I am stuck in the redirection to the application again, in where a red toast is shown with the following information: "trust anchor for certification path not found"
## Steps to Reproduce
1. Select OAUTH method
2. Fill all the fields using URL=https://xxxxx.duckdns.org, ID=50, Secre=XXXX
3. Chrome is opened and click on authorize.
4. Automatic redirection is done to the app and the error message is shown: "java.security.cert.CertPathValidatorException: trust anchor for certification path not found".
5. No login possible.

Currently in the server, there is no error and the logs that can be seen are the expected ones:

```
firefly_iii@intel    | 10.255.0.2 - - [16/Jul/2019:19:26:43 +0000] "POST /oauth/authorize HTTP/1.0" 302 2200 "-" "Mozilla/5.0 (Linux; Android 9; SM-N950F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.143 Mobile Safari/537.36"

firefly_iii@intel    | 10.255.0.2 - - [16/Jul/2019:19:30:28 +0000] "GET /oauth/authorize?client_id=50&redirect_uri=http://empty&scope=&response_type=code&state= HTTP/1.0" 200 3103 "-" "Mozilla/5.0 (Linux; Android 9; SM-N950F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.143 Mobile Safari/537.36"
```

I have now tested using the last version of the application, but the result was the same using the previous one. I have also tried using the redirection to https://empty with no luck.

Looking at the exception, it seems to be something related to the certificate. I am using let's encrypt for the certificate creation and the firefly server is working properly under https.

**Comment by emansih** [comment]
Are you using self signed cert?

**Comment by dperezq** [comment]
I was using one at the beginning and hosted in localhost, but then after realise that the cert was the issue, I created a certificate using let’s encrypt for my site and make it public.

**Comment by emansih** [comment]
This may help with the issue you are facing. https://github.com/emansih/FireflyMobile/issues/53#issuecomment-510961230

**Comment by dperezq** [comment]
> This may help with the issue you are facing. [#53 (comment)](https://github.com/emansih/FireflyMobile/issues/53#issuecomment-510961230)

That's seems to be for self-signed certificate. Mine is based on Let's encrypt and from chrome it says secure and "your certificate is valid" in the server. I only added to the nginx reverse proxy to get https properly. 

By other hand, I am not root in my phone, so I cannot add system certificates. I could try to load the Let's encrypt certificate in the user certificate library in the mobile phone.

**Comment by emansih** [comment]
I'm using a Galaxy S8 on Android 9 and I can't reproduce your bug.

**Comment by dperezq** [comment]
Last comment you did open my eyes. I have researched about this and the issue is that let's encrypt does not use an intermediate certificate, so in Android, it's not trusted. I detail the steps followed to make it work. Note that I use let's encrypt for the certificate and nginx for the server in docker.

You can check the chain of the certificate with the following command:
`openssl s_client -connect XXXX.duckdns.org:443`
With that command, at the end you will see something like this:
```
Certificate chain
 0 s:/CN=XXX.duckdns.org
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
```
This can also be tested with the following site: https://www.ssllabs.com/ssltest/index.html
And with the result: This server's certificate chain is incomplete. Grade capped to B.

which means, that the certificate will not work on some devices due the previous comment.
After find the main issue, how it is solved?
1.- Download the intermediate certificate
`nuc@nuc:~$ curl --output intermediate.crt --silent https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem
`
2.- Concatenate with your current certificate
`nuc@nuc:~$ cat cert.pem intermediate.crt > cert_chained.crt
`
3.- Add it to your nginx conf file:
`  ssl_certificate     cert_chained.crt;
`

After that steps, you can test with the command and the beginning and the result would be:
```
Certificate chain
 0 s:/CN=XXXX.duckdns.org
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
```

Thanks for the support

**Comment by emansih** [comment]
It's probably a wrong config on your end since I'm using Let's Encrypt on my domain too(www.hisname.xyz). https://www.ssllabs.com/ssltest/analyze.html?d=www.hisname.xyz&hideResults=on&latest
