### ISSUE TITLE
"Expenses" lists transactions of all types

### ISSUE THREAD

**Issue by Ditti4** [emansih/FireflyMobile#6]
**Firefly III Server Version:** 4.7.7

**Firefly III Mobile Version:** 0.06

**Android Version:**  6.0.1

**Device Information:**  

- BRAND: Xiaomi
- MODEL: Redmi 3s Prime
--------------------------------------

## Expected Behavior
The "Expenses" view should list expenses and only expenses.

## Current Behavior
Currently the view also lists deposits and transfers as well as expenses including some amusing coloring issues (sometimes deposits and transfers are red, sometimes they're black).

## Steps to Reproduce
Go to "Transactions" -> "Expenses". I don't feel too comfortable adding a screenshot here but I think it should be easy enough to reproduce.

**Comment by emansih** [comment]
I'm not sure about this bug. Here is a screenshot using the data from https://demo.firefly-iii.org
![screenshot](https://user-images.githubusercontent.com/5896415/47273001-063e8d80-d5c0-11e8-872f-b6b7fd006270.jpg)

**Comment by Ditti4** [comment]
I just checked with the demo and it behaves the same way. Make sure to add a deposit or transfer, then it'll look like this:

![image](https://user-images.githubusercontent.com/1223152/47277529-844f6400-d5c1-11e8-850b-3e756ef7e063.png)

**Comment by emansih** [comment]
Found a bug in Firefly Server Edition. When interacting with `https://demo.firefly-iii.org/api/v1/transactions?type=expenses`

```
{
            "type": "transactions",
            "id": "1356",
            "attributes": {
                "updated_at": "2018-10-23T12:00:09+02:00",
                "created_at": "2018-10-23T12:00:09+02:00",
                "description": "Saving money for September",
                "transaction_description": null,
                "date": "2018-09-28",
                "type": "Transfer",
                "identifier": 0,
                "journal_id": 669,
                "reconciled": false,
                "amount": 140,
                "currency_id": 1,
                "currency_code": "EUR",
                "currency_symbol": "€",
                "currency_dp": 2,
                "foreign_amount": null,
                "foreign_currency_id": null,
                "foreign_currency_code": null,
                "foreign_currency_symbol": null,
                "foreign_currency_dp": null,
                "bill_id": null,
                "bill_name": null,
                "category_id": null,
                "category_name": null,
                "budget_id": null,
                "budget_name": null,
                "notes": null,
                "source_id": 1,
                "source_name": "Checking Account",
                "source_iban": "NL11XOLA6707795988",
                "source_type": "Asset account",
                "destination_id": 2,
                "destination_name": "Savings Account",
                "destination_iban": "NL96DZCO4665940223",
                "destination_type": "Asset account"
            },
            "links": {
                "0": {
                    "rel": "self",
                    "uri": "/transactions/1356"
                },
                "self": "https://demo.firefly-iii.org/api/v1/transactions/1356"
            }
        }
```
Transaction ID 1356 shows up. However, if i were to call https://demo.firefly-iii.org/api/v1/transactions?type=expense`, Transaction ID 1356 doesn't show up. I will report this bug upstream.
