### ISSUE TITLE
Allow comma as the decimal separator

### ISSUE THREAD

**Issue by mastacheata** [emansih/FireflyMobile#61]
**Firefly III Server Version:**
 4.7.17.3
**Firefly III Mobile Version:**
 1.3.6
**Android Version:**  
9
**Device Information:**  

- BRAND: Google 
- MODEL: Pixel 3
--------------------------------------

## Expected Behavior
When entering a decimal separated by decimal-comma it should save the transaction
## Current Behavior
It says I need to first fill out the amount field before saving
## Steps to Reproduce
Use decimal-comma to separate integer and fractional part of a decimal. Then try to save the transaction or balance. (Works just fine if I use the full-stop instead, but that's reserved for grouping numbers in my mind)

![Screenshot_20190723-233350](https://user-images.githubusercontent.com/716261/61749279-a2d9ca00-ada2-11e9-9fe0-c339dbea29a7.png)

**Comment by emansih** [comment]
At first glance, it looks to be a bug in Firefly III

**Comment by corch1988** [comment]
Firefly III does accept a comma as seperator on the server.
Its how a number is formatted in different countries.
See:
https://language-boutique.com/lost-in-translation-full-reader/writing-numbers-points-or-commas.html

**Comment by emansih** [comment]
This is a limitation in the API. https://github.com/firefly-iii/firefly-iii/issues/2350

**Comment by corch1988** [comment]
I did not know that the API just works with dots.

Isn't it possible to simply replace the comma with a dot if the language of the app is set to another language than english?
Or maybe a setting where it is possible to toggle this behavior?
Or replace the comma in general before the request?

**Comment by mastacheata** [comment]
I'd very much favor the replace comma by dot before request.  

Otherwise you should separate the language and the localce from each other.  
I prefer having the English language labels and descriptions as German translations are in most cases of inferior quality unless the original app/software author is German. But I'd also like to keep my German locale (use the € as my currency, the decimal ISO system for numbers and units, the comma as the decimal separator and the dot as grouping indicator etc.) 

This shouldn't be too much of a problem anyway since you don't allow to group numbers in the input field (noone in their right mind would do that, but if they do than it could be confusing to the computer when deciding whether the dot or the comma is the decimal separator)

Another option: Just send the cents (at least in currencies with only two categories of funds - dollars and cents, euros and cents etc. that would be an easy way to get around the decimal separator thingie)

**Comment by JC5** [comment]
You can try it with quotes, like so: `"12,34"`. I don't know from the top of my head if Firefly III will process it correctly. I believe it won't however.


 However, like I said in the other issue, if you send numbers with commas instead of dots you break the JSON format. JSON doesn't accept comma's like that. They MUST be dots.

**Comment by corch1988** [comment]
So a replacement of the commas like
`transaction_amount_edittext.getString().replace(',', '.')`
before the request would work and would not clash with the api right?

**Comment by emansih** [comment]
@corch1988 yes the request works since validation is done server side. but what's the point though? 

@JC5 yea, quotes don't work 

```
{
  "message": "The given data was invalid.",
  "errors": {
    "transactions.0.amount": [
      "The transactions.0.amount must be a number.",
      "transactions.0.amount must be larger than zero."
    ]
  }
}
```

**Comment by corch1988** [comment]
The point is to don't confuse users from a different country than the US where the default separator is not a dot but a comma.

**Comment by JC5** [comment]
Since it's an API that isn't user-facing the requirements are simple: is a number. For data, this is always a dot. Also the US standard but alas, those Yankees defined the standard so there you go.

Make sure you convert and it should work just fine :)

**Comment by emansih** [comment]
> The point is to not confuse users from a different country than the US where the default separator is not a dot but a comma.

I'm not from the US but I use dot :(

**Comment by corch1988** [comment]
With`transaction_amount_edittext.getString().replace(',', '.')` BOTH can be possible. Dots AND commas.

**Comment by corch1988** [comment]
Thank you 👍

**Comment by emansih** [comment]
Fix in latest pre-release.
