### ISSUE TITLE
Custom intellij android project icon is used as default icon in app menu

### ISSUE THREAD

**Issue by agilob** [emansih/FireflyMobile#63]
**Firefly III Mobile Version:** 1.3.6 from fdroid

**Android Version:**  7.1.1

**Device Information:**  

- BRAND: motorola
- MODEL: g4
--------------------------------------

## Expected Behavior
Would prefer to see the same icon of the application as in FDroid app list.

## Current Behavior
Standard intellij(?) android project icon is visible.
![Screenshot_20190804-200404](https://user-images.githubusercontent.com/2544251/62428012-badf1100-b6f3-11e9-950e-a47e6e3d522c.png)

**Comment by emansih** [comment]
That's really strange. I just downloaded the APK and I don't  have the default Android icon. Could you verify the binary integrity?

**Comment by emansih** [comment]
The SHA256 for the APK I downloaded from F-Droid is `DE84805F64D1F71E508D40C5D3B254820E10ABB842B921A4CBAF56E5FA81833C` and it is signed 
with the following key `E7:65:BA:AE:47:B7:69:1D:05:5B:40:8C:19:7D:5A:8A:E9:0E:B7:64:42:66:7E:28:6E:4F:01:CF:6F:6A:AC:9F`

```
daniel@XiaoMaoMao:~ $ keytool -printcert -jarfile /home/daniel/xyz.hisname.fireflyiii_44.apk
Signer #1:

Signature:

Owner: CN=FDroid, OU=FDroid, O=fdroid.org, L=ORG, ST=ORG, C=UK
Issuer: CN=FDroid, OU=FDroid, O=fdroid.org, L=ORG, ST=ORG, C=UK
Serial number: b3ae32d
Valid from: Tue Nov 27 14:18:35 SGT 2018 until: Sat Apr 14 14:18:35 SGT 2046
Certificate fingerprints:
         SHA1: BE:6B:A9:B0:C2:3A:F2:39:62:3F:FE:95:14:E4:04:6C:53:BB:7C:C2
         SHA256: E7:65:BA:AE:47:B7:69:1D:05:5B:40:8C:19:7D:5A:8A:E9:0E:B7:64:42:66:7E:28:6E:4F:01:CF:6F:6A:AC:9F
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 3

Extensions:

#1: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: B5 5E EE 72 F7 C6 C6 F7   56 7A 43 2B 99 AB 35 13  .^.r....VzC+..5.
0010: D6 92 AD 32                                        ...2
]
]
```

**Comment by dIELERx** [comment]
I can confirm that, I also see the default icon.
I started using this App with Version 1.3.5 from F-Droid and since that, I did not see any custom icon... just the default one. To be honest, I didnt know that there was a custom Icon.

**Firefly III Server Version**: 4.7.17
**Firefly III Mobile Version**: 1.3.6
**Android Version**: 9

**Device Information**:
    BRAND: Xiaomi
    MODEL: Redmi Note 5

**Comment by agilob** [comment]
It's because phones with different screen resolution will pick different file to show.
The default icon is available in the repo, eg. here https://github.com/emansih/FireflyMobile/blob/master/app/src/main/res/mipmap-hdpi/ic_launcher_round.png and here https://github.com/emansih/FireflyMobile/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png

**Comment by emansih** [comment]
Yes, but the icon is set here. https://github.com/emansih/FireflyMobile/blob/master/app/src/main/AndroidManifest.xml#L21

**Comment by emansih** [comment]
Oh, maybe it's because of round icon
