### ISSUE TITLE
App crashes a few seconds after starting it.

### ISSUE THREAD

**Issue by spaetz** [emansih/FireflyMobile#65]
**Firefly III Server Version:**
4.8.0.2
**Firefly III Mobile Version:**
1.3.6
**Android Version:**  
7.1.2
**Device Information:**  
BQ tenshi
--------------------------------------

I was able to pair my account via oauth. But now:

Firefly mobile starts and after a few seconds crashes. Stacktrace is attached.
[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/3519380/Fireflyiii-mobile.txt)

**Comment by emansih** [comment]
https://github.com/emansih/FireflyMobile/issues/64#issuecomment-520145934

**Comment by spaetz** [comment]
OK, thanks for letting me know. I will patiently wait for updates :-)
