### ISSUE TITLE
Crash when setting up personal access token

### ISSUE THREAD

**Issue by Tavlor** [emansih/FireflyMobile#66]
**Firefly III Server Version:**
4.8.0.2
**Firefly III Mobile Version:**
1.3.6
**Android Version:**  
6.0.1
**Device Information:**  

- BRAND: Samsung
- MODEL: Galaxy S5
--------------------------------------

## Expected Behavior
After entering the URL and PAT, should connect to firefly or give a message if the URL or PAT are wrong
## Current Behavior
crashes immediately 
## Steps to Reproduce
URL: http://192.168.0.1234/ (if I leave off the backslash it works)
PAT: newline at the end (getting rid of the newline works)
I'm not sure which of these actually causes the issue.

REPORT_ID=5fec00fc-e09c-4ba5-b00b-18793789ab1e
APP_VERSION_NAME=1.3.6
PHONE_MODEL=SM-G900T
BRAND=samsung
PRODUCT=kltetmo
ANDROID_VERSION=6.0.1
BUILD_CONFIG=
STACK_TRACE=java.lang.IllegalArgumentException: Unexpected char 0x0a at 1079 in Authorization value: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjNmYzAyOTNhNjhhZTY3M2QzNzQxNjc0MWQwNDQxYWY1Mjc5NTMzM2RjMGYwYWRmMjY2MTI3Mjk0Y2M2ZTk3YTg4M2U1Y2FhNzk5MGU0MDgwIn0.eyJhdWQiOiIxMyIsImp0aSI6IjNmYzAyOTNhNjhhZTY3M2QzNzQxNjc0MWQwNDQxYWY1Mjc5NTMzM2RjMGYwYWRmMjY2MTI3Mjk0Y2M2ZTk3YTg4M2U1Y2FhNzk5MGU0MDgwIiwiaWF0IjoxNTY3NzcwMTkxLCJuYmYiOjE1Njc3NzAxOTEsImV4cCI6MTU5OTM5MjU5MSwic3ViIjoiMSIsInNjb3BlcyI6W119.ghCwqKl377CIeYkjJqMP4biuGcsZLZLFsRoWibC1Ng5SoKTC2915cDy3f-2y9OT3tluAM-ClvxX1-oDq9HP5_lbT3iUqXOe6zTftTi68VgjT89250aPOUyq4ri7tY001LDGVrGn-Gy_xn9Ex0efyV9clPCU-4HnTpHelQ19xgwy_-tSGBPQG7TgQ0ThzD41hKnp8-SDR5Z5xQEkw1C2xy4b_ZSvYxnfHIwTdVbhC__v5iNX1YqCRfcPj6ulQIOUtVdBvyrQW5DJeqj66ToaJjLtplO0Rx5Lbeyd5n6v173hMynTvI33s5fEacjleFNEfbznS3nhlCKwLV8tojvlBeigYwGYlJ6IX7lq5Vx3cGz4Nl_muKSTsSnQTO2qUqp4LpLxf0pnmv6HYk6XtGD6h3GSGfj0XKl8JDE-5-DDaXh1_MJcb3Euvo3eKC24lDUUCl9XX_PBPO1SjVZayeedgWy1IbyvDTyY3pogf2DxRRDtvARG2BiHQ9fbyaRVKMY-APqWbzyNRwqn_Yj05Vfh6V6VTZx_fR_hzGLDly7aKfPSD3MyAeUeClUg29a2w4m4Pb6iGNgBdQAK8xg3q45W1A5rZT55EbmQgHZvUjVVGM4iWJFREcasMUp3oE3dfb3MnUxccutjKVfZN4JCWgEBskEAioD4D0yHcJbaB_sb-LPk

	at f.z.a(Headers.java:33)
	at f.z$a.c(Headers.java:2)
	at f.J$a.b(Request.java:7)
	at xyz.hisname.fireflyiii.util.c.c.a(HeaderInterceptor.kt:3)
	at f.a.c.h.a(RealInterceptorChain.java:11)
	at f.a.c.h.a(RealInterceptorChain.java:2)
	at f.I.a(RealCall.java:28)
	at f.I$a.b(RealCall.java:2)
	at f.a.b.run(NamedRunnable.java:3)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

LOGCAT=09-06 06:44:39.644 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 1
09-06 06:44:39.654 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:39.824 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 0
09-06 06:44:39.834 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 1
09-06 06:44:39.834 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:40.014 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 0
09-06 06:44:40.014 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 1
09-06 06:44:40.024 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:40.734 D/ViewRootImpl(20869): ViewPostImeInputStage processPointer 0
09-06 06:44:40.934 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:41.274 W/ClipboardExManager(20869): hasData : 2, -1, null
09-06 06:44:41.314 D/ViewRootImpl(20869): #1 mView = android.widget.PopupWindow$PopupDecorView{d97c6be V.E...... ......I. 0,0-0,0}
09-06 06:44:41.374 D/ViewRootImpl(20869): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
09-06 06:44:41.384 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:41.454 D/TextView(20869): setTypeface with style : 0
09-06 06:44:41.464 D/TextView(20869): setTypeface with style : 0
09-06 06:44:41.474 D/ViewRootImpl(20869): #1 mView = android.widget.PopupWindow$PopupDecorView{13ed621 V.E...... ......I. 0,0-0,0}
09-06 06:44:41.524 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:41.524 D/ViewRootImpl(20869): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
09-06 06:44:41.574 D/ViewRootImpl(20869): ViewPostImeInputStage processPointer 1
09-06 06:44:41.584 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:42.094 D/ViewRootImpl(20869): ViewPostImeInputStage processPointer 0
09-06 06:44:42.174 D/ViewRootImpl(20869): ViewPostImeInputStage processPointer 1
09-06 06:44:42.174 W/ClipboardExManager(20869): getData : 2, -1, null
09-06 06:44:42.184 D/ViewRootImpl(20869): #3 mView = null
09-06 06:44:42.194 D/ViewRootImpl(20869): #3 mView = null
09-06 06:44:42.204 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:43.074 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 0
09-06 06:44:43.074 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 1
09-06 06:44:43.094 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:43.264 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 0
09-06 06:44:43.264 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 1
09-06 06:44:43.274 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:43.444 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 0
09-06 06:44:43.444 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 1
09-06 06:44:43.454 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:43.644 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 0
09-06 06:44:43.644 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 1
09-06 06:44:43.654 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:43.834 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 0
09-06 06:44:43.834 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 1
09-06 06:44:43.834 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:46.324 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 0
09-06 06:44:46.324 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 1
09-06 06:44:46.474 D/ViewRootImpl(20869): MSG_RESIZED: ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
09-06 06:44:46.494 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:44:46.494 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
--------- beginning of system
09-06 06:44:50.624 V/ActivityThread(20869): updateVisibility : ActivityRecord{5cda464 token=android.os.BinderProxy@737a5ae {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.onboarding.OnboardingActivity}} show : false
09-06 06:45:00.104 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:45:00.104 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:45:00.154 I/Timeline(20869): Timeline: Activity_idle id: android.os.BinderProxy@737a5ae time:1740974
09-06 06:45:00.234 D/ViewRootImpl(20869): MSG_RESIZED: ci=Rect(0, 72 - 0, 930) vi=Rect(0, 72 - 0, 930) or=1
09-06 06:45:00.604 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:45:00.604 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:45:00.964 D/ViewRootImpl(20869): ViewPostImeInputStage processPointer 0
09-06 06:45:01.154 D/ViewRootImpl(20869): ViewPostImeInputStage processPointer 1
09-06 06:45:01.194 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:45:01.204 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:45:01.884 D/ViewRootImpl(20869): ViewPostImeInputStage processPointer 0
09-06 06:45:02.074 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:45:02.404 W/ClipboardExManager(20869): hasData : 2, -1, null
09-06 06:45:02.544 D/TextView(20869): setTypeface with style : 0
09-06 06:45:02.554 D/TextView(20869): setTypeface with style : 0
09-06 06:45:02.554 D/ViewRootImpl(20869): #1 mView = android.widget.PopupWindow$PopupDecorView{78246d8 V.E...... ......I. 0,0-0,0}
09-06 06:45:02.644 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:45:02.664 D/ViewRootImpl(20869): MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
09-06 06:45:02.744 D/ViewRootImpl(20869): ViewPostImeInputStage processPointer 1
09-06 06:45:02.764 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:45:03.944 D/ViewRootImpl(20869): ViewPostImeInputStage processPointer 0
09-06 06:45:04.004 D/ViewRootImpl(20869): ViewPostImeInputStage processPointer 1
09-06 06:45:04.004 W/ClipboardExManager(20869): getData : 2, -1, null
09-06 06:45:04.044 D/ViewRootImpl(20869): #3 mView = null
09-06 06:45:04.054 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:45:04.904 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 0
09-06 06:45:04.914 D/ViewRootImpl(20869): ViewPostImeInputStage processKey 1
09-06 06:45:05.034 D/ViewRootImpl(20869): MSG_RESIZED: ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
09-06 06:45:05.074 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:45:05.084 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:45:05.084 W/DisplayListCanvas(20869): DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
09-06 06:45:05.944 D/ViewRootImpl(20869): ViewPostImeInputStage processPointer 0
09-06 06:45:06.004 D/ViewRootImpl(20869): ViewPostImeInputStage processPointer 1
09-06 06:45:06.574 W/        (20869): Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
09-06 06:45:06.574 W/art     (20869): Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
09-06 06:45:06.724 I/Choreographer(20869): Skipped 42 frames!  The application may be doing too much work on its main thread.
09-06 06:45:06.844 E/ACRA    (20869): ACRA caught a IllegalArgumentException for xyz.hisname.fireflyiii
09-06 06:45:06.844 E/ACRA    (20869): java.lang.IllegalArgumentException: Unexpected char 0x0a at 1079 in Authorization value: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjNmYzAyOTNhNjhhZTY3M2QzNzQxNjc0MWQwNDQxYWY1Mjc5NTMzM2RjMGYwYWRmMjY2MTI3Mjk0Y2M2ZTk3YTg4M2U1Y2FhNzk5MGU0MDgwIn0.eyJhdWQiOiIxMyIsImp0aSI6IjNmYzAyOTNhNjhhZTY3M2QzNzQxNjc0MWQwNDQxYWY1Mjc5NTMzM2RjMGYwYWRmMjY2MTI3Mjk0Y2M2ZTk3YTg4M2U1Y2FhNzk5MGU0MDgwIiwiaWF0IjoxNTY3NzcwMTkxLCJuYmYiOjE1Njc3NzAxOTEsImV4cCI6MTU5OTM5MjU5MSwic3ViIjoiMSIsInNjb3BlcyI6W119.ghCwqKl377CIeYkjJqMP4biuGcsZLZLFsRoWibC1Ng5SoKTC2915cDy3f-2y9OT3tluAM-ClvxX1-oDq9HP5_lbT3iUqXOe6zTftTi68VgjT89250aPOUyq4ri7tY001LDGVrGn-Gy_xn9Ex0efyV9clPCU-4HnTpHelQ19xgwy_-tSGBPQG7TgQ0ThzD41hKnp8-SDR5Z5xQEkw1C2xy4b_ZSvYxnfHIwTdVbhC__v5iNX1YqCRfcPj6ulQIOUtVdBvyrQW5DJeqj66ToaJjLtplO0Rx5Lbeyd5n6v173hMynTvI33s5fEacjleFNEfbznS3nhlCKwLV8tojvlBeigYwGYlJ6IX7lq5Vx3cGz4Nl_muKSTsSnQTO2qUqp4LpLxf0pnmv6HYk6XtGD6h3GSGfj0XKl8JDE-5-DDaXh1_MJcb3Euvo3eKC24lDUUCl9XX_PBPO1SjVZayeedgWy1IbyvDTyY3pogf2DxRRDtvARG2BiHQ9fbyaRVKMY-APqWbzyNRwqn_Yj05Vfh6V6VTZx_fR_hzGLDly7aKfPSD3MyAeUeClUg29a2w4m4Pb6iGNgBdQAK8xg3q45W1A5rZT55EbmQgHZvUjVVGM4iWJFREcasMUp3oE3dfb3MnUxccutjKVfZN4JCWgEBskEAioD4D0yHcJbaB_sb-LPk
09-06 06:45:06.844 E/ACRA    (20869): 
09-06 06:45:06.844 E/ACRA    (20869): 	at f.z.a(Headers.java:33)
09-06 06:45:06.844 E/ACRA    (20869): 	at f.z$a.c(Headers.java:2)
09-06 06:45:06.844 E/ACRA    (20869): 	at f.J$a.b(Request.java:7)
09-06 06:45:06.844 E/ACRA    (20869): 	at xyz.hisname.fireflyiii.util.c.c.a(HeaderInterceptor.kt:3)
09-06 06:45:06.844 E/ACRA    (20869): 	at f.a.c.h.a(RealInterceptorChain.java:11)
09-06 06:45:06.844 E/ACRA    (20869): 	at f.a.c.h.a(RealInterceptorChain.java:2)
09-06 06:45:06.844 E/ACRA    (20869): 	at f.I.a(RealCall.java:28)
09-06 06:45:06.844 E/ACRA    (20869): 	at f.I$a.b(RealCall.java:2)
09-06 06:45:06.844 E/ACRA    (20869): 	at f.a.b.run(NamedRunnable.java:3)
09-06 06:45:06.844 E/ACRA    (20869): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-06 06:45:06.844 E/ACRA    (20869): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-06 06:45:06.844 E/ACRA    (20869): 	at java.lang.Thread.run(Thread.java:818)
IS_SILENT=false
USER_CRASH_DATE=2019-09-06T06:45:06.878-05:00

**Comment by emansih** [comment]
Hello, sorry for such a late reply. It seems that there is a new line(0x0a) in your Bearer Token. Can I know what browser are you using?

**Comment by Tavlor** [comment]
Firefox mobile
