### ISSUE TITLE
personal access token: transactions are missing and app crashes shortly after setting up

### ISSUE THREAD

**Issue by Tavlor** [emansih/FireflyMobile#67]
**Firefly III Server Version:**
4.8.0.2
**Firefly III Mobile Version:**
1.3.6
**Android Version:**  
6.0.1
**Device Information:**  

- BRAND: Samsung
- MODEL: Galaxy S5
--------------------------------------

## Expected Behavior
App displays the same data as the webpage, and keeps functioning 
## Current Behavior
After setting up access to my firefly instance using a personal access token, the app displays some information (budget amount) but doesn't show any transactions. After about a minute the app crashes. If I open it again, it crashes immediately, until I clear the app's data.
## Steps to Reproduce
- set up access via personal access token
- wait a minute

REPORT_ID=a6cc4c71-3fca-4c53-84f6-ec419ff49f1a
APP_VERSION_NAME=1.3.6
PHONE_MODEL=SM-G900T
BRAND=samsung
PRODUCT=kltetmo
ANDROID_VERSION=6.0.1
BUILD_CONFIG=
STACK_TRACE=java.lang.IllegalArgumentException: Parameter specified as non-null is null: method d.f.b.j.b, parameter description
	at xyz.hisname.fireflyiii.repository.models.transaction.TransactionAttributes.<init>(TransactionAttributes.kt)
	at xyz.hisname.fireflyiii.data.local.dao.ba.a(TransactionDataDao_Impl.java:326)
	at xyz.hisname.fireflyiii.b.k.C.a(TransactionRepository.kt:41)
	at xyz.hisname.fireflyiii.b.k.A.c(TransactionRepository.kt)
	at d.c.b.a.a.a(ContinuationImpl.kt:3)
	at kotlinx.coroutines.Ea.b(ResumeMode.kt:15)
	at kotlinx.coroutines.internal.z.a(Scopes.kt:4)
	at kotlinx.coroutines.va.a(JobSupport.kt:54)
	at kotlinx.coroutines.va.b(JobSupport.kt:6)
	at kotlinx.coroutines.va.a(JobSupport.kt:95)
	at kotlinx.coroutines.va.b(JobSupport.kt:38)
	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
	at d.c.b.a.a.a(ContinuationImpl.kt:10)
	at kotlinx.coroutines.Ea.b(ResumeMode.kt:15)
	at kotlinx.coroutines.internal.z.a(Scopes.kt:4)
	at kotlinx.coroutines.va.a(JobSupport.kt:54)
	at kotlinx.coroutines.va.b(JobSupport.kt:6)
	at kotlinx.coroutines.va.a(JobSupport.kt:95)
	at kotlinx.coroutines.va.b(JobSupport.kt:38)
	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
	at d.c.b.a.a.a(ContinuationImpl.kt:10)
	at kotlinx.coroutines.X.run(Dispatched.kt:15)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:31)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:9)

LOGCAT=09-06 06:57:50.421 V/ViewPager(27170): Intercept done!
09-06 06:57:50.431 E/RecyclerView(27170): No adapter attached; skipping layout
09-06 06:57:50.761 E/RecyclerView(27170): No adapter attached; skipping layout
09-06 06:57:51.431 D/ViewRootImpl(27170): ViewPostImeInputStage processPointer 0
09-06 06:57:51.431 V/ViewPager(27170): Down at 507.0,356.0 mIsBeingDragged=falsemIsUnableToDrag=false
09-06 06:57:51.451 V/ViewPager(27170): Moved x to 507.0,354.5 diff=0.0,1.5
09-06 06:57:51.471 V/ViewPager(27170): Moved x to 507.0,355.0 diff=0.0,1.0
09-06 06:57:51.481 V/ViewPager(27170): Moved x to 507.0,355.0 diff=0.0,1.0
09-06 06:57:51.481 D/ViewRootImpl(27170): ViewPostImeInputStage processPointer 1
09-06 06:57:51.481 V/ViewPager(27170): Intercept done!
09-06 06:57:51.501 E/RecyclerView(27170): No adapter attached; skipping layout
09-06 06:57:51.871 E/RecyclerView(27170): No adapter attached; skipping layout
09-06 06:57:51.911 D/ViewRootImpl(27170): ViewPostImeInputStage processPointer 0
09-06 06:57:51.911 V/ViewPager(27170): Down at 367.0,349.0 mIsBeingDragged=falsemIsUnableToDrag=false
09-06 06:57:51.931 V/ViewPager(27170): Moved x to 365.4587,349.0 diff=1.5412903,0.0
09-06 06:57:51.951 V/ViewPager(27170): Moved x to 363.89008,349.0 diff=3.1099243,0.0
09-06 06:57:51.951 D/ViewRootImpl(27170): ViewPostImeInputStage processPointer 1
09-06 06:57:51.951 V/ViewPager(27170): Intercept done!
09-06 06:57:51.971 E/RecyclerView(27170): No adapter attached; skipping layout
09-06 06:57:52.231 E/RecyclerView(27170): No adapter attached; skipping layout
09-06 06:57:52.431 D/ViewRootImpl(27170): ViewPostImeInputStage processPointer 0
09-06 06:57:52.431 V/ViewPager(27170): Down at 273.0,352.0 mIsBeingDragged=falsemIsUnableToDrag=false
09-06 06:57:52.451 V/ViewPager(27170): Moved x to 273.0,352.0 diff=0.0,0.0
09-06 06:57:52.461 V/ViewPager(27170): Moved x to 274.0,352.0 diff=1.0,0.0
09-06 06:57:52.481 V/ViewPager(27170): Moved x to 274.531,352.531 diff=1.5310059,0.53100586
09-06 06:57:52.491 V/ViewPager(27170): Moved x to 275.0,353.0 diff=2.0,1.0
09-06 06:57:52.491 D/ViewRootImpl(27170): ViewPostImeInputStage processPointer 1
09-06 06:57:52.491 V/ViewPager(27170): Intercept done!
09-06 06:57:52.501 E/RecyclerView(27170): No adapter attached; skipping layout
09-06 06:57:52.791 E/RecyclerView(27170): No adapter attached; skipping layout
09-06 06:57:52.881 D/ViewRootImpl(27170): ViewPostImeInputStage processPointer 0
09-06 06:57:52.881 V/ViewPager(27170): Down at 138.0,347.0 mIsBeingDragged=falsemIsUnableToDrag=false
09-06 06:57:52.941 V/ViewPager(27170): Moved x to 138.0,347.0 diff=0.0,0.0
09-06 06:57:52.951 D/ViewRootImpl(27170): ViewPostImeInputStage processPointer 1
09-06 06:57:52.951 V/ViewPager(27170): Intercept done!
09-06 06:57:52.961 E/RecyclerView(27170): No adapter attached; skipping layout
09-06 06:57:53.231 D/ViewRootImpl(27170): ViewPostImeInputStage processPointer 0
09-06 06:57:53.311 E/RecyclerView(27170): No adapter attached; skipping layout
09-06 06:57:53.321 D/ViewRootImpl(27170): ViewPostImeInputStage processPointer 1
09-06 06:57:54.921 D/ViewRootImpl(27170): ViewPostImeInputStage processPointer 0
09-06 06:57:55.001 D/ViewRootImpl(27170): ViewPostImeInputStage processPointer 1
09-06 06:57:55.051 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.051 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.051 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.051 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.051 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.051 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.061 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.061 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.061 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.071 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.071 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.071 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.071 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.071 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.071 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.071 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.071 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.071 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.071 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.071 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.081 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.081 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.081 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.081 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.081 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.091 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.091 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.101 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.101 D/TextView(27170): setTypeface with style : 0
09-06 06:57:55.161 E/RecyclerView(27170): No adapter attached; skipping layout
09-06 06:57:55.371 W/        (27170): Unable to open '/system/framework/com.qti.location.sdk.jar': No such file or directory
09-06 06:57:55.371 W/art     (27170): Failed to open zip archive '/system/framework/com.qti.location.sdk.jar': I/O Error
09-06 06:57:55.381 E/ACRA    (27170): ACRA caught a IllegalArgumentException for xyz.hisname.fireflyiii
09-06 06:57:55.381 E/ACRA    (27170): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method d.f.b.j.b, parameter description
09-06 06:57:55.381 E/ACRA    (27170): 	at xyz.hisname.fireflyiii.repository.models.transaction.TransactionAttributes.<init>(TransactionAttributes.kt)
09-06 06:57:55.381 E/ACRA    (27170): 	at xyz.hisname.fireflyiii.data.local.dao.ba.a(TransactionDataDao_Impl.java:326)
09-06 06:57:55.381 E/ACRA    (27170): 	at xyz.hisname.fireflyiii.b.k.C.a(TransactionRepository.kt:41)
09-06 06:57:55.381 E/ACRA    (27170): 	at xyz.hisname.fireflyiii.b.k.A.c(TransactionRepository.kt)
09-06 06:57:55.381 E/ACRA    (27170): 	at d.c.b.a.a.a(ContinuationImpl.kt:3)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.Ea.b(ResumeMode.kt:15)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.internal.z.a(Scopes.kt:4)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.va.a(JobSupport.kt:54)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.va.b(JobSupport.kt:6)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.va.a(JobSupport.kt:95)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.va.b(JobSupport.kt:38)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
09-06 06:57:55.381 E/ACRA    (27170): 	at d.c.b.a.a.a(ContinuationImpl.kt:10)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.Ea.b(ResumeMode.kt:15)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.internal.z.a(Scopes.kt:4)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.va.a(JobSupport.kt:54)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.va.b(JobSupport.kt:6)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.va.a(JobSupport.kt:95)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.va.b(JobSupport.kt:38)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
09-06 06:57:55.381 E/ACRA    (27170): 	at d.c.b.a.a.a(ContinuationImpl.kt:10)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.X.run(Dispatched.kt:15)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:31)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:4)
09-06 06:57:55.381 E/ACRA    (27170): 	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:9)
IS_SILENT=false
USER_CRASH_DATE=2019-09-06T06:57:55.431-05:00

**Comment by emansih** [comment]
Same as #64. Transaction API has gone through an overhaul. I'm working on it on some nights. Please give me some time.
