### ISSUE TITLE
Source and destination account have same content for withdrawals and deposits

### ISSUE THREAD

**Issue by Ditti4** [emansih/FireflyMobile#7]
**Firefly III Server Version:** 4.7.7

**Firefly III Mobile Version:** 0.06

**Android Version:** 6.0.1

**Device Information:**  

- BRAND: Xiaomi
- MODEL: Redmi 3s Prime
--------------------------------------

## Expected Behavior
When creating a withdrawal, the destination account shouldn't be one of my asset accounts, but rather an expense account like "Netflix" or "Amazon". Same goes for deposits and their source accounts. The easiest way to do that would be to have those fields auto-completed text fields.

## Current Behavior
Currently, withdrawals and deposits have the same spinner content for the source and destination account, making it impossible to create anything but transfers.

## Steps to Reproduce
Go to "Expenses" or "Revenue/Income" and create a transaction using the FAB. You can find a screenshot here: https://i.imgur.com/qS2CpKf.png

**Comment by emansih** [comment]
Correct me if i am wrong, when submitting transaction info, the source and destination accounts must only be assets account. is it not?

**Comment by Ditti4** [comment]
This is what [the docs](https://firefly-iii.readthedocs.io/en/latest/api/transactions.html#create-transaction) say:

> `transactions[*][source_id]` OR `transactions[*][source_name]`. The source account of the transaction. Must be an existing asset account for transfers and withdrawals. **May be a new revenue account for deposits.** You can leave both blank in a deposit to create a cash deposit.
> `transactions[*][destination_id]` OR `transactions[*][destination_name]`. The destination account of the transaction. Must be an existing asset account for transfers and deposits. May both be blank for a cash withdrawal, or **create a new expense account for withdrawals (fill in only the name).**

(emphasis mine)

So how I read it is: put in a source/destination name for a deposit/withdrawal and Firefly III will either match that to an existing revenue/expense account (like "Amazon", "Netflix", "Employer") or create a new one, just like the normal web interface does.

**Comment by Ditti4** [comment]
I'm not really sure if any of my comment attempts made it through (getting 500 errors from Github), so let's try again:

This is what [the docs](https://firefly-iii.readthedocs.io/en/latest/api/transactions.html#create-transaction) say:

> `transactions[*][source_id]` OR `transactions[*][source_name]`. The source account of the transaction. Must be an existing asset account for transfers and withdrawals. **May be a new revenue account for deposits.** You can leave both blank in a deposit to create a cash deposit.
> `transactions[*][destination_id]` OR `transactions[*][destination_name]`. The destination account of the transaction. Must be an existing asset account for transfers and deposits. May both be blank for a cash withdrawal, or **create a new expense account for withdrawals (fill in only the name).**

(emphasis mine)

So how I read it is: put in a source/destination name for a deposit/withdrawal and Firefly III will either match that to an existing revenue/expense account (like "Amazon", "Netflix", "Employer") or create a new one, just like the normal web interface does.

**Comment by Ditti4** [comment]
I mean, it works in case of a source account for a withdrawal - but the expense account should still be a text field. 😉

**Comment by Ditti4** [comment]
I just tried out the new version and I think we kind of misunderstood each other. In case of a withdrawal, the "Source account" (where the money's coming from) should be an asset account, like in your screenshot above. The "Expense account" (where the money goes, see https://demo.firefly-iii.org/accounts/expense), however, is usually something like a store, for example, not an asset account. In case of a deposit, the "Destination account" should be an asset account (where the money goes) while the "Revenue account" (where the money is coming from, see https://demo.firefly-iii.org/accounts/revenue) could be, for example, your employer.

Currently, all of these different account types use the same value sets (asset accounts), while in reality it should be three different value sets (asset accounts, expense accounts, revenue accounts).

I do like the idea of using the spinner for all cases where an asset account is needed, but using the spinner for the expense/revenue accounts is not the best option in my opinion.

**Comment by mconway** [comment]
Since I got name dropped here, I can at least mention how I did it. For a transfer, both the destination and source accounts use the asset accounts list.
For a withdrawal, the destination account is based on the expense accounts list
For a deposit, the source account is based on the revenue accounts list.

Hope that helps!

**Comment by Ditti4** [comment]
Just installed 0.1.0 and that's way better. Thank you so much for your hard work! :+1:
