### ISSUE TITLE
Error in AndroidStudio

### ISSUE THREAD

**Issue by KatiaSishost** [emansih/FireflyMobile#70]
Hello, im trying to compile the app but i have this error

ERROR: path may not be null or empty string. path='null'

Im trying with MASTER and DEV branches

**Comment by emansih** [comment]
That error doesn't say anything though. Is there any logs above or below it?

**Comment by KatiaSishost** [comment]
path may not be null or empty string. path='null' <a href="openFile:D:\Android\app\build.gradle">Open File</a>

and build.gradle:

`apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'com.akaita.android.easylauncher'
apply plugin: "com.github.ben-manes.versions"
apply plugin: 'org.owasp.dependencycheck'

android {
    compileSdkVersion(Dependencies.compileSdk)
    defaultConfig {
        applicationId "xyz.hisname.fireflyiii"
        minSdkVersion(Dependencies.minSdk)
        targetSdkVersion(Dependencies.targetSdk)
        versionCode 47
        versionName "1.4.2"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        def appConfigFile = file('config.properties')
        def hostName = ""
        if(appConfigFile.exists()){
            Properties appConfig = new Properties()
            appConfig.load(new FileInputStream(appConfigFile))
            if(appConfig['config.hostname'] != null){
                hostName = appConfig['config.hostname']
                manifestPlaceholders = [host: hostName.replaceAll('"', '')]
            }
        } else {
            throw new FileNotFoundException("$appConfigFile not found!")
        }
        buildConfigField("String", "HOSTNAME", hostName)
    }

    signingConfigs {
        githubRelease {
            storeFile file(System.getenv("FireflyKeystoreFile"))
            storePassword System.getenv("FireflyKeystorePassword")
            keyAlias System.getenv("FireflyKeystoreAlias")
            keyPassword System.getenv("FireflyKeystorePassword")
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            matchingFallbacks = ['release']
            shrinkResources true
        }
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix "-debug"
            minifyEnabled false
            matchingFallbacks = ['debug']
        }
        // This build type is no different from `release` except that it run unit tests and change the apk name
        // It's created so that it is compatible with Fdroid build system
        githubRelease{
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            matchingFallbacks = ['release']
            signingConfig signingConfigs.githubRelease
            shrinkResources true
            applicationVariants.all { variant ->
                variant.outputs.all {
                    outputFileName = "v${versionName}-firefly.apk"
                }
            }
        }
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8
        }
    }

    aaptOptions {
        ignoreAssetsPattern "NOTICE.txt"
    }
	
    configurations {all*.exclude group: 'com.android.support'}
}

afterEvaluate {
    if(name == "assembleGithubRelease"){
        assembleGithubRelease.dependsOn test
        assembleGithubRelease.dependsOn tasks.dependencyCheckAnalyze
    }
}

dependencies {

    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation Dependencies.kotlinLib
    // Android support libs
    implementation Dependencies.appCompat
    implementation Dependencies.androidxFragment
    implementation Dependencies.androidxAnnotation
    implementation Dependencies.androidxRecyclerView
    implementation Dependencies.materialDesign
    implementation Dependencies.androidxCore
    implementation Dependencies.androidxConstraintLayout
    implementation Dependencies.androidxPref
    implementation Dependencies.androidxWork
    implementation Dependencies.multiDex
    implementation Dependencies.swipeRefreshLayout

    // Lifecycle component
    implementation Dependencies.lifecycleLibs
    implementation Dependencies.lifecyclerLiveDataCore
    kapt Dependencies.lifecycleCompiler

    // Room
    implementation Dependencies.roomLibs
    kapt Dependencies.roomCompiler
    // Retrofit
    implementation Dependencies.retrofitLibs
    implementation Dependencies.retrofitGson
    implementation("com.squareup.retrofit2:converter-scalars:2.6.0")

    // Coroutine
    implementation Dependencies.coroutineCore
    implementation Dependencies.coroutineAndroid

    // Glide
    implementation Dependencies.glideLib
    implementation Dependencies.glideOkHttpExtension
    kapt Dependencies.glideCompiler

    implementation Dependencies.materialDrawer
    implementation Dependencies.iconics
    implementation Dependencies.googleMaterialIcons
    implementation Dependencies.fontAwesome

    implementation Dependencies.toasty
    implementation Dependencies.threeTenBp
    implementation Dependencies.chart
    implementation Dependencies.aboutLib
    implementation Dependencies.nachos
    implementation Dependencies.acraMail
    implementation Dependencies.osmdroid
    implementation Dependencies.accordionView
    implementation Dependencies.fancyshowcaseview

    implementation Dependencies.markdownLib
    implementation Dependencies.markdownStrikeThroughExtension
    implementation Dependencies.markdownAutoLink

    // Project Lib
    api project(path: ":languagepack")

    testImplementation Dependencies.jUnit
    debugImplementation Dependencies.debugDb
}`

**Comment by emansih** [comment]
From what I can tell, you are trying to build   'assembleGithubRelease' and you do not have a valid keystore in your system environment. For obvious reasons, I do not upload my keystore onto GitHub. A quick fix will be to build 'assembleDebug' instead
