### ISSUE TITLE
Error in compiled version from 1.4.0 & f-droid

### ISSUE THREAD

**Issue by KatiaSishost** [emansih/FireflyMobile#71]
after loggin with PAT.

REPORT_ID=a35817f8-09a0-4d80-8aab-db17383a52b2
APP_VERSION_NAME=1.4.0
PHONE_MODEL=SM-G935F
BRAND=samsung
PRODUCT=hero2ltexx
ANDROID_VERSION=8.0.0
BUILD_CONFIG=
STACK_TRACE=java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	... 1 more
Caused by: org.json.JSONException: Value [] of type org.json.JSONArray cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONObject.<init>(JSONObject.java:163)
	at org.json.JSONObject.<init>(JSONObject.java:176)
	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:4)
	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:1)
	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
	at i.l.run(DefaultCallAdapterFactory.java:3)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	... 3 more

LOGCAT=10-01 12:41:52.685 I/MultiDex( 1073): VM with version 2.1.0 has multidex support
10-01 12:41:52.685 I/MultiDex( 1073): Installing application
10-01 12:41:52.685 I/MultiDex( 1073): VM has multidex support, MultiDex support library is disabled.
10-01 12:41:52.745 I/ACRA    ( 1073): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
10-01 12:41:52.814 D/NetworkSecurityConfig( 1073): Using Network Security Config from resource network_security_config debugBuild: false
10-01 12:41:52.822 I/MaterialDrawer( 1073): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
10-01 12:41:52.915 D/skia    ( 1073): approximate: numPoints=51, lengths[0]=0.000000, totalLength=620.200073, segmentPoints[0]=[-197.600006,0.000000]
10-01 12:41:52.915 D/skia    ( 1073): approximate: approximation[0]=0.000000, approximation[1]=-197.600006, approximation[2]=0.000000
10-01 12:41:52.915 D/skia    ( 1073): approximate: numPoints=51, lengths[50]=620.200073, totalLength=620.200073, segmentPoints[50]=[422.600037,0.000000]
10-01 12:41:52.915 D/skia    ( 1073): approximate: approximation[150]=1.000000, approximation[151]=422.600037, approximation[152]=0.000000
10-01 12:41:52.915 D/skia    ( 1073): approximate: numPoints=4, lengths[0]=0.000000, totalLength=3.448155, segmentPoints[0]=[0.000000,0.100000]
10-01 12:41:52.915 D/skia    ( 1073): approximate: approximation[0]=0.000000, approximation[1]=0.000000, approximation[2]=0.100000
10-01 12:41:52.915 D/skia    ( 1073): approximate: numPoints=4, lengths[3]=3.448155, totalLength=3.448155, segmentPoints[3]=[3.000000,0.100000]
10-01 12:41:52.915 D/skia    ( 1073): approximate: approximation[9]=1.000000, approximation[10]=3.000000, approximation[11]=0.100000
10-01 12:41:52.916 D/skia    ( 1073): approximate: numPoints=47, lengths[0]=0.000000, totalLength=722.199951, segmentPoints[0]=[-522.599976,0.000000]
10-01 12:41:52.916 D/skia    ( 1073): approximate: approximation[0]=0.000000, approximation[1]=-522.599976, approximation[2]=0.000000
10-01 12:41:52.916 D/skia    ( 1073): approximate: numPoints=47, lengths[46]=722.199951, totalLength=722.199951, segmentPoints[46]=[199.600006,0.000000]
10-01 12:41:52.916 D/skia    ( 1073): approximate: approximation[138]=1.000000, approximation[139]=199.600006, approximation[140]=0.000000
10-01 12:41:52.916 D/skia    ( 1073): approximate: numPoints=3, lengths[0]=0.000000, totalLength=2.472497, segmentPoints[0]=[0.000000,0.100000]
10-01 12:41:52.916 D/skia    ( 1073): approximate: approximation[0]=0.000000, approximation[1]=0.000000, approximation[2]=0.100000
10-01 12:41:52.916 D/skia    ( 1073): approximate: numPoints=3, lengths[2]=2.472497, totalLength=2.472497, segmentPoints[2]=[2.000000,0.100000]
10-01 12:41:52.916 D/skia    ( 1073): approximate: approximation[6]=1.000000, approximation[7]=2.000000, approximation[8]=0.100000
10-01 12:41:52.927 I/zygote64( 1073): Do partial code cache collection, code=26KB, data=19KB
10-01 12:41:52.928 I/zygote64( 1073): After code cache collection, code=26KB, data=19KB
10-01 12:41:52.928 I/zygote64( 1073): Increasing code cache capacity to 128KB
10-01 12:41:52.998 D/OpenGLRenderer( 1073): HWUI GL Pipeline
10-01 12:41:53.004 D/ViewRootImpl@eef74f7[HomeActivity]( 1073): setView = DecorView@fa23f64[HomeActivity] TM=true MM=false
10-01 12:41:53.006 I/zygote64( 1073): Do partial code cache collection, code=54KB, data=39KB
10-01 12:41:53.006 I/zygote64( 1073): After code cache collection, code=54KB, data=39KB
10-01 12:41:53.006 I/zygote64( 1073): Increasing code cache capacity to 256KB
10-01 12:41:53.017 V/InputMethodManager( 1073): Not IME target window, ignoring
10-01 12:41:53.017 D/ViewRootImpl@eef74f7[HomeActivity]( 1073): dispatchAttachedToWindow
10-01 12:41:53.133 I/zygote64( 1073): Do full code cache collection, code=123KB, data=86KB
10-01 12:41:53.134 I/zygote64( 1073): After code cache collection, code=66KB, data=39KB
10-01 12:41:53.142 V/Surface ( 1073): sf_framedrop debug : 0x4f4c, game : false, logging : 0
10-01 12:41:53.142 D/ViewRootImpl@eef74f7[HomeActivity]( 1073): Relayout returned: old=[0,0][0,0] new=[0,0][1080,1920] result=0x7 surface={valid=true 513802178560} changed=true
10-01 12:41:53.146 I/OpenGLRenderer( 1073): Initialized EGL, version 1.4
10-01 12:41:53.146 D/OpenGLRenderer( 1073): Swap behavior 2
10-01 12:41:53.150 D/libGLESv1( 1073): STS_GLApi : DTS, ODTC are not allowed for Package : xyz.hisname.fireflyiii
10-01 12:41:53.151 D/mali_winsys( 1073): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [1080x1920]-format:1
10-01 12:41:53.151 D/OpenGLRenderer( 1073): eglCreateWindowSurface = 0x77a8c1e770
10-01 12:41:53.219 E/RecyclerView( 1073): No adapter attached; skipping layout
10-01 12:41:53.222 I/zygote64( 1073): Deoptimizing void a.e.b.a.i.L() due to JIT inline cache
10-01 12:41:53.223 W/StaticLayout( 1073): maxLineHeight should not be -1.  maxLines:1 lineCount:1
10-01 12:41:53.228 I/zygote64( 1073): Do partial code cache collection, code=126KB, data=75KB
10-01 12:41:53.229 I/zygote64( 1073): After code cache collection, code=106KB, data=67KB
10-01 12:41:53.229 I/zygote64( 1073): Increasing code cache capacity to 512KB
10-01 12:41:53.300 D/ViewRootImpl@eef74f7[HomeActivity]( 1073): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 1920) ci=Rect(0, 72 - 0, 0) vi=Rect(0, 72 - 0, 0) or=1
10-01 12:41:53.300 D/ViewRootImpl@eef74f7[HomeActivity]( 1073): MSG_WINDOW_FOCUS_CHANGED 1
10-01 12:41:53.306 V/InputMethodManager( 1073): Starting input: tba=android.view.inputmethod.EditorInfo@3295cfc nm : xyz.hisname.fireflyiii ic=null
10-01 12:41:53.306 I/InputMethodManager( 1073): startInputInner - mService.startInputOrWindowGainedFocus
10-01 12:41:53.325 V/InputMethodManager( 1073): Starting input: tba=android.view.inputmethod.EditorInfo@ae93465 nm : xyz.hisname.fireflyiii ic=null
10-01 12:41:54.460 D/ViewRootImpl@eef74f7[HomeActivity]( 1073): Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x1 surface={valid=true 513802178560} changed=false
10-01 12:41:54.527 I/zygote64( 1073): Do full code cache collection, code=238KB, data=145KB
10-01 12:41:54.527 I/zygote64( 1073): After code cache collection, code=212KB, data=119KB
10-01 12:41:54.599 I/zygote64( 1073): Do partial code cache collection, code=225KB, data=125KB
10-01 12:41:54.600 I/zygote64( 1073): After code cache collection, code=225KB, data=125KB
10-01 12:41:54.600 I/zygote64( 1073): Increasing code cache capacity to 1024KB
10-01 12:41:55.293 D/AndroidRuntime( 1073): Shutting down VM
10-01 12:41:55.298 E/AndroidRuntime( 1073): FATAL EXCEPTION: main
10-01 12:41:55.298 E/AndroidRuntime( 1073): Process: xyz.hisname.fireflyiii, PID: 1073
10-01 12:41:55.298 E/AndroidRuntime( 1073): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
10-01 12:41:55.298 E/AndroidRuntime( 1073): Caused by: java.lang.reflect.InvocationTargetException
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at java.lang.reflect.Method.invoke(Native Method)
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	... 1 more
10-01 12:41:55.298 E/AndroidRuntime( 1073): Caused by: org.json.JSONException: Value [] of type org.json.JSONArray cannot be converted to JSONObject
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at org.json.JSON.typeMismatch(JSON.java:111)
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at org.json.JSONObject.<init>(JSONObject.java:163)
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at org.json.JSONObject.<init>(JSONObject.java:176)
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:4)
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:1)
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at i.l.run(DefaultCallAdapterFactory.java:3)
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at android.os.Handler.handleCallback(Handler.java:789)
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at android.os.Handler.dispatchMessage(Handler.java:98)
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at android.os.Looper.loop(Looper.java:164)
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
10-01 12:41:55.298 E/AndroidRuntime( 1073): 	... 3 more
10-01 12:41:55.300 E/ACRA    ( 1073): ACRA caught a RuntimeException for xyz.hisname.fireflyiii
10-01 12:41:55.300 E/ACRA    ( 1073): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
10-01 12:41:55.300 E/ACRA    ( 1073): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
10-01 12:41:55.300 E/ACRA    ( 1073): Caused by: java.lang.reflect.InvocationTargetException
10-01 12:41:55.300 E/ACRA    ( 1073): 	at java.lang.reflect.Method.invoke(Native Method)
10-01 12:41:55.300 E/ACRA    ( 1073): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
10-01 12:41:55.300 E/ACRA    ( 1073): 	... 1 more
10-01 12:41:55.300 E/ACRA    ( 1073): Caused by: org.json.JSONException: Value [] of type org.json.JSONArray cannot be converted to JSONObject
10-01 12:41:55.300 E/ACRA    ( 1073): 	at org.json.JSON.typeMismatch(JSON.java:111)
10-01 12:41:55.300 E/ACRA    ( 1073): 	at org.json.JSONObject.<init>(JSONObject.java:163)
10-01 12:41:55.300 E/ACRA    ( 1073): 	at org.json.JSONObject.<init>(JSONObject.java:176)
10-01 12:41:55.300 E/ACRA    ( 1073): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:4)
10-01 12:41:55.300 E/ACRA    ( 1073): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:1)
10-01 12:41:55.300 E/ACRA    ( 1073): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
10-01 12:41:55.300 E/ACRA    ( 1073): 	at i.l.run(DefaultCallAdapterFactory.java:3)
10-01 12:41:55.300 E/ACRA    ( 1073): 	at android.os.Handler.handleCallback(Handler.java:789)
10-01 12:41:55.300 E/ACRA    ( 1073): 	at android.os.Handler.dispatchMessage(Handler.java:98)
10-01 12:41:55.300 E/ACRA    ( 1073): 	at android.os.Looper.loop(Looper.java:164)
10-01 12:41:55.300 E/ACRA    ( 1073): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
10-01 12:41:55.300 E/ACRA    ( 1073): 	... 3 more
IS_SILENT=false
USER_CRASH_DATE=2019-10-01T12:41:55.319-03:00

**Comment by emansih** [comment]
I see your APK version is 1.4.0, latest is v1.4.2 though.
