### ISSUE TITLE
Show whats missing when creating new withdrawal

### ISSUE THREAD

**Issue by natrius** [emansih/FireflyMobile#72]
**Firefly III Mobile Version:**

1.4.3

**Android Version:**  

9

**Device Information:**  

- BRAND: Xiaomi
- MODEL: Mi 9
--------------------------------------

## Expected Behavior

Show whats missing when inputting a new withdrawal without description. "Description is a necessary field."

## Current Behavior

"Error occurred while saving transaction"

## Steps to Reproduce

- Open App
- "+"
- Input Info, not writing description
- press "+" in the right top corner
- Error

**Comment by emansih** [comment]
I am unable to replicate this bug
![firefly-mobile-screenshot-issue-72](https://user-images.githubusercontent.com/5896415/68207150-52147700-0009-11ea-927d-00ebdf13d968.png)
.

**Comment by emansih** [comment]
sorry, i misunderstand your issue. Are you trying to say that an entry should be possible without description?

**Comment by emansih** [comment]
Oh I understand now.... The error message is shown from Firefly III itself.  It reduces the amount of parsing needed to be done by me.

**Comment by natrius** [comment]
Ah, i see. So i have to direct it to fireflyiii itself. Thanks :)

**Comment by emansih** [comment]
Well, I can do local parsing and I have some design mockups. What do you think?

![Firefly-ShowcaseView](https://user-images.githubusercontent.com/5896415/68278317-049d1600-00ac-11ea-9dab-9d339724029d.png)


![Firefly-Tooltip](https://user-images.githubusercontent.com/5896415/68278324-07980680-00ac-11ea-9f21-11ed440dd85e.png)

**Comment by emansih** [comment]
Personally I think the first one is nicer

**Comment by natrius** [comment]
Yepp, the first one is really nice. 

(I would prefer the description is not needed, but thats a fireflyiii thing, not yours! )
