### ISSUE TITLE
Can't sign in with personal access token

### ISSUE THREAD

**Issue by dreamwhite** [emansih/FireflyMobile#77]
**Firefly III Server Version:**
 4.8.2
**Firefly III Mobile Version:**
1.4.6
**Android Version:**  
10
**Device Information:**  

- BRAND:  OnePlus
- MODEL: 6T
--------------------------------------

## Expected Behavior
Login with personal access toek 
## Current Behavior
App crashes
## Steps to Reproduce
Login with personal access token

**Comment by emansih** [comment]
Self signed cert?

**Comment by dreamwhite** [comment]
Nope. Tried with another Firefly app but it works. Seems like that the FireFly app doesn't work as expected

**Comment by emansih** [comment]
Are you using https?
