### ISSUE TITLE
Dashboard shows wrong amounts for "Overview" and "List of Accounts"

### ISSUE THREAD

**Issue by Ditti4** [emansih/FireflyMobile#8]
**Firefly III Server Version:** 4.7.7

**Firefly III Mobile Version:** 0.1.0

**Android Version:** 8.1

**Device Information:** 

- BRAND: Xiaomi
- MODEL: Redmi 3s Prime
--------------------------------------

## Expected Behavior
The "Cash" and "Credit Card" cards on the dashboard should show the correct amount, in my case 0 as I don't use the built-in cash wallet and have no liabilities in my Firefly instance. Additionally, the "Overview" card should also display the correct amounts.

## Current Behavior
Currently both of these cards show the exact amount of "10979" on my phone. When connected to the demo instance, all of the three cards show an amount of "5771" and the "Overview" card shows some pretty wild numbers:

![image](https://user-images.githubusercontent.com/1223152/47621612-af264480-dafa-11e8-8b75-1ef9eb2b7ca2.png)

Based on the Firefly web interface, this is what the overview should show for the demo instance:

![image](https://user-images.githubusercontent.com/1223152/47621627-e1d03d00-dafa-11e8-9aec-324189643b46.png)

## Steps to Reproduce
Connect the newest version of the app to the official Firefly demo instance and check out the dashboard.

**Comment by emansih** [comment]
See point 4. https://github.com/emansih/FireflyMobile#known-limitations--bugs

**Comment by Ditti4** [comment]
I just thought that by "at times" you meant that it works most of the time, which isn't the case for me 😀

**Comment by emansih** [comment]
yea, it's a trade off really.  I have allowed users to view their data offline but I have also messed up parts of the codebase. I'm still trying to learn more on LiveData and ViewModel to use them correctly.

**Comment by emansih** [comment]
Fix in the latest release(v0.1.1)
