### ISSUE TITLE
Split transaction

### ISSUE THREAD

**Issue by bestlibre** [emansih/FireflyMobile#87]
Is it possible to create split transaction from the mobile app ? 

If it's not possible, could it be added ?

Thanks

**Comment by emansih** [comment]
I'm not sure if the API allows me. I will take a look. On 11 Mar 2020 5:20 pm, bestlibre <notifications@github.com> wrote:Is it possible to create split transaction from the mobile app ?
If it's not possible, could it be added ?
Thanks

**Comment by emansih** [comment]
I have added this feature in the latest release,4.0.1, after almost a year. I will be closing this issue.

**Comment by gamelaster** [comment]
Thank you @emansih
