### ISSUE TITLE
The quick add screen for a transaction should allow adding an attachment

### ISSUE THREAD

**Issue by darnir** [emansih/FireflyMobile#88]
**Firefly III Server Version:**
5.1.1

**Firefly III Mobile Version:**
2.0.3

**Android Version:**  
8.0.0

**Device Information:**  

- BRAND: Motorola
- MODEL:  Z2 Play
--------------------------------------

## Expected Behavior
The quick add screen for a transaction should allow adding an attachment.

## Current Behavior
Only the transaction edit screen allows adding an attachment

P.S.: Would it be possible to also provide a way to take a photograph from the app and set it as an attachment? It unfortunately needs an extra permission though.

**Comment by emansih** [comment]
It is working as intended since the API does not allow users to add an attachment while creating a new transaction.

**Comment by darnir** [comment]
I see. Thanks for letting me know. I'll open a request with Firefly-III first to add this feature.

**Comment by emansih** [comment]
@darnir There was an issue opened long ago by me. It was deleted? disappeared? in one of the Firefly III API docs repo. Basically, James says that it takes too much work.
