### ISSUE TITLE
Back button not working in piggy banks

### ISSUE THREAD

**Issue by TheObserver6995** [emansih/FireflyMobile#89]
**Firefly III Server Version:**
4.8.2
**Firefly III Mobile Version:**
2.0.3 F-Droid
**Android Version:**  
9
**Device Information:**  

- BRAND: Oneplus
- MODEL: 6
Using a Custom ROM without official Google Play Services, but with microG.
--------------------------------------

## Expected Behavior
Should be able to go back at any point.
## Current Behavior
Back button - device and app build in - not working in the detail view of piggy bank.
## Steps to Reproduce
Open the app, select piggy bank under money management and open one of the existing piggy banks. When pressing the back button, nothing happens.

**Comment by emansih** [comment]
I finally have some time this weekend. I will look into it. I promise

**Comment by emansih** [comment]
@TheObserver6995 Hello, I have fixed the issue and will release a fix later this week. Thanks!
