### ISSUE TITLE
Trying oauth (works in another app), get error message

### ISSUE THREAD

**Issue by TobiasDev** [emansih/FireflyMobile#9]
**Firefly III Server Version:**
4.7.7

**Firefly III Mobile Version:**
0.1.0

When I try to log in, it opens chrome, but it gives me this message after I logged in: {"error": "invalid_client", "message": "Client authentication failed"} 

I tried updating the http://empty to https, and it still doesn't work. I get to the part where I'm allowed to log in, however after that I get this message. 

When I try the other login option, the client just keeps on loading forever, but never actually logging in. 

I managed to find my other issue here: https://github.com/mconway/firefly-app/issues/12 If that would help in anyway.

**Comment by TobiasDev** [comment]
After fiddling around a bit, with changing from https to http, etc, and such for my thing I think I managed to get it a step further, now I get a error "Web page not available. I wonder if this has something to do with the softacolus installation of Firefly. (I had this issue in another app), because installing with softacolus, installs it into "https://yourdomain.com/public, in the other app I think the /public part broke something in the app.

**Comment by emansih** [comment]
`{"error": "invalid_client", "message": "Client authentication failed"}`
This message is shown because you are using mismatched client secret / client id. Ensure you are using the correct pair of client secret and client id. 

![bug](https://user-images.githubusercontent.com/5896415/47851084-88c21b00-de12-11e8-8aff-169dd87a3986.PNG)


You don't have to input http prefix, the software is smart enough to add it for you ;) https://github.com/emansih/FireflyMobile/blob/87cfff510ed0c390372fae9c1ff5d72a52aefe42/app/src/main/java/xyz/hisname/fireflyiii/ui/onboarding/LoginFragment.kt#L75

**Comment by TobiasDev** [comment]
I double checked the secret and it looks correct. I'll try and create a new one and see if that works.

**Comment by TobiasDev** [comment]
> 
> 
> `{"error": "invalid_client", "message": "Client authentication failed"}`
> This message is shown because you are using mismatched client secret / client id. Ensure you are using the correct pair of client secret and client id.
> 
> ![bug](https://user-images.githubusercontent.com/5896415/47851084-88c21b00-de12-11e8-8aff-169dd87a3986.PNG)
> 
> You don't have to input http prefix, the software is smart enough to add it for you ;) https://github.com/emansih/FireflyMobile/blob/87cfff510ed0c390372fae9c1ff5d72a52aefe42/app/src/main/java/xyz/hisname/fireflyiii/ui/onboarding/LoginFragment.kt#L75

I just tried making a new client, and now I got another error: "Web page not availabe" - http://empty/?code=loads of numbers

**Comment by emansih** [comment]
it appears that the URI is not redirecting. Can i have a test account for your Firefly III instance?

**Comment by TobiasDev** [comment]
> 
> 
> it appears that the URI is not redirecting. Can i have a test account for your Firefly III instance?

Yep, (I'll delete this when you have tested. :) ) 

website: fin.postnow.eu
Mail: temp@postnow.eu
Pass: test

**Comment by emansih** [comment]
something is terribly wrong with your installation. 

**Not Found**

The requested URL /oauth/authorize was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by TobiasDev** [comment]
Sorry, you need to write /public eg: fin.postnow.eu/public

**Comment by emansih** [comment]
ah! that's the problem. your instance is redirecting me to `https://fin.postnow.eu/oauth/token` instead of `https://fin.postnow.eu/public/oauth/token`

**Comment by TobiasDev** [comment]
Huh... Really? I thought that was changed with the issue I posted above. Is it something in the Firefly app?

**Comment by TobiasDev** [comment]
Yeah, but I just double checked the file and it is correct there. The fix was for 4.7.7. :)

**Comment by emansih** [comment]
I have enabled logging in retrofit library and it shows me this
```
Response{protocol=h2, code=404, message=, url=https://fin.postnow.eu/oauth/token}
```

**Comment by TobiasDev** [comment]
> 
> 
> I have enabled logging in retrofit library and it shows me this
> 
> ```
> Response{protocol=h2, code=404, message=, url=https://fin.postnow.eu/oauth/token}
> ```
> 
> This needs some serious investigation

Wow... That seems really weird. Is that part of the Firefly instance? I wonder if I should try and force my domain in the file and see if that works (literally giving it my domain address, eg fin.domain.com/public/oauth, etc

**Comment by emansih** [comment]
it's a bug in my code, i will investigate, nothing to do on your end

**Comment by TobiasDev** [comment]
> 
> 
> it's a bug in my code, i will investigate, nothing to do on your end

Got it! Thanks for the help!

**Comment by TobiasDev** [comment]
> hey. i'm stuck at this issue for quite some time now. Every request(https://fin.postnow.eu/public) that i made gets redirected to https://fin.postnow.eu/ for some reason.

Hmm. That sucks. :( Not sure if I could do anything to help, but sadly don't think I can.

**Comment by emansih** [comment]
thanks for this bug report and the test account. this bug has been fixed. i will be releasing an updated apk soon. do report back if you find anymore bugs

**Comment by TobiasDev** [comment]
Thanks for looking into this! Do I need to do something different in the settings? Because now whenever I press allow, it takes me to Google, searching for the http://empty + loads of text. Eg. Should my re direct be something different now?

**Comment by emansih** [comment]
Are you using Chrome? I have redirection issues with Firefox

**Comment by TobiasDev** [comment]
Aha! I changed to Chrome and that fixed the issue! I'm normally using Bromite. :) But I just used Chrome to log in and it worked! Thanks. Now I get to try the app!
