### ISSUE TITLE
Unable to add new spend

### ISSUE THREAD

**Issue by derritter88** [emansih/FireflyMobile#92]
**Firefly III Server Version:** 5.2.1

**Firefly III Mobile Version:** 2.0.3

**Android Version:**  9

**Device Information:**  

- BRAND: BQ
- MODEL: Aquaris X2 Pro
--------------------------------------

## Expected Behavior

1. Open app
2. "Neue Buchung erstellen" (= create new transaction)
3. Fill out the required fields.
4. Push "+" button to add the transaction
5. Transaction is being transmitted to the server

## Current Behavior
1. Open app
2. "Neue Buchung erstellen" (= create new transaction)
3. Fill out the required fields.
4. Push "+" button to add the transaction and then the app crashes (see attached log)

## Steps to Reproduce
1. Open app
2. "Neue Buchung erstellen" (= create new transaction)
3. Fill out the required fields.
4. Push "+" button to add the transaction

[Fireflyiii-mobile.txt](https://github.com/emansih/FireflyMobile/files/4541115/Fireflyiii-mobile.txt)

**Comment by emansih** [comment]
there is an issue with your currency. are you submitting a valid currency?

**Comment by derritter88** [comment]
I am using EUR within the app and EUR is also the only valid currency on my server.

**Comment by derritter88** [comment]
Okay I found something interessting:
When I opened the app it said "Unauthorized" - I was also unable to sync any new transactions from my server to the app.
So I logged out on my mobilephone and logged in again via OAUTH. 
Now it works including my issue.

The only question: Why does the app crash and say currency issue instead of "You're not logged in." or something similar?

**Comment by emansih** [comment]
I only check if you have the correct authentication in the dashboard. I don't check other factors such as Firefly III returning other data when submitting transactions.  The code is a spaghetti mess and I don't have the time and resources to fix it now.

**Comment by derritter88** [comment]
Okay
