### ISSUE TITLE
the app doesn't launch if the virtual balance is a float

### ISSUE THREAD

**Issue by fenpaws** [emansih/FireflyMobile#94]
**Firefly III Server Version:** 5.2.5

**Firefly III Mobile Version:** 2.0.4.58

**Android Version:**  10

**Device Information:**  

- BRAND: OnePlus
- MODEL: 6T
--------------------------------------
## Expected Behavior
The app should launch with the correct balance with virtual balance.
## Current Behavior
App throes an exception that it wants an int for the virtual balance
`Expected an int but was 980.88 at line 1 collum 496 path $.data[0].attribute.virtual_balance`
## Steps to Reproduce
Change your virtual balance to a float, like in the error above. Then launch the app.
## Screenshot of the error
https://imgur.com/a/mG8R2fB

**Comment by emansih** [comment]
@fenpaws will be fixed in the next release.
