### ISSUE TITLE
can't see anything in  Liabilities

### ISSUE THREAD

**Issue by toyqiu** [emansih/FireflyMobile#95]
this is my  Liabilities page in web
![image](https://user-images.githubusercontent.com/479873/82920822-62427280-9faa-11ea-9bb0-8d7c8e91f2b2.png)

this is my Liabilities page in FireflyMobile
![Screenshot_20200526-234346_Firefly III Mobile](https://user-images.githubusercontent.com/479873/82921606-23f98300-9fab-11ea-9bca-0070505c81b9.jpg)
![Screenshot_20200526-234340_Firefly III Mobile](https://user-images.githubusercontent.com/479873/82921770-57d4a880-9fab-11ea-8aa0-c41c68696797.jpg)

**Comment by fabianski7** [comment]
this bug really exists. which version of firefly are you using @toyqiu?

My setup:
Server: 5.2.0
App: 2.0.5
API: 1.1.0

Besides not being able to visualize, you can't create any new entries either.

**Comment by fabianski7** [comment]
ping @emansih

**Comment by emansih** [comment]
will be fixed in the next release

**Comment by emansih** [comment]
Fixed in v2.0.6
