### ISSUE TITLE
Available money in budget does not decrease after spending money from budget

### ISSUE THREAD

**Issue by pbartyik** [emansih/FireflyMobile#97]
**Firefly III Server Version:**
5.2.8
**Firefly III Mobile Version:**
2.0.5
**Android Version:**  
10 , security patch 1 May 2020

**Device Information:**  

- BRAND: Nokia
- MODEL: 8 Sirocco
--------------------------------------

In app budget shows as always 100.0% available even after creating transactions (either via mobile or web) using budgets.

## Expected Behavior
Spent money decreases available amount in budget.

## Current Behavior
Spent money does not decrease available amount in budget.

## Steps to Reproduce
Install App
Set up budgets online
Add transaction from budget

Thank you for developing this app, it is very useful for adding transactions on the go. Would also love to see quick glance on the dashboard how much is left to spend in specific budgets, thus this bug is a bit annoying.

**Comment by emansih** [comment]
Which chart? 

This?

![chart](https://user-images.githubusercontent.com/5896415/85388785-df510f80-b589-11ea-9852-2c9861316c2f.png)


**OR**


![chart_details](https://user-images.githubusercontent.com/5896415/85388797-e37d2d00-b589-11ea-9b18-5b5d29ddb4e0.png)

**Comment by pbartyik** [comment]
yes, that is the one. Sorry for not attaching screenshot, it contains private numbers :)

**Comment by pbartyik** [comment]
@emansih thanks for the quick fix, can you please push the release to f-droid as well?

**Comment by emansih** [comment]
I don't control the builds on official Fdroid.
